# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=255, verbose_name='Name')),
                ('phone', models.TextField(max_length=15, verbose_name='Phone')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name_plural': 'Contacts',
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_size', models.CharField(choices=[('mm', 'Milimeters'), ('cm', 'Centimeters'), ('inch', 'inch')], default='mm', max_length=5, verbose_name='Unit Size')),
                ('widthSize', models.FloatField(verbose_name='Width Size')),
                ('longSize', models.FloatField(verbose_name='Long Size')),
                ('name', models.TextField(default='', max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', max_length=255, verbose_name='Description')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name_plural': 'Paper Types',
                'verbose_name': 'Paper Type',
            },
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('location', models.TextField(default='', max_length=255, verbose_name='Location')),
                ('geolocation', location_field.models.plain.PlainLocationField(max_length=63)),
                ('name', models.TextField(default='', max_length=255, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='../media/print_logos', verbose_name='Logo')),
                ('qualification', models.IntegerField(verbose_name='Qualification')),
                ('creation_date', models.DateField(verbose_name='Creation Date')),
                ('state', models.TextField(default='', max_length=255, verbose_name='State')),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('closeTime', models.TimeField(verbose_name='Close Time')),
                ('startDay', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=25, verbose_name='Start Day')),
                ('closeDay', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='fri', max_length=25, verbose_name='Close Day')),
                ('description', models.TextField(default='', max_length=255, verbose_name='Description')),
                ('advertisement', models.TextField(default='', max_length=255, verbose_name='Advertisement')),
                ('contacts', models.ManyToManyField(to='print.Contact', verbose_name='Contacts')),
                ('paperType', models.ManyToManyField(to='print.PaperType', verbose_name='Paper Types')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsible User')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name_plural': 'Printers',
                'verbose_name': 'Print',
            },
        ),
    ]
