# Generated by Django 2.2.13 on 2020-10-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massivereservations',
            name='days',
        ),
        migrations.CreateModel(
            name='ReservationRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('reserved_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations_management.ReservedProducts')),
            ],
        ),
    ]
