# Generated by Django 2.2.13 on 2020-10-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0002_auto_20201005_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedproducts',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reservedproducts',
            name='object_id',
        ),
        migrations.AddField(
            model_name='reservations',
            name='is_massive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservedproducts',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations_management.Reservations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='MassiveReservations',
        ),
    ]
