# Generated by Django 2.2.13 on 2020-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0003_auto_20201005_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedproducts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Processing'), (1, 'Requested'), (2, 'Accepted'), (3, 'Denied'), (4, 'Closed')], default=1),
            preserve_default=False,
        ),
    ]
