# Generated by Django 2.2.13 on 2020-10-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0005_auto_20201005_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Selected'), (1, 'Requested'), (2, 'Accepted'), (3, 'Denied'), (4, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Selected'), (1, 'Requested'), (2, 'Accepted'), (3, 'Denied'), (4, 'Closed')]),
        ),
    ]
