# Generated by Django 2.2.13 on 2020-10-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0006_auto_20201005_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['-status']},
        ),
    ]
