# Generated by Django 2.2.13 on 2020-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0007_auto_20201006_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Denied'), (3, 'Closed'), (4, 'Selected')], default=0),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Denied'), (3, 'Closed'), (4, 'Selected')]),
        ),
    ]
