# Generated by Django 2.2.13 on 2020-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0009_reservations_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedproducts',
            name='was_returned',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Denied'), (3, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Borrowed'), (2, 'Denied'), (3, 'Selected'), (4, 'Returned')], default=0),
        ),
    ]
