# Generated by Django 2.2.13 on 2020-10-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0010_auto_20201007_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
