# Generated by Django 2.2.13 on 2020-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0012_auto_20201009_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproducts',
            name='amount_required',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='selectedproducts',
            name='final_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='selectedproducts',
            name='initial_date',
            field=models.DateTimeField(null=True),
        ),
    ]
