# Generated by Django 2.2.13 on 2020-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0013_auto_20201009_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproducts',
            name='amount_required',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='selectedproducts',
            name='final_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='selectedproducts',
            name='initial_date',
            field=models.DateTimeField(),
        ),
    ]
