# Generated by Django 2.2.13 on 2020-10-12 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations_management', '0016_auto_20201012_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedproducts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations_management.Reservations'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Borrowed'), (2, 'Denied'), (3, 'Selected'), (4, 'Returned')], default=3),
        ),
    ]
