# Generated by Django 2.2.13 on 2020-10-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0017_auto_20201012_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedProducts',
        ),
    ]
