# Generated by Django 2.2.13 on 2020-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0018_delete_selectedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedproducts',
            name='amount_returned',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
