# Generated by Django 2.2.13 on 2020-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0020_auto_20201013_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtasks',
            name='task_type',
            field=models.CharField(default='decrease', max_length=20),
            preserve_default=False,
        ),
    ]
