# Generated by Django 4.0.8 on 2022-11-29 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0062_remove_organizationusermanagement_group'),
        ('reservations_management', '0021_reservationtasks_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='is_massive',
            field=models.BooleanField(default=False, verbose_name='Is massive'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratory'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Denied'), (3, 'Closed')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='amount_required',
            field=models.FloatField(verbose_name='Amount Required'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='amount_returned',
            field=models.FloatField(default=0, verbose_name='Amount Returned'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='final_date',
            field=models.DateTimeField(verbose_name='Final Date'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='initial_date',
            field=models.DateTimeField(verbose_name='Initial Date'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='is_returnable',
            field=models.BooleanField(default=True, verbose_name='Is Returnable'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations_management.reservations', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Borrowed'), (2, 'Denied'), (3, 'Selected'), (4, 'Returned')], default=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservedproducts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
