# Generated by Django 4.0.8 on 2022-12-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0023_reservations_created_by_reservations_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='organization',
        ),
    ]
