# Generated by Django 4.0.8 on 2022-12-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0067_inform_created_by_inform_creation_date_and_more'),
        ('reservations_management', '0024_remove_reservations_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='laboratory',
        ),
        migrations.AddField(
            model_name='reservedproducts',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratory'),
        ),
    ]
