# Generated by Django 5.1 on 2025-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations_management", "0025_remove_reservations_laboratory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationrange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reservationtasks",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reservedproducts",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
