# Generated by Django 5.2.11 on 2026-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations_management",
            "0026_alter_reservationrange_id_alter_reservations_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedproducts",
            name="reserved_boxes",
            field=models.JSONField(
                default=list,
                help_text="List of reserved box entries: [{'code': 'b-0001', 'units': 12}]",
                verbose_name="Reserved boxes",
            ),
        ),
    ]
