# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('F', 'Furniture'), ('D', 'Drawer')], max_length=2, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Furniture',
                'verbose_name': 'Piece of furniture',
            },
        ),
        migrations.AlterModelOptions(
            name='laboratoryroom',
            options={'verbose_name': 'Laboratory Room', 'verbose_name_plural': 'Laboratory Rooms'},
        ),
        migrations.AddField(
            model_name='furniture',
            name='labroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.LaboratoryRoom'),
        ),
    ]
