# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_auto_20160808_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Furniture'), ('D', 'Drawer')], max_length=2, verbose_name='Type')),
                ('container_shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Shelf')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Furniture')),
            ],
            options={
                'verbose_name_plural': 'Shelves',
                'verbose_name': 'Shelf',
            },
        ),
    ]
