# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_auto_20160808_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='container_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.Shelf'),
        ),
    ]
