# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_auto_20160808_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='type',
            field=models.CharField(choices=[('C', 'Crate'), ('D', 'Drawer')], max_length=2, verbose_name='Type'),
        ),
    ]
