# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_auto_20160902_2040'),
        ('laboratory', '0006_shelf_name'),
    ]

    operations = [
    ]
