# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_auto_20160808_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfeatures',
            name='name',
            field=models.CharField(choices=[('0', 'General use'), ('1', 'Security equipment'), ('2', 'Analytic Chemistry'), ('3', 'Organic Chemistry'), ('4', 'Physical Chemistry'), ('5', 'Chemical and Biological process'), ('6', 'Industrial Biotechnology'), ('7', 'Biochemistry'), ('8', 'Water Chemistry'), ('9', 'Other')], max_length=2, verbose_name='Name'),
        ),
    ]
