# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_auto_20160808_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Reactive'), ('1', 'Material'), ('2', 'Equipment')], max_length=2, verbose_name='Type')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('feature', models.ManyToManyField(to='laboratory.ObjectFeatures')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Shelf')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
    ]
