# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Material quantity')),
                ('measurement_unit', models.CharField(choices=[('0', 'Meters'), ('1', 'Milimeters'), ('2', 'Centimeters'), ('3', 'Liters'), ('4', 'Mililiters')], max_length=2, verbose_name='Measurement unit')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Object')),
            ],
        ),
    ]
