# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_shelfobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfobject',
            options={'verbose_name': 'Shelf object', 'verbose_name_plural': 'Shelf objects'},
        ),
    ]
