# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0017_auto_20161222_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='lab_admins',
            field=models.ManyToManyField(blank=True, related_name='lab_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='laboratorists',
            field=models.ManyToManyField(blank=True, related_name='laboratorists', to=settings.AUTH_USER_MODEL),
        ),
    ]
