# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:49
from __future__ import unicode_literals

from django.db import migrations



def create_groups(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model("auth", "Group")
    groups = ['Laboratory Administrator', 'Professor', 'Student']
    for group in groups:
        if not Group.objects.filter(name=group).exists():
            Group.objects.create(name=group)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0022_auto_20170328_0932'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]

