# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0024_laboratory_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('cas_id_number', models.CharField(max_length=255, verbose_name='CAS ID number')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'C&L Inventory',
                'verbose_name_plural': 'C&L Inventory objects',
            },
        ),
    ]
