# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0025_auto_20180214_2007'),
        ('laboratory', '0026_auto_20170505_1359'),
    ]

    operations = [
    ]
