# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0027_merge_20180214_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstructure',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='laboratory.OrganizationStructure'),
        ),
        migrations.AlterField(
            model_name='principaltechnician',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.Laboratory'),
        ),
    ]
