# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 16:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0029_auto_20180214_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='organization',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_lab', to='laboratory.OrganizationStructure'),
        ),
    ]
