# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0027_solution_name'),
        ('laboratory', '0030_auto_20170505_1404'),
    ]

    operations = [
    ]
