# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0031_merge_20170511_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone')),
                ('id_card', models.CharField(max_length=100, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStruture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Laboratory name')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.OrganizationStruture')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.OrganizationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='geolocation',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='location',
            field=models.TextField(default='', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='phone_number',
            field=models.CharField(default='', max_length=25, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.LaboratoryAdmin'),
        ),
    ]
