# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('laboratory', '0032_auto_20180216_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryGroup',
            fields=[
                ('codename', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Codename')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clinventory',
            options={'permissions': (('view_clinventory', 'Can see available C&L Inventory'),), 'verbose_name': 'C&L Inventory', 'verbose_name_plural': 'C&L Inventory objects'},
        ),
        migrations.AlterModelOptions(
            name='feedbackentry',
            options={'permissions': (('view_feedbackentry', 'Can see available feed back entry'),), 'verbose_name': 'Feedback entry', 'verbose_name_plural': 'Feedback entries'},
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['name'], 'permissions': (('view_furniture', 'Can see available Furniture'),), 'verbose_name': 'Piece of furniture', 'verbose_name_plural': 'Furniture'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'permissions': (('view_laboratory', 'Can see available laboratory'),), 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryroom',
            options={'permissions': (('view_shelf', 'Can see available shelf'),), 'verbose_name': 'Laboratory Room', 'verbose_name_plural': 'Laboratory Rooms'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'permissions': (('view_object', 'Can see available object'),), 'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='objectfeatures',
            options={'permissions': (('view_objectfeatures', 'Can see available objectfeatures'),), 'verbose_name': 'Object feature', 'verbose_name_plural': 'Object features'},
        ),
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'permissions': (('view_organizationstructure', 'Can see available OrganizationStructure'),), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='principaltechnician',
            options={'permissions': (('view_principaltechnician', 'Can see available PrincipalTechnician'),)},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'permissions': (('view_shelf', 'Can see available shelf'),), 'verbose_name': 'Shelf', 'verbose_name_plural': 'Shelves'},
        ),
        migrations.AlterModelOptions(
            name='shelfobject',
            options={'permissions': (('view_shelfobjects', 'Can see available shelf objects'),), 'verbose_name': 'Shelf object', 'verbose_name_plural': 'Shelf objects'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'permissions': (('view_Solution', 'Can see available Solution'),), 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
    ]
