# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0033_auto_20180216_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principaltechnician',
            name='credentials',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
