# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0033_auto_20180213_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryadmin',
            name='credentils',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
