# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0033_auto_20180306_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'permissions': (('view_laboratory', 'Can see available laboratory'), ('view_report', 'Can see available reports'), ('do_report', 'Can download available reports')), 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
    ]
