# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 18:06
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.management import create_permissions

def add_missing_permissions(apps, Permission):
    ContentType = apps.get_model("contenttypes", "ContentType")
    model=apps.get_model('djreservation', "reservation")
    
    
    reservation = ContentType.objects.get_for_model(model)
    
    Permission.objects.create(content_type=reservation,
                                      codename="view_reservation",
                                      name="Can view available reservation")

def create_perms_groups(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None    
    
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    add_missing_permissions(apps, Permission)
    
    admin = Group.objects.get(name='Laboratory Administrator') 
    labs = Group.objects.get(name='Professor')
    student = Group.objects.get(name='Student')

    perms_student =[
         # reservations
        "view_reservation",
        "add_reservation",
        "change_reservation",
        "delete_reservation",
        
         #laboratory 
        "view_laboratory",
        "view_laboratoryroom",
        # procedures
        "view_procedure",
        "view_procedureobservations",
        ]

    perms_professor = [  
        # reservations
        "view_reservation", 
        "add_reservation",
        "change_reservation",
        "delete_reservation",
                
        # procedureobservations
        "view_procedureobservations",
        "add_procedureobservations",
        "change_procedureobservations",
        "delete_procedureobservations",
        
        # procedure
        "view_procedure",
        "add_procedure",
        "change_procedure",
        "delete_procedure",
        
        # procedurestep
        "view_procedurestep",
        "add_procedurestep", 
        "change_procedurestep",
        "delete_procedurestep",
        
        # procedurerequiredobject
        "view_procedurerequiredobject",
        "add_procedurerequiredobject",
        "change_procedurerequiredobject", 
        "delete_procedurerequiredobject",
        
        # solutions
        "view_solution",
        "add_solution",
        "change_solution",
        
        #laboratory
        "view_laboratory",
        "view_laboratoryroom"
        ]

    perms_admin = [ # reservations
        "add_reservation","change_reservation","delete_reservation","add_reservationtoken",
        "change_reservationtoken","delete_reservationtoken","view_reservation",

        # shelf
        "view_shelf","add_shelf","change_shelf","delete_shelf",        
        # shelfobjets 
        "view_shelfobject","add_shelfobject","change_shelfobject","delete_shelfobject",
        # objets         
        "view_object","add_object","change_object","delete_object",
        # objectfeatures        
        "view_objectfeatures","add_objectfeatures","change_objectfeatures","delete_objectfeatures",
        # procedurerequiredobject
        "view_procedurerequiredobject","add_procedurerequiredobject","change_procedurerequiredobject",
        "delete_procedurerequiredobject",
        # laboratory
        "view_laboratory","add_laboratory","change_laboratory","delete_laboratory",
        # laboratoryroom
        "view_laboratoryroom","add_laboratoryroom","change_laboratoryroom","delete_laboratoryroom",
        # furniture
        "view_furniture","add_furniture","change_furniture","delete_furniture",
        #Products
       # "view_product","add_product","change_product","delete_product",
        # procedureobservations
        "view_procedureobservations",
        "add_procedureobservations",
        "change_procedureobservations",
        "delete_procedureobservations",
        #CL Inventory
        "view_clinventory","add_clinventory","change_clinventory","delete_clinventory", 
        # solutions
        "view_solution","add_solution","change_solution","delete_solution",
        #reports
        "view_report","do_report",
        ]
    
    for perm in perms_student:
       
        student.permissions.add(Permission.objects.get(codename=perm))
    for perm in perms_professor:
        labs.permissions.add(Permission.objects.get(codename=perm))
    for perm in perms_admin:
        admin.permissions.add(Permission.objects.get(codename=perm))
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0034_auto_20180430_1343'),
        ('academic',  '0003_auto_20170508_1042'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('djreservation', '0006_reservationtoken_base_url'),
        ('auth', '0008_alter_user_username_max_length')
    ]

    operations = [
        migrations.RunPython(create_perms_groups),
    ]
