# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0034_laboratoryadmin_credentils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratoryadmin',
            old_name='credentils',
            new_name='credentials',
        ),
    ]
