# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0036_auto_20180213_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryadmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
