# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0037_auto_20180213_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryadmin',
            name='id_card',
            field=models.CharField(max_length=100, verbose_name='ID Card'),
        ),
        migrations.AlterField(
            model_name='organizationstruture',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
