# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('laboratory', '0038_auto_20180213_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='PrincipalTechnician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone')),
                ('id_card', models.CharField(max_length=100, verbose_name='ID Card')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('credentials', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratoryadmin',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='organizationstruture',
            name='father',
        ),
        migrations.RemoveField(
            model_name='organizationstruture',
            name='group',
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.PrincipalTechnician'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='Location'),
        ),
        migrations.DeleteModel(
            name='LaboratoryAdmin',
        ),
        migrations.DeleteModel(
            name='OrganizationStruture',
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='adminlab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.PrincipalTechnician'),
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.OrganizationStructure'),
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
