# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0039_auto_20180213_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='adminlab',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.PrincipalTechnician'),
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.PrincipalTechnician'),
        ),
        migrations.AlterField(
            model_name='principaltechnician',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
