# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0040_auto_20180213_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='technician',
        ),
        migrations.AddField(
            model_name='principaltechnician',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.Laboratory'),
        ),
        migrations.AddField(
            model_name='principaltechnician',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.OrganizationStructure'),
        ),
    ]
