# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 02:31
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0041_auto_20180213_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='geolocation',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
