# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 02:33
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0042_auto_20180213_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='geolocation',
            field=location_field.models.plain.PlainLocationField(default='9.925565912405506,-84.8583984375', max_length=63),
        ),
    ]
