# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 02:34
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0043_auto_20180213_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='geolocation',
            field=location_field.models.plain.PlainLocationField(default='9.895804362670006,-84.1552734375', max_length=63),
        ),
    ]
