# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0045_auto_20180214_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstructure',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.OrganizationStructure'),
        ),
    ]
