REPORT_FORMS ={
    'reactive_precursor': {
        'task':'report.tasks.task_report',
        'form':'report.forms.ValidateReportForm',
        'title':'List of reactive precursors',
        'html': 'report.views.objects.report_reactive_precursor_html',
        'pdf': 'report.views.objects.report_reactive_precursor_pdf',
        'xls': 'report.views.objects.report_reactive_precursor_doc',
        'xlsx': 'report.views.objects.report_reactive_precursor_doc',
        'ods': 'report.views.objects.report_reactive_precursor_doc',
    },
    'report_laboratory_room': {
        'task':'report.tasks.task_report',
        'form':'report.forms.ValidateLaboratoryRoomReportForm',
        'title':'Objects list by laboratory',
        'html':'report.views.lab_room.lab_room_html',
        'pdf':'report.views.lab_room.lab_room_pdf',
        'xls':'report.views.lab_room.lab_room_doc',
        'xlsx':'report.views.lab_room.lab_room_doc',
        'ods':'report.views.lab_room.lab_room_doc',
    },
    'report_objects': {
        'task':'report.tasks.task_report',
        'form':'report.forms.ReportObjectForm',
        'title':'List of objects',
        'html': 'report.views.objects.report_objects_html',
        'pdf': 'report.views.objects.report_objects_pdf',
        'xls': 'report.views.objects.report_objects_doc',
        'xlsx': 'report.views.objects.report_objects_doc',
        'ods': 'report.views.objects.report_objects_doc',
    },
    'report_limit_objects': {
        'task':'report.tasks.task_report',
        'form': 'report.forms.ValidateReportForm',
        'title': 'Limited shelf objects',
        'html': 'report.views.objects.report_limit_object_html',
        'pdf': 'report.views.objects.report_limit_object_pdf',
        'xls': 'report.views.objects.report_limit_object_doc',
        'xlsx': 'report.views.objects.report_limit_object_doc',
        'ods': 'report.views.objects.report_limit_object_doc',
    },
    'report_objectschanges': {
        'task':'report.tasks.task_report',
        'form': 'report.forms.ValidateObjectLogChangeReportForm',
        'title': 'Changes on Objects',
        'html':'report.views.objects.report_objectlogchange_html',
        'pdf': 'report.views.objects.report_objectlogchange_pdf',
        'xls': 'report.views.objects.report_objectlogchange_doc',
        'xlsx': 'report.views.objects.report_objectlogchange_doc',
        'ods': 'report.views.objects.report_objectlogchange_doc',
    },
    'report_furniture': {
        'task':'report.tasks.task_report',
        'form':'report.forms.ValidateLaboratoryRoomReportForm',
        'title':'Furniture report',
        'html':'report.views.furniture.furniture_html',
        'pdf':'report.views.furniture.furniture_pdf',
        'xls':'report.views.furniture.furniture_doc',
        'xlsx':'report.views.furniture.furniture_doc',
        'ods':'report.views.furniture.furniture_doc',
    },
    'report_organization_reactive_list': {
        'task':'report.tasks.task_report',
        'form': 'report.forms.OrganizationReactiveForm',
        'title': 'User exposition',
        'html':'report.views.objects.report_organization_reactive_list_html',
        'pdf': 'report.views.objects.report_organization_reactive_list_pdf',
        'xls': 'report.views.objects.report_organization_reactive_list_doc',
        'xlsx':'report.views.objects.report_organization_reactive_list_doc',
        'ods': 'report.views.objects.report_organization_reactive_list_doc',
    },
}