# Generated by Django 2.0.3 on 2018-03-11 01:51

from django.db import migrations

def create_default_templates(apps, schema_editor):

    Pictogram= apps.get_model('sga', 'Pictogram')
    
    for pic in ["5-2red.gif",
                "acide8.gif",
                "acide.gif",
                "acid_red.gif",
                "Aquatic-pollut-red.gif",
                "blan-red.gif",
                "bleu4.gif",
                "Bomba explotando.gif",
                "bottle.gif",
                "exclam.gif",
                "Gas inflamable sga.gif",
                "Gas inflamable transporte.gif",
                "jaune5-1.gif",
                "rondflam.gif",
                "rouge3.gif",
                "silhouete.gif",
                "skull6.gif",
                "skull.gif",
                "stripes.gif",
                "Trans.e1.1.gif",
                "Trans.e1.2.gif",
                "Trans.e1.3.gif",
                "Trans.e1.4.gif",
                "Trans.e1.5.gif",
                "Trans.e1.6.gif"]:
        Pictogram.objects.create(name=pic)

class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0001_initial'),
    ]

    operations = [
          migrations.RunPython(create_default_templates),
    ]
