# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_auto_20200325_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substance',
            options={'permissions': (('view_sustance', 'Can see available Sustance'),), 'verbose_name': 'Sustance', 'verbose_name_plural': 'Sustances'},
        ),
        migrations.AlterField(
            model_name='label',
            name='sustance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.Substance', verbose_name='Sustance'),
        ),
    ]
