# Generated by Django 2.2.12 on 2020-05-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_auto_20200325_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builderinformation',
            options={'verbose_name': 'Builder Information', 'verbose_name_plural': 'Information of Builders'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='dangerindication',
            options={'verbose_name': 'Danger Indication', 'verbose_name_plural': 'Indication of Danger'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterModelOptions(
            name='pictogram',
            options={'verbose_name': 'Pictogram', 'verbose_name_plural': 'Pictograms'},
        ),
        migrations.AlterModelOptions(
            name='prudenceadvice',
            options={'verbose_name': 'Prudence Advice', 'verbose_name_plural': 'Prudence Advices'},
        ),
        migrations.AlterModelOptions(
            name='recipientsize',
            options={'verbose_name': 'Recipient Size', 'verbose_name_plural': 'Size of recipients'},
        ),
        migrations.AlterModelOptions(
            name='substance',
            options={'verbose_name': 'Sustance', 'verbose_name_plural': 'Sustances'},
        ),
        migrations.AlterModelOptions(
            name='templatesga',
            options={'verbose_name': 'Template SGA', 'verbose_name_plural': 'Templates SGA'},
        ),
        migrations.AlterModelOptions(
            name='warningclass',
            options={'verbose_name': 'Warning Class', 'verbose_name_plural': 'Warning Classes'},
        ),
        migrations.AlterModelOptions(
            name='warningword',
            options={'verbose_name': 'Warning Word', 'verbose_name_plural': 'Warning Words'},
        ),
        migrations.AlterField(
            model_name='label',
            name='sustance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.Substance', verbose_name='Sustance'),
        ),
    ]
