# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_pictograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Warning Category',
                'verbose_name_plural': 'Warning Categories',
                'permissions': (('view_warningclass', 'Can see available Warning Categories'),),
            },
        ),
        migrations.RemoveField(
            model_name='sustance',
            name='cas_number',
        ),
        migrations.RemoveField(
            model_name='warningclass',
            name='category',
        ),
        migrations.AddField(
            model_name='component',
            name='cas_number',
            field=models.CharField(default='0000', max_length=150, verbose_name='CAS number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sustance',
            name='synonymous',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Synonymous'),
        ),
        migrations.AddField(
            model_name='warningclass',
            name='_type',
            field=models.SmallIntegerField(choices=[(0, 'Physic danger'), (1, 'Healty danger'), (2, 'Environment danger')], default=0, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='builderinformation',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='builderinformation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='builderinformation',
            name='phone',
            field=models.TextField(max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dangerindication',
            name='code',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='dangerindication',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dangerindication',
            name='pictograms',
            field=models.ManyToManyField(to='sga.Pictogram', verbose_name='Pictograms'),
        ),
        migrations.AlterField(
            model_name='dangerindication',
            name='warning_class',
            field=models.ManyToManyField(to='sga.WarningClass', verbose_name='Warning class'),
        ),
        migrations.AlterField(
            model_name='dangerindication',
            name='warning_words',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.WarningWord', verbose_name='Warning words'),
        ),
        migrations.AlterField(
            model_name='label',
            name='builderInformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.BuilderInformation', verbose_name='Builder Information'),
        ),
        migrations.AlterField(
            model_name='label',
            name='size',
            field=models.SmallIntegerField(choices=[(0, 'default')], verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='label',
            name='sustance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.Sustance', verbose_name='Sustance'),
        ),
        migrations.AlterField(
            model_name='pictogram',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sustance',
            name='comercial_name',
            field=models.CharField(max_length=250, verbose_name='Comercial name'),
        ),
        migrations.AlterField(
            model_name='sustance',
            name='components',
            field=models.ManyToManyField(to='sga.Component', verbose_name='Components'),
        ),
        migrations.AlterField(
            model_name='sustance',
            name='danger_indications',
            field=models.ManyToManyField(to='sga.DangerIndication', verbose_name='Danger indications'),
        ),
        migrations.AlterField(
            model_name='warningclass',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warningword',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warningword',
            name='weigth',
            field=models.SmallIntegerField(default=0, verbose_name='Weigth'),
        ),
        migrations.AddField(
            model_name='warningclass',
            name='categories',
            field=models.ManyToManyField(to='sga.WarningCategory', verbose_name='Categories'),
        ),
    ]
