# Generated by Django 2.2.12 on 2020-06-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_auto_20200603_1128'),
        ('sga', '0003_auto_20200525_1908'),
    ]

    operations = [
    ]
