# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_auto_20180822_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerindication',
            name='prudence_advice',
            field=models.TextField(default='Fill me', verbose_name='Prudence advice'),
        ),
    ]
