# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0004_dangerindication_prudence_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerindication',
            name='prudence_advice_help',
            field=models.TextField(blank=True, null=True, verbose_name='Help for prudence advice'),
        ),
        migrations.AlterField(
            model_name='dangerindication',
            name='prudence_advice',
            field=models.TextField(default='None', verbose_name='Prudence advice'),
        ),
    ]
