# Generated by Django 2.2.12 on 2020-06-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0004_merge_20200603_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substance',
            options={'verbose_name': 'Sustance', 'verbose_name_plural': 'Sustances'},
        ),
    ]
