# Generated by Django 2.2.13 on 2020-12-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0005_auto_20200605_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerPrudence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_indication', models.ManyToManyField(to='sga.DangerIndication', verbose_name='Danger indication')),
                ('prudence_advice', models.ManyToManyField(to='sga.PrudenceAdvice', verbose_name='Prudence advice')),
            ],
        ),
    ]
