# Generated by Django 2.2.13 on 2020-12-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0005_auto_20200605_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('amount', models.CharField(max_length=10, verbose_name='Amount')),
                ('details', models.TextField(max_length=255, verbose_name='Details')),
                ('is_donator', models.BooleanField(default=True, verbose_name='Add me to the donators list')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid?')),
                ('donation_date', models.DateTimeField(auto_now_add=True, verbose_name='Donation date')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
