# Generated by Django 2.2.13 on 2021-01-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0006_dangerprudence'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='uipa_name',
            field=models.CharField(default='', max_length=250, verbose_name='UIPA name'),
        ),
    ]
