# Generated by Django 2.2.13 on 2021-01-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0007_substance_uipa_name'),
        ('sga', '0006_donation'),
    ]

    operations = [
    ]
