# Generated by Django 2.2.13 on 2021-02-24 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0008_merge_20210126_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTemplateSGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('json_representation', models.TextField()),
                ('recipient_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.RecipientSize', verbose_name='Recipient Size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Template SGA',
                'verbose_name_plural': 'Personal Templates SGA',
            },
        ),
    ]
