# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 03:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0008_auto_20180822_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warningclass',
            name='categories',
        ),
        migrations.AddField(
            model_name='warningclass',
            name='danger_type',
            field=models.CharField(choices=[('typeofdanger', 'Type of danger'), ('class', 'Danger class'), ('category', 'Danger Category')], default='category', max_length=25),
        ),
        migrations.DeleteModel(
            name='WarningCategory',
        ),
    ]
