# Generated by Django 3.2 on 2022-08-29 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0009_personaltemplatesga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltemplatesga',
            name='recipient_size',
        ),
        migrations.AddField(
            model_name='personaltemplatesga',
            name='preview',
            field=models.TextField(help_text='B64 preview image'),
        ),
        migrations.AddField(
            model_name='personaltemplatesga',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sga.templatesga', verbose_name='Template SGA'),
        ),
        migrations.AddField(
            model_name='templatesga',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
