# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0009_auto_20180822_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('height', models.FloatField(default=10, verbose_name='Height')),
                ('height_unit', models.CharField(choices=[('mm', 'Milimeters'), ('cm', 'Centimeters'), ('inch', 'inch')], default='cm', max_length=5, verbose_name='Height Unit')),
                ('width', models.FloatField(default=10, verbose_name='Width')),
                ('width_unit', models.CharField(choices=[('mm', 'Milimeters'), ('cm', 'Centimeters'), ('inch', 'inch')], default='cm', max_length=5, verbose_name='Width Unit')),
            ],
            options={
                'verbose_name': 'Recipient Size',
                'permissions': (('view_recipientsize', 'Can see available Recipient Size'),),
                'verbose_name_plural': 'Size of recipients',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='commercial_information',
            field=models.TextField(blank=True, null=True, verbose_name='Commercial Information'),
        ),
        migrations.AlterField(
            model_name='label',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.RecipientSize', verbose_name='Recipient Size'),
        ),
    ]
