# Generated by Django 3.2 on 2022-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0010_auto_20220829_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltemplatesga',
            name='preview',
            field=models.TextField(help_text='B64 preview image'),
        ),
        migrations.AlterField(
            model_name='templatesga',
            name='preview',
            field=models.TextField(help_text='B64 preview image', null=True),
        ),
    ]
