# Generated by Django 3.2 on 2022-09-01 17:17

from django.db import migrations, models
import django.db.models.deletion

def delete_templates(apps, schema_editor):
    PersonalTemplateSGA = apps.get_model('sga', 'PersonalTemplateSGA')

    PersonalTemplateSGA.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0010_auto_20220829_1518'),
    ]

    operations = [
        migrations.RunPython(delete_templates),
        migrations.RemoveField(
            model_name='label',
            name='size',
        ),
        migrations.AddField(
            model_name='personaltemplatesga',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sga.label', verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='templatesga',
            name='preview',
            field=models.TextField(help_text='B64 preview image', null=True),
        ),
    ]
