# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0011_dangerindication_warning_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningclass',
            name='danger_type',
            field=models.CharField(choices=[('typeofdanger', 'Type of danger'), ('class', 'Danger class'), ('category', 'Danger Category')], default='category', max_length=25, verbose_name='Danger type'),
        ),
    ]
