# Generated by Django 3.2 on 2022-09-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0011_auto_20220901_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltemplatesga',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode/', verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='personaltemplatesga',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
