# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0012_auto_20180823_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerindication',
            name='prudence_advice_help',
        ),
        migrations.AddField(
            model_name='prudenceadvice',
            name='prudence_advice_help',
            field=models.TextField(blank=True, null=True, verbose_name='Help for prudence advice'),
        ),
    ]
