# Generated by Django 3.2 on 2022-09-05 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0012_auto_20220902_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltemplatesga',
            name='barcode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='personaltemplatesga',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='sga/logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='templatesga',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
