# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0013_auto_20180827_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustance',
            name='agrochemical',
            field=models.BooleanField(default=False),
        ),
    ]
