# Generated by Django 3.2 on 2022-09-05 19:26

from django.db import migrations


def create_default_template(apps, schema_editor):
    TemplateSGA = apps.get_model('sga', 'TemplateSGA')
    PersonalTemplateSGA = apps.get_model('sga', 'PersonalTemplateSGA')
    RecipientSize = apps.get_model('sga', 'RecipientSize')

    PersonalTemplateSGA.objects.all().delete()
    TemplateSGA.objects.all().delete()

    recipient = RecipientSize.objects.create(
        width=17,
        height=13
    )

    TemplateSGA.objects.create(
        name="Plantilla Base",
        community_share=True,
        recipient_size=recipient
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0013_auto_20220905_1323'),
    ]

    operations = [
        migrations.RunPython(create_default_template),
    ]
