# Generated by Django 3.2 on 2022-09-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0011_auto_20220901_0957'),
        ('sga', '0014_auto_20220905_1326'),
    ]

    operations = [
    ]
