# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0015_auto_20180914_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sustance',
            new_name='Substance',
        ),
    ]
