# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0016_auto_20181223_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('json_representation', models.TextField()),
                ('community_share', models.BooleanField(default=True, verbose_name='Share with community')),
                ('preview', models.TextField(help_text='B64 preview image')),
                ('recipient_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.RecipientSize', verbose_name='Recipient Size')),
            ],
        ),
    ]
