# Generated by Django 3.2 on 2022-09-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0016_auto_20220912_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerindication',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='dangerprudence',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='personaltemplatesga',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='pictogram',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='prudenceadvice',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='substance',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='templatesga',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
        migrations.AddField(
            model_name='warningword',
            name='organilab_context',
            field=models.CharField(default='laboratory', max_length=25),
        ),
    ]
