# Generated by Django 3.2 on 2022-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0017_auto_20220912_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
