# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0017_templatesga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatesga',
            options={'permissions': (('view_label', 'Can see available labels'),), 'verbose_name': 'Template SGA', 'verbose_name_plural': 'Templates SGA'},
        ),
        migrations.AlterField(
            model_name='warningclass',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='warningclass',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='warningclass',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
