# Generated by Django 3.2 on 2022-09-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0018_auto_20220913_1059'),
        ('sga', '0018_substance_description'),
    ]

    operations = [
    ]
