# Generated by Django 3.2 on 2022-09-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0016_alter_personaltemplatesga_preview'),
        ('sga', '0019_merge_20220913_1411'),
    ]

    operations = [
    ]
