# Generated by Django 3.2 on 2022-09-26 17:58

from django.db import migrations

def delete_organilab_sga_complements(apps, schema_editor):
    DangerPrudence = apps.get_model('sga', 'DangerPrudence')
    PrudenceAdvice = apps.get_model('sga', 'PrudenceAdvice')
    WarningWord = apps.get_model('sga', 'WarningWord')
    Pictogram = apps.get_model('sga', 'Pictogram')
    DangerIndication = apps.get_model('sga', 'DangerIndication')

    PrudenceAdvice.objects.all().update(organilab_context="")
    Pictogram.objects.all().update(organilab_context="")
    DangerPrudence.objects.all().update(organilab_context="")
    WarningWord.objects.all().update(organilab_context="")
    DangerIndication.objects.all().update(organilab_context="")


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0020_merge_20220913_2302'),
    ]

    operations = [
        migrations.RunPython(delete_organilab_sga_complements),
        migrations.RemoveField(
            model_name='prudenceadvice',
            name='organilab_context',
        ),
        migrations.RemoveField(
            model_name='warningword',
            name='organilab_context',
        ),
        migrations.RemoveField(
            model_name='pictogram',
            name='organilab_context',
        ),
        migrations.RemoveField(
            model_name='dangerindication',
            name='organilab_context',
        ),
        migrations.RemoveField(
            model_name='dangerprudence',
            name='organilab_context',
        ),
    ]
