# Generated by Django 3.2 on 2022-09-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0021_remove_organilab_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesga',
            name='organilab_context',
        ),
        migrations.AlterField(
            model_name='label',
            name='builderInformation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sga.builderinformation', verbose_name='Builder Information'),
        ),
    ]
