# Generated by Django 3.2 on 2022-09-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0022_auto_20220926_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceDangerPrudence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_indication', models.ManyToManyField(to='sga.DangerIndication', verbose_name='Danger indication')),
                ('prudence_advice', models.ManyToManyField(to='sga.PrudenceAdvice', verbose_name='Prudence advice')),
                ('substance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sga.substance')),
            ],
        ),
    ]
