# Generated by Django 3.2 on 2022-09-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0023_substancedangerprudence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubstanceDangerPrudence',
            new_name='SGAComplement',
        ),
    ]
