# Generated by Django 3.2 on 2022-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0025_auto_20221006_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancecharacteristics',
            name='concentration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Concentration'),
        ),
    ]
