# Generated by Django 3.2 on 2022-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0025_auto_20221006_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityleaf',
            name='other_security_information',
            field=models.TextField(blank=True, null=True, verbose_name='Other security information'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='contaminated_packaging',
            field=models.TextField(blank=True, null=True, verbose_name='Contaminated packaging'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='incompatible_materials',
            field=models.TextField(blank=True, null=True, verbose_name='Incompatible materials'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='inflammability_solid_gas',
            field=models.TextField(blank=True, null=True, verbose_name='Flammability (solid,gas)'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='medical_indication',
            field=models.TextField(blank=True, null=True, verbose_name='Indication of any medical attention and special treatment that should be provided immediately'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='proper_shipping_name',
            field=models.TextField(blank=True, null=True, verbose_name='United Nations proper shipping name'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='regulations_legislation',
            field=models.TextField(blank=True, null=True, verbose_name='Regulations and legislation on safety, health and the environment specific to the substance or mixture'),
        ),
        migrations.AlterField(
            model_name='substancecharacteristics',
            name='concentration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Concentration'),
        ),
    ]
