# Generated by Django 4.1.2 on 2022-10-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0026_alter_substancecharacteristics_concentration'),
        ('sga', '0026_auto_20221007_1218'),
    ]

    operations = [
    ]
