# Generated by Django 3.2 on 2022-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0026_auto_20221007_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone number'),
        ),
    ]
