# Generated by Django 4.1.2 on 2022-10-10 17:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields

def gen_position(apps, schema_editor):
    WarningClass = apps.get_model('sga', 'WarningClass')
    for obj in WarningClass.objects.all():
        obj.position = obj.tree_id * 100000 + obj.lft
        obj.save(update_fields=['position'])

class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0027_merge_20221010_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warningclass',
            options={'ordering': ['position'], 'verbose_name': 'Warning Class', 'verbose_name_plural': 'Warning Classes'},
        ),
        migrations.AddField(
            model_name='warningclass',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='components_sga',
            field=models.ManyToManyField(to='sga.substance', verbose_name='Components'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='synonymous',
            field=models.TextField(verbose_name='Synonymous'),
        ),
        migrations.AlterField(
            model_name='warningclass',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sga.warningclass'),
        ),
        migrations.RunPython(gen_position, reverse_code=migrations.RunPython.noop),
    ]
