# Generated by Django 3.2 on 2022-10-13 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0027_auto_20221010_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityleaf',
            name='directives_classification',
            field=models.TextField(blank=True, null=True, verbose_name='Classification according to EU Directives 67/548/CEE or 1999/45/CE'),
        ),
        migrations.AddField(
            model_name='securityleaf',
            name='identified_uses',
            field=models.TextField(blank=True, null=True, verbose_name='Identified uses'),
        ),
        migrations.AddField(
            model_name='securityleaf',
            name='reach_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REACH No.'),
        ),
        migrations.AddField(
            model_name='securityleaf',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='securityleaf',
            name='register_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Registro'),
        ),
        migrations.AddField(
            model_name='securityleaf',
            name='regulation_classification',
            field=models.TextField(blank=True, null=True, verbose_name='Classification according to Regulation (CE) 1272/2008'),
        ),
        migrations.AddField(
            model_name='securityleaf',
            name='regulatory_information',
            field=models.TextField(blank=True, null=True, verbose_name='Regulatory information'),
        ),
        migrations.AddField(
            model_name='sgacomplement',
            name='pictograms',
            field=models.ManyToManyField(to='sga.Pictogram', verbose_name='Pictogram'),
        ),
        migrations.AddField(
            model_name='sgacomplement',
            name='warningword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sga.warningword', verbose_name='WarningWord'),
        ),
        migrations.AddField(
            model_name='substance',
            name='brand',
            field=models.CharField(default='', max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sga.provider', verbose_name='Provider'),
        ),
    ]
