# Generated by Django 4.1.2 on 2022-10-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0028_alter_warningclass_options_warningclass_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warningclass',
            name='level',
        ),
        migrations.RemoveField(
            model_name='warningclass',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='warningclass',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='warningclass',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='warningclass',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sga.warningclass', verbose_name='parent'),
        ),
    ]
