# Generated by Django 4.1.2 on 2022-10-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0029_remove_warningclass_level_remove_warningclass_lft_and_more'),
        ('sga', '0031_securityleaf_vla_vm_pp'),
    ]

    operations = [
    ]
