# Generated by Django 4.0.8 on 2022-10-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0032_merge_20221017_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictograms/'),
        ),
        migrations.AlterField(
            model_name='securityleaf',
            name='font',
            field=models.TextField(blank=True, null=True, verbose_name='Font'),
        ),
    ]
