# Generated by Django 4.0.8 on 2022-10-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0033_pictogram_image_alter_securityleaf_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogram',
            name='warning_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sga.warningword'),
        ),
    ]
