# Generated by Django 4.0.8 on 2022-10-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0034_alter_pictogram_warning_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sga/pictograms/'),
        ),
    ]
