# Generated by Django 4.0.8 on 2022-10-18 16:21

from django.db import migrations, models

def delete_organilab_pictograms(apps, schema_editor):
    pictogram = apps.get_model('sga', 'Pictogram')
    sgaComplement = apps.get_model('sga', 'SGAComplement')
    dangerIndication = apps.get_model('sga', 'DangerIndication')

    for sga in sgaComplement.objects.all():
        sga.pictograms.clear()

    for danger in dangerIndication.objects.all():
        danger.pictograms.clear()

    pictogram.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0035_alter_pictogram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='id_pictogram',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(delete_organilab_pictograms),

    ]
