# Generated by Django 4.0.8 on 2022-10-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0033_alter_securityleaf_font'),
        ('sga', '0036_pictogram_id_pictogram'),
    ]

    operations = [
    ]
