# Generated by Django 4.0.8 on 2022-10-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0037_merge_20221025_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogram',
            name='warning_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sga.warningword', verbose_name='Warning Word'),
        ),
    ]
