# Generated by Django 4.0.8 on 2022-11-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0038_alter_pictogram_warning_word'),
        ('sga', '0039_alter_pictogram_warning_word'),
    ]

    operations = [
    ]
