# Generated by Django 4.0.8 on 2022-11-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0040_merge_20221101_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='providersga', to='sga.provider', verbose_name='Provider'),
        ),
    ]
