# Generated by Django 4.0.8 on 2022-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0042_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='builderinformation',
            name='community_share',
        ),
        migrations.RemoveField(
            model_name='label',
            name='commercial_information',
        ),
        migrations.AddField(
            model_name='builderinformation',
            name='commercial_information',
            field=models.TextField(blank=True, null=True, verbose_name='Commercial Information'),
        ),
        migrations.AddField(
            model_name='label',
            name='community_share',
            field=models.BooleanField(blank=True, default=False, verbose_name='Share with community'),
        ),
    ]
