# Generated by Django 4.0.8 on 2022-11-29 01:08

from django.db import migrations, models
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0062_remove_organizationusermanagement_group'),
        ('sga', '0043_delete_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='substancecharacteristics',
            name='bioaccumulable',
            field=models.BooleanField(null=True, verbose_name='Bioaccumulable'),
        ),
        migrations.AlterField(
            model_name='substancecharacteristics',
            name='white_organ',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_white_organ_sga', to='laboratory.catalog', verbose_name='White organ'),
        ),
    ]
