# Generated by Django 4.0.8 on 2022-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0044_alter_substance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='synonymous',
            field=models.TextField(blank=True, null=True, verbose_name='Synonymous'),
        ),
    ]
