# Generated by Django 4.0.8 on 2022-12-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0046_substance_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
