# Generated by Django 4.0.8 on 2022-12-22 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0066_alter_protocol_file'),
        ('sga', '0047_delete_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builderinformation',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='builderinformation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builderinformation',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='builderinformation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure'),
        ),
        migrations.RunSQL(
            "ALTER TABLE sga_substance ADD IF NOT EXISTS creator_id INTEGER;",
            state_operations=[
                migrations.AddField(
                    "substance",
                    "creator",
                    models.ForeignKey(null=True,
                                      on_delete=django.db.models.deletion.DO_NOTHING,
                                      to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
            ],
        ),
        migrations.RenameField(
            model_name='substance',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='substance',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substance',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure'),
        ),
    ]
