# Generated by Django 4.0.8 on 2023-01-26 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0048_builderinformation_created_by_and_more'),
    ]

    operations = [
    ]
