# Generated by Django 4.0.8 on 2023-06-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0050_pictogram_creation_date_pictogram_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltemplatesga',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sga.recipientsize', verbose_name='Template SGA'),
        ),
    ]
