# Generated by Django 4.1.7 on 2023-06-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sga", "0052_rename_recipient_personaltemplatesga_recipient_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaltemplatesga",
            name="recipient_size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sga.recipientsize",
                verbose_name="Recipient size",
            ),
        ),
    ]
