# Generated by Django 4.0.8 on 2023-06-09 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0052_rename_recipient_personaltemplatesga_recipient_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltemplatesga',
            name='organilab_context',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='organilab_context',
        ),
        migrations.AlterField(
            model_name='personaltemplatesga',
            name='recipient_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sga.recipientsize', verbose_name='Recipient size'),
        ),
    ]
