# Generated by Django 4.0.8 on 2023-06-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0053_remove_personaltemplatesga_organilab_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerindication',
            name='pictograms',
        ),
        migrations.RemoveField(
            model_name='sgacomplement',
            name='pictograms',
        ),
        migrations.DeleteModel(
            name='Pictogram',
        ),
    ]
