# Generated by Django 4.0.8 on 2023-06-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0054_remove_dangerindication_pictograms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substance',
            name='creator',
        ),
        migrations.AlterField(
            model_name='personaltemplatesga',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.label', verbose_name='Label'),
        ),
    ]
