# Generated by Django 4.0.8 on 2023-06-15 03:10

from django.db import migrations, models
import django.db.models.deletion
import logging
logger = logging.getLogger("django")

# def migrate_to_creator_model(apps, schema_editor):
#     Substance = apps.get_model('sga', 'Substance')
#
#     for data in Substance.objects.all().values('pk', 'creator'):
#         Substance.objects.filter(pk=data['pk']).update(created_by=data['creator'])
#         logger.info("Substance Creator %(pk)s = %(creator)s"%data)

class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0054_remove_dangerindication_pictograms_and_more'),
    ]

    operations = [
       # migrations.RunPython(migrate_to_creator_model),
        migrations.AlterField(
            model_name='personaltemplatesga',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.label', verbose_name='Label'),
        ),
    ]
