# Generated by Django 4.0.8 on 2023-06-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0055_remove_substance_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsubstance',
            name='substance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sga.substance', verbose_name='Substance'),
        ),
    ]
