# Generated by Django 4.0.8 on 2023-06-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0056_alter_reviewsubstance_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgacomplement',
            name='substance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sga.substance'),
        ),
    ]
