# Generated by Django 4.0.8 on 2023-06-15 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0114_alter_shelf_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0057_alter_sgacomplement_substance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.substance')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
            },
        ),
    ]
