# Generated by Django 4.0.8 on 2023-06-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0058_componentsga_substancesga_sustancecharacteristicssga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Under Review'), (2, 'Approved')], default=0),
        ),
    ]
