# Generated by Django 4.0.8 on 2023-07-06 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0122_create_base_unit_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0061_displaylabel_remove_templatesga_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displaylabel',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='templatesga',
            old_name='creator',
            new_name='created_by',
        ),

        migrations.AddField(
            model_name='displaylabel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displaylabel',
            name='label_in_png',
            field=models.TextField(help_text='B64 image using the recipient size', null=True),
        ),
        migrations.AddField(
            model_name='displaylabel',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='displaylabel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure'),
        ),

        migrations.AddField(
            model_name='templatesga',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatesga',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='templatesga',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure'),
        ),
    ]
