# Generated by Django 4.0.8 on 2023-07-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0063_builderinformation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substanceobservation',
            old_name='creator',
            new_name='created_by',
        ),
    ]
