# Generated by Django 4.1.11 on 2023-10-13 19:37

from django.db import migrations, models
import sga.models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0064_rename_creator_substanceobservation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaylabel',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=sga.models.upload_logo, verbose_name='Logo'),
        ),
    ]
