# Generated by Django 5.1 on 2025-03-24 22:49

from django.db import migrations

def add_key_show_sga(apps, schema_editor):
    Settings = apps.get_model("djgentelella", "GentelellaSettings")
    Settings.objects.get_or_create(
        key='show_sga',
        value='true'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0065_alter_displaylabel_logo_and_more"),
    ]

    operations = [
        migrations.RunPython(add_key_show_sga)

    ]
