# Generated by Django 4.1.10 on 2024-05-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0065_alter_displaylabel_logo_and_more'),
    ]

    operations = [
        migrations.RunSQL(
        """
       ALTER TABLE sga_substance ADD COLUMN IF NOT EXISTS  creator_id INTEGER;
       UPDATE sga_substance SET  created_by_id=creator_id WHERE created_by_id IS NULL and created_by_id IS NOT NULL;
       ALTER TABLE sga_substance DROP COLUMN IF EXISTS  creator_id;
        """
        ),
    ]
