# Generated by Django 5.1 on 2025-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0067_alter_builderinformation_id_alter_component_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damger_category', models.CharField(choices=[('physical', 'Physical'), ('health', 'Health'), ('environment', 'Environment')], max_length=30, verbose_name='Danger Category')),
                ('h_code', models.ManyToManyField(related_name='category_h_code', to='sga.dangerindication', verbose_name='H Code')),
            ],
        ),
    ]
