# Generated by Django 5.1 on 2025-04-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0068_hcodecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcodecategory',
            old_name='damger_category',
            new_name='danger_category',
        ),
    ]
