# Generated by Django 5.1 on 2025-04-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0069_rename_damger_category_hcodecategory_danger_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcodecategory',
            name='h_code',
            field=models.ManyToManyField(related_name='category_h_code', to='sga.dangerindication', verbose_name='H Codes'),
        ),
    ]
