# Generated by Django 5.1 on 2025-05-12 16:45

import laboratory.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0070_alter_hcodecategory_h_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pictogram', models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files)),
            ],
        ),
    ]
