# Generated by Django 5.1 on 2025-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0071_pictogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcodecategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hcodecategory',
            name='threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
