# Generated by Django 5.1 on 2025-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0072_hcodecategory_name_hcodecategory_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcodecategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hcodecategory',
            name='threshold',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Threshold'),
        ),
    ]
