# Generated by Django 5.2.8 on 2026-01-22 20:43

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0166_merge_20260114_1219'),
        ('sga', '0073_alter_hcodecategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcodecategory',
            name='measurement_unit',
            field=laboratory.catalog.GTForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurementunit_hcode_category', to='laboratory.catalog', verbose_name='Measurement unit'),
        ),
    ]
