# Generated by Django 5.2.11 on 2026-02-12 17:50

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0175_alter_shelfobject_flashpoint"),
        ("sga", "0074_hcodecategory_measurement_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DangerSubstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cas_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="CAS code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "synonym",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Synonym"
                    ),
                ),
                (
                    "physical_status",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Physical Status",
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Threshold"
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Measurement unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DangerSubstanceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=25, null=True)),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("threshold", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "h_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sga.dangerindication",
                    ),
                ),
                (
                    "process_condition",
                    laboratory.catalog.GTForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="process_condition",
                        to="laboratory.catalog",
                        verbose_name="Process Condition",
                    ),
                ),
            ],
        ),
    ]
