# Generated by Django 6.0.2 on 2026-02-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0075_dangersubstance_dangersubstancecategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangersubstance",
            name="measurement_unit",
            field=models.CharField(
                blank=True,
                default="Toneladas",
                max_length=25,
                null=True,
                verbose_name="Measurement unit",
            ),
        ),
    ]
