# Generated by Django 6.0.2 on 2026-02-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0076_alter_dangersubstance_measurement_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dangersubstance",
            name="measurement_unit",
        ),
        migrations.RemoveField(
            model_name="dangersubstance",
            name="physical_status",
        ),
        migrations.RemoveField(
            model_name="dangersubstance",
            name="synonym",
        ),
        migrations.AddField(
            model_name="dangersubstance",
            name="especial_condition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dangersubstance",
            name="h_codes_match",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dangersubstance",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="dangersubstance",
            name="patron_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dangersubstance",
            name="type_match",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dangersubstancecategory",
            name="measurement_unit",
            field=models.CharField(
                blank=True,
                default="Toneladas",
                max_length=25,
                null=True,
                verbose_name="Measurement unit",
            ),
        ),
    ]
