# Generated by Django 6.0.2 on 2026-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0077_remove_dangersubstance_measurement_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dangersubstance",
            name="h_codes_match",
        ),
        migrations.AddField(
            model_name="dangersubstance",
            name="h_codes_match",
            field=models.ManyToManyField(
                to="sga.dangerindication", verbose_name="H Codes"
            ),
        ),
    ]
