# Generated by Django 6.0.2 on 2026-02-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0078_remove_dangersubstance_h_codes_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangersubstancecategory",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("health", "Health"),
                    ("physical", "Physical"),
                    ("environmental", "Environmental"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
