# Generated by Django 6.0.2 on 2026-02-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0079_alter_dangersubstancecategory_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangersubstance",
            name="especial_condition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Especial Condition"
            ),
        ),
        migrations.AlterField(
            model_name="dangersubstance",
            name="patron_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Patron Name"
            ),
        ),
        migrations.AlterField(
            model_name="dangersubstance",
            name="type_match",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Type Match"
            ),
        ),
    ]
