# Generated by Django 5.2.11 on 2026-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0080_alter_dangersubstance_especial_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dangerindication",
            name="danger_type",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
    ]
