# Generated by Django 6.0.2 on 2026-02-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0080_alter_dangersubstance_especial_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangersubstancecategory",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("health", "Health"),
                    ("physical", "Physical"),
                    ("environmental", "Environmental"),
                ],
                max_length=25,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="dangersubstancecategory",
            name="h_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sga.dangerindication",
                verbose_name="H Code",
            ),
        ),
        migrations.AlterField(
            model_name="dangersubstancecategory",
            name="note",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Note"
            ),
        ),
        migrations.AlterField(
            model_name="dangersubstancecategory",
            name="section",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Section"
            ),
        ),
        migrations.AlterField(
            model_name="dangersubstancecategory",
            name="threshold",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Threshold"
            ),
        ),
    ]
