# Generated by Django 6.0.2 on 2026-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0081_alter_dangersubstancecategory_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangersubstance",
            name="type_match",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cas", "CAS"),
                    ("type_match", "Type Match"),
                    ("patron_name", "Patron Name"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type Match",
            ),
        ),
    ]
