# Generated by Django 5.2.11 on 2026-02-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0081_dangerindication_danger_type"),
        ("sga", "0082_alter_dangersubstance_type_match"),
    ]

    operations = []
