# Generated by Django 5.2.11 on 2026-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0084_alter_builderinformation_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substancecharacteristics",
            name="density",
            field=models.FloatField(
                default=0,
                help_text="t belongs to the regulations of decree 44741, only use dot like 0.344 on decimal",
                verbose_name="Density",
            ),
        ),
        migrations.AddField(
            model_name="substancecharacteristics",
            name="has_threshold",
            field=models.BooleanField(
                default=False,
                help_text="It belongs to the regulations of decree 44741",
                verbose_name="Has threshold?",
            ),
        ),
        migrations.AddField(
            model_name="substancecharacteristics",
            name="is_dangerous",
            field=models.BooleanField(
                default=False,
                help_text="It belongs to the regulations of decree 44741",
                verbose_name="Is Dangerous?",
            ),
        ),
        migrations.AddField(
            model_name="substancecharacteristics",
            name="is_pure",
            field=models.BooleanField(
                default=False,
                help_text="It belongs to the regulations of decree 44741",
                verbose_name="Is pure?",
            ),
        ),
        migrations.AddField(
            model_name="substancecharacteristics",
            name="threshold",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="It belongs to the regulations of decree 44741",
                null=True,
                verbose_name="Threshold",
            ),
        ),
    ]
