# Generated by Django 5.2.11 on 2026-07-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0208_objectlogchange_deleted_user_info_and_more"),
        ("sga", "0085_substancecharacteristics_density_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substance",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substances_lab",
                to="laboratory.laboratory",
                verbose_name="Laboratory",
            ),
        ),
    ]
