# Generated by Django 5.2.11 on 2026-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0208_objectlogchange_deleted_user_info_and_more"),
        ("sga", "0086_substance_laboratory"),
    ]

    operations = [
        migrations.AddField(
            model_name="substance",
            name="features",
            field=models.ManyToManyField(
                to="laboratory.objectfeatures", verbose_name="Object features"
            ),
        ),
    ]
