# Generated by Django 5.2.11 on 2026-07-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0208_objectlogchange_deleted_user_info_and_more"),
        ("sga", "0087_substance_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="substancecharacteristics",
            name="object_related",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substancharacteristics_object",
                to="laboratory.object",
            ),
        ),
    ]
