# Generated by Django 5.2.11 on 2026-07-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sga", "0088_substancecharacteristics_object_related"),
    ]

    operations = [
        migrations.AddField(
            model_name="substancecharacteristics",
            name="img_representation",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="sustances_images/",
                verbose_name="Image representation",
            ),
        ),
    ]
