# Generated by Django 5.2.11 on 2026-07-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0218_derive_laboratory_and_organization_codes"),
        ("sga", "0094_substancelaboratory_alter_substance_laboratories"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientsize",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="laboratory.laboratory",
                verbose_name="Laboratory",
            ),
        ),
    ]
