# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 23:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_shelf_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['name'], 'verbose_name': 'Piece of furniture', 'verbose_name_plural': 'Furniture'},
        ),
    ]
