# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 15:22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_auto_20161210_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='cas_id_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Cas ID Number'),
        ),
        migrations.AddField(
            model_name='object',
            name='is_precursor',
            field=models.NullBooleanField(verbose_name='Is precursor'),
        ),
        migrations.AddField(
            model_name='object',
            name='molecular_formular',
            field=models.CharField(max_length=255, null=True, verbose_name='Molecular formula'),
        ),
        migrations.AddField(
            model_name='object',
            name='security_sheet',
            field=models.FileField(null=True, upload_to='security_sheets/', verbose_name='Security sheet'),
        ),
    ]
