# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 15:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_auto_20161212_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='molecular_formular',
            new_name='molecular_formula',
        ),
    ]
