# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 15:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_merge_20161117_2025'),
        ('laboratory', '0012_shelfobject_limit_quantity'),
    ]

    operations = [
    ]
