# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_merge_20161214_0942'),
        ('laboratory', '0015_laboratory_related_labs'),
    ]

    operations = [
    ]
