# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0016_merge_20161222_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='is_precursor',
            field=models.BooleanField(default=False, verbose_name='Is precursor'),
        ),
    ]
