# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 17:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0019_feedbackentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='feedbackentry',
            name='related_file',
            field=models.FileField(blank=True, upload_to='media/feedback_entries/', verbose_name='Related file'),
        ),
        migrations.AlterField(
            model_name='objectfeatures',
            name='name',
            field=models.CharField(choices=[('0', 'General use'), ('1', 'Security equipment'), ('2', 'Analytic Chemistry'), ('3', 'Organic Chemistry'), ('4', 'Physical Chemistry'), ('5', 'Chemical and Biological process'), ('6', 'Industrial Biotechnology'), ('7', 'Biochemistry'), ('8', 'Water Chemistry'), ('9', 'Other')], max_length=2, unique=True, verbose_name='Name'),
        ),
    ]
