# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0042_auto_20200302_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Share with others'),
        ),
        migrations.AddField(
            model_name='object',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.Laboratory'),
        ),
    ]
