# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0043_auto_20200303_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='laboratory',
        ),
        migrations.AddField(
            model_name='object',
            name='laboratory',
            field=models.ManyToManyField(blank=True, to='laboratory.Laboratory'),
        ),
    ]
