# Generated by Django 4.0.8 on 2023-04-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0101_merge_20230413_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=512)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.taskreport')),
            ],
        ),
    ]
