# Generated by Django 4.0.8 on 2023-07-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_objectchangelogreport_documentreportstatus_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentreportstatus',
            name='file',
        ),
    ]
