# Generated by Django 4.0.8 on 2023-07-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_documentreportstatus_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectchangelogreport',
            name='diff_value',
            field=models.FloatField(default=0.0),
        ),
    ]
