# Generated by Django 4.0.8 on 2023-07-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_objectchangelogreport_diff_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskreport',
            old_name='creator',
            new_name='created_by',
        ),
    ]
