# Generated by Django 4.1.11 on 2023-10-17 17:18

from django.db import migrations, models
import laboratory.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_creator_taskreport_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files),
        ),
    ]
