# Generated by Django 4.1.11 on 2023-10-13 19:37

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_creator_taskreport_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=report.models.upload_report),
        ),
    ]
