# Generated by Django 5.2.8 on 2026-02-03 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0167_sustancecharacteristics_density"),
        ("report", "0006_alter_taskreport_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegencyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "physical_total",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("break_physical_total", models.BooleanField(default=False)),
                (
                    "enviroment_total",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("break_enviroment_total", models.BooleanField(default=False)),
                ("health_total", models.FloatField(blank=True, default=0.0, null=True)),
                ("break_health_total", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.organizationstructure",
                    ),
                ),
                (
                    "task_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.taskreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegencyReportBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("danger_category", models.CharField(max_length=50)),
                ("danger_list", models.PositiveIntegerField(default=3)),
                ("total", models.FloatField(default=0.0)),
                ("break_threshold", models.BooleanField(default=False)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.regencyreport",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="laboratory.object",
                    ),
                ),
            ],
        ),
    ]
