# Generated by Django 5.2.11 on 2026-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_objectchangelogreportbuilder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
