# Generated by Django 5.2.11 on 2026-09-08 02:01

import organilab.model_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_taskreport_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='language',
            field=models.CharField(default=organilab.model_defaults.get_default_language, max_length=10),
        ),
    ]
