[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket


[program:organilab_wsgi]
directory=/organilab
command = gunicorn -c /organilab/deploy/gunicorn_config_wsgi.py ; Command to start app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8

[program:organilab_asgi]
directory=/organilab
command = gunicorn -c /organilab/deploy/gunicorn_config_asgi.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx-app]
command = /usr/sbin/nginx
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery_worker]
directory=/organilab
command=celery -A organilab worker -l info -c %(ENV_CELERY_CONCURRENCY)s
user=organilab
autostart=false
autorestart=true
stopwaitsecs=600
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CELERY_CONCURRENCY="2"

[program:celery_beat]
directory=/organilab
command=celery -A organilab beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=INFO --pidfile=/tmp/celerybeat.pid
user=organilab
autostart=false
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
