# Generated by Django 5.2.11 on 2026-09-16 23:07

import django.db.models.deletion
import laboratory.catalog
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0223_normalize_dataconfig'),
        ('risk_management', '0037_alter_buildings_geolocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(help_text='Meter or service number, as it appears on the bill', max_length=100, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('meters_count', models.PositiveSmallIntegerField(default=1, verbose_name='Number of meters')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_points', to='risk_management.buildings', verbose_name='Building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laboratories', models.ManyToManyField(blank=True, related_name='measurement_points', to='laboratory.laboratory', verbose_name='Laboratories')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
                ('point_type', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambiental_point_types', to='laboratory.catalog', verbose_name='Point type')),
                ('resource_type', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambiental_point_resources', to='laboratory.catalog', verbose_name='Resource type')),
            ],
            options={
                'verbose_name': 'Measurement point',
                'verbose_name_plural': 'Measurement points',
                'ordering': ['pk'],
                'unique_together': {('organization', 'code', 'resource_type')},
            },
        ),
    ]
