# Generated by Django 5.2.11 on 2026-09-16 23:23

import django.db.models.deletion
import laboratory.catalog
import laboratory.models_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0002_seed_catalogs'),
        ('laboratory', '0223_normalize_dataconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period end')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Unit cost')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total cost')),
                ('is_waste', models.BooleanField(default=False, verbose_name='Is waste')),
                ('document', models.FileField(blank=True, help_text='Bill, receipt or waste manifest', null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Supporting document')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=20, verbose_name='Source')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ambiental.measurementpoint', verbose_name='Measurement point')),
                ('treatment', laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambiental_record_treatments', to='laboratory.catalog', verbose_name='Waste treatment')),
                ('unit', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambiental_record_units', to='laboratory.catalog', verbose_name='Unit')),
                ('waste_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambiental_records', to='laboratory.provider', verbose_name='Authorized waste manager')),
            ],
            options={
                'verbose_name': 'Consumption record',
                'verbose_name_plural': 'Consumption records',
                'ordering': ['-period_end', 'pk'],
                'indexes': [models.Index(fields=['organization', 'period_start'], name='ambiental_c_organiz_d5493a_idx'), models.Index(fields=['point', 'period_start'], name='ambiental_c_point_i_60e188_idx')],
                'unique_together': {('point', 'period_start', 'period_end')},
            },
        ),
    ]
