# Generated by Django 5.2.11 on 2026-09-16 23:35

import django.db.models.deletion
import laboratory.catalog
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0003_consumptionrecord'),
        ('laboratory', '0223_normalize_dataconfig'),
        ('risk_management', '0037_alter_buildings_geolocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizationBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Value')),
                ('is_manual', models.BooleanField(default=True, help_text='Preloading never overwrites a value entered manually', verbose_name='Entered manually')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_bases', to='risk_management.buildings', verbose_name='Building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('normalizer', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambiental_normalization_bases', to='laboratory.catalog', verbose_name='Normalizer')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
            ],
            options={
                'verbose_name': 'Normalization base',
                'verbose_name_plural': 'Normalization bases',
                'ordering': ['-year', 'pk'],
                'permissions': [('preload_normalizationbase', 'Can preload normalization bases')],
                'unique_together': {('organization', 'normalizer', 'building', 'year')},
            },
        ),
    ]
