# Generated by Django 5.2.11 on 2026-09-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0004_normalizationbase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionrecord',
            options={'ordering': ['-period_end', 'pk'], 'permissions': [('view_ambiental_dashboard', 'Can view the environmental dashboard')], 'verbose_name': 'Consumption record', 'verbose_name_plural': 'Consumption records'},
        ),
    ]
