# Generated by Django 5.2.11 on 2026-09-17 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0005_alter_consumptionrecord_options'),
        ('laboratory', '0223_normalize_dataconfig'),
        ('presentation', '0014_seed_alert_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(verbose_name='Period')),
                ('reference_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Reference value')),
                ('registered_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Registered value')),
                ('variation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Variation (%)')),
                ('level', models.CharField(max_length=20, verbose_name='Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('reviewed_note', models.TextField(blank=True, default='', verbose_name='Review note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ambiental.measurementpoint', verbose_name='Measurement point')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ambiental.consumptionrecord', verbose_name='Consumption record')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_consumption_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_alerts', to='presentation.alertrule', verbose_name='Alert rule')),
            ],
            options={
                'verbose_name': 'Consumption alert',
                'verbose_name_plural': 'Consumption alerts',
                'ordering': ['reviewed', '-period', 'pk'],
                'permissions': [('review_consumptionalert', 'Can review consumption alerts')],
                'unique_together': {('rule', 'point', 'period')},
            },
        ),
    ]
