# Generated by Django 5.2.11 on 2026-09-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0007_consumption_alert_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementpoint',
            options={'ordering': ['pk'], 'permissions': [('manage_building_access', 'Can manage access to buildings')], 'verbose_name': 'Measurement point', 'verbose_name_plural': 'Measurement points'},
        ),
    ]
