# Generated by Django 4.1.13 on 2024-09-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_and_perms', '0016_addpermissiontoadmingroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In process'), (3, 'Finished')], default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('rols', models.ManyToManyField(related_name='pending_tasks', to='auth_and_perms.rol')),
                ('validate_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth_and_perms.profile')),
            ],
        ),
    ]
