# Generated by Django 5.2.11 on 2026-02-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0024_alter_profile_id_card"),
        ("pending_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pendingtask",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "Pending task",
                "verbose_name_plural": "Pending tasks",
            },
        ),
        migrations.AlterField(
            model_name="pendingtask",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="pendingtask",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="pendingtask",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth_and_perms.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterField(
            model_name="pendingtask",
            name="rols",
            field=models.ManyToManyField(
                blank=True, to="auth_and_perms.rol", verbose_name="Roles"
            ),
        ),
        migrations.AlterField(
            model_name="pendingtask",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "In process"), (2, "Finished")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
