# Generated by Django 4.1.13 on 2024-09-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0016_addpermissiontoadmingroup'),
        ('pending_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='validate_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth_and_perms.profile'),
        ),
    ]
