# Generated by Django 4.1.13 on 2024-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_tasks', '0002_alter_pendingtask_validate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In process'), (2, 'Finished')], default=0),
        ),
    ]
