# Generated by Django 5.2.11 on 2026-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pending_tasks", "0002_alter_pendingtask_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingtask",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is archived"),
        ),
        migrations.AddField(
            model_name="pendingtask",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pendingtask",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
            preserve_default=False,
        ),
    ]
