# Generated by Django 5.2.11 on 2026-03-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pending_tasks", "0003_pendingtask_is_archived_pendingtask_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingtask",
            name="organization",
        ),
    ]
