# Generated by Django 5.2.11 on 2026-04-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pending_tasks", "0004_remove_pendingtask_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTaskManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pending_tasks.pendingtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending task manager",
                "verbose_name_plural": "Pending task managers",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="pending_tas_content_ea5769_idx",
                    )
                ],
            },
        ),
    ]
