import json
from django.utils.translation import ugettext as _

TOUR_STEPS = [
    {
        'element': "#brand_id",
        'title': _("Hello!"),
        'content': _("Welcome to Organilab, the simple laboratory organizer. Let's take a look of the main features of this system"),
        'placement': 'bottom'
    },
    {
        'element': '#index_labview_id',
        'title': _('Laboratory'),
        'content': _("The laboratory view is Organilab's main feature because it offers a general view of the structure of the laboratory for its management"),
        'placement': "bottom"
    },
    {
        'element': '#index_manage_id',
        'title': _('Management'),
        'content': _("In the management views you can find everything you need to control the components of the laboratory, from rooms to objects."),
        'placement': "bottom"
    },
    {
        'element': '#index_report_id',
        'title': _('Reports'),
        'content': _("If you need a full inventory of the whole laboratory or an specific component, this is the place to do it"),
        'placement': "bottom"
    },
    {
        'element': '#select_id',
        'title': _('Select laboratory'),
        'content': _('You can have access to multiple laboratories, select the one you want to manage by clicking this link'),
        'placement': 'bottom'
    },
    {
        'element': '#labview_id',
        'title': _('Laboratory view'),
        'content': _('In this view you can manage most of the components related to the lab, including its rooms, furniture and objects'),
        'placement': 'bottom'
    },
    {
        'element': '#management_id',
        'title': _('Management views'),
        'content': _('This views manage the different objects handled by the Organilab system for the current laboratory'),
        'placement': 'bottom'
    },
    {
        'element': '#reports_id',
        'title': _('Reports'),
        'content': _('Here you can see and retrieve the reports generated by the different components handled and saved in the Organilab system'),
        'placement': 'bottom'
    },
    {
        'element': '#reservation_list_id',
        'title': _('My reservations'),
        'content': _('In this view you can check out all the reservations related to you and their current status.'),
        'placement': 'bottom'
    },
    {
        'element': '#reservation_admin_id',
        'title': _('Reservation administration'),
        'content': _('Here you create and finish a given reservation registered in the Organilab system'),
        'placement': 'bottom'
    },
    {
        'element': '#feedback_id',
        'title': _('Help us!'),
        'content': _("If you have an issue testing or using Organilab, let us know. We'll be eager to help you"),
        'placement': 'bottom'
    }
]

TOUR_STEPS_JSON = json.dumps(TOUR_STEPS)
