# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-25 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_squashed_0046_auto_20200320_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobject',
            name='limit_quantity',
            field=models.FloatField(verbose_name='Limit material quantity'),
        ),
    ]
