# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_furniture_dataconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='feature',
            new_name='features',
        ),
    ]
