# Generated by Django 2.2.12 on 2020-05-26 01:16

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog
import laboratory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_auto_20200525_1908'),
        ('laboratory', '0002_auto_20200325_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clinventory',
            options={'verbose_name': 'C&L Inventory', 'verbose_name_plural': 'C&L Inventory objects'},
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['name'], 'verbose_name': 'Piece of furniture', 'verbose_name_plural': 'Furniture'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'permissions': (('view_report', 'Can see available reports'), ('do_report', 'Can download available reports')), 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryroom',
            options={'verbose_name': 'Laboratory Room', 'verbose_name_plural': 'Laboratory Rooms'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='objectfeatures',
            options={'verbose_name': 'Object feature', 'verbose_name_plural': 'Object features'},
        ),
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='principaltechnician',
            options={'ordering': ['name'], 'verbose_name': 'Principal Technician', 'verbose_name_plural': 'Principal Technicians'},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name': 'Shelf', 'verbose_name_plural': 'Shelves'},
        ),
        migrations.AlterModelOptions(
            name='shelfobject',
            options={'verbose_name': 'Shelf object', 'verbose_name_plural': 'Shelf objects'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.RemoveField(
            model_name='object',
            name='cas_id_number',
        ),
        migrations.RemoveField(
            model_name='object',
            name='h_code',
        ),
        migrations.RemoveField(
            model_name='object',
            name='imdg_code',
        ),
        migrations.RemoveField(
            model_name='object',
            name='is_precursor',
        ),
        migrations.RemoveField(
            model_name='object',
            name='molecular_formula',
        ),
        migrations.RemoveField(
            model_name='object',
            name='security_sheet',
        ),
        migrations.AddField(
            model_name='object',
            name='synonym',
            field=models.CharField(blank=True, help_text='Comma separed name', max_length=255, null=True, verbose_name='Synonym'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='type',
            field=laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Catalog', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='type',
            field=laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Catalog', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='measurement_unit',
            field=laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurementunit', to='laboratory.Catalog', verbose_name='Measurement unit'),
        ),
        migrations.CreateModel(
            name='SustanceCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioaccumulable', models.NullBooleanField(default=False)),
                ('molecular_formula', models.CharField(blank=True, max_length=255, null=True, validators=[laboratory.validators.validate_molecular_formula], verbose_name='Molecular formula')),
                ('cas_id_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cas ID Number')),
                ('security_sheet', models.FileField(blank=True, null=True, upload_to='security_sheets/', verbose_name='Security sheet')),
                ('is_precursor', models.BooleanField(default=False, verbose_name='Is precursor')),
                ('h_code', models.ManyToManyField(blank=True, to='sga.DangerIndication', verbose_name='Danger Indication')),
                ('iarc', laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gt_iarcrel', to='laboratory.Catalog')),
                ('imdg', laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gt_imdg', to='laboratory.Catalog')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Object')),
                ('white_organ', laboratory.catalog.GTManyToManyField(related_name='gt_white_organ', to='laboratory.Catalog')),
            ],
            options={
                'verbose_name': 'Sustance characteristic',
                'verbose_name_plural': 'Sustance characteristics',
            },
        ),
    ]
