# Generated by Django 2.2.12 on 2020-05-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_catalog_object'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='clinventory',
            options={'verbose_name': 'C&L Inventory', 'verbose_name_plural': 'C&L Inventory objects'},
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['name'], 'verbose_name': 'Piece of furniture', 'verbose_name_plural': 'Furniture'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'permissions': (('view_report', 'Can see available reports'), ('do_report', 'Can download available reports')), 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryroom',
            options={'verbose_name': 'Laboratory Room', 'verbose_name_plural': 'Laboratory Rooms'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='objectfeatures',
            options={'verbose_name': 'Object feature', 'verbose_name_plural': 'Object features'},
        ),
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='principaltechnician',
            options={'ordering': ['name'], 'verbose_name': 'Principal Technician', 'verbose_name_plural': 'Principal Technicians'},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name': 'Shelf', 'verbose_name_plural': 'Shelves'},
        ),
        migrations.AlterModelOptions(
            name='shelfobject',
            options={'verbose_name': 'Shelf object', 'verbose_name_plural': 'Shelf objects'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),






    ]
