# Generated by Django 2.2.12 on 2020-05-31 18:37

from django.db import migrations
import django.db.models.deletion
import laboratory.catalog
def add_precursor_type(apps, schema_editor):
    Catalog = apps.get_model('laboratory', 'Catalog')
    Catalog.objects.create(key='Precursor', description='Lista 1')
    Catalog.objects.create(key='Precursor', description='Lista 2')
    Catalog.objects.create(key='Precursor', description='Lista 3')

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_auto_20200525_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustancecharacteristics',
            name='precursor_type',
            field=laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gt_precursor', to='laboratory.Catalog'),
        ),
        migrations.RunPython(add_precursor_type),
    ]
