# Generated by Django 2.2.12 on 2020-06-16 03:19

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields

from laboratory.utils import get_user_laboratories, filter_laboratorist_profile


def make_restructuration(apps, schema_editor):
    PrincipalTechnician =   apps.get_model('laboratory', 'PrincipalTechnician')
    Profile = apps.get_model('laboratory', 'Profile')

    for pt in PrincipalTechnician.objects.all():
        user = pt.credentials.all().first()
        verify_user = Profile.objects.filter(user=user).first()

        if user:
            if verify_user is None:
                profile= Profile.objects.create(
                    phone_number=pt.phone_number,
                    id_card=pt.id_card,
                    user=user,
                )
            else:
                profile = verify_user

            if pt.assigned:
                profile.laboratories.add(pt.assigned)


    OrganizationUserManagement =   apps.get_model('laboratory', 'OrganizationUserManagement')
    OrganizationStructure =   apps.get_model('laboratory', 'OrganizationStructure')

    for oos in OrganizationStructure.objects.all():
        oum = OrganizationUserManagement.objects.create(
            group=oos.group,
            organization=oos,
        )

        for ptn in PrincipalTechnician.objects.filter(organization=oos):
            for user in ptn.credentials.all():
                oum.users.add(user)


    for profile in Profile.objects.all():
        orga = OrganizationUserManagement.objects.filter(users__in=[profile.user]).first()

        if orga:
            if orga.organization:
                profile.laboratories.add(*orga.organization.laboratory_set.all())


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0006_sustancecharacteristics_precursor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUserManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group')),
            ],
        ),
        migrations.AddField(
            model_name='organizationusermanagement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='laboratory.OrganizationStructure', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organizationusermanagement',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=25, verbose_name='Phone')),
                ('id_card', models.CharField(max_length=100, verbose_name='ID Card')),
                ('laboratories', models.ManyToManyField(blank=True, to='laboratory.Laboratory', verbose_name='Laboratories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(make_restructuration),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='group',
        ),
        migrations.DeleteModel(
            name='PrincipalTechnician',
        ),

    ]
