# Generated by Django 2.2.12 on 2020-06-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_auto_20200616_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.CharField(choices=[('0', 'Reactive'), ('1', 'Material'), ('2', 'Equipment')], default='0', max_length=2, verbose_name='Type'),
        ),
    ]
