# Generated by Django 2.2.13 on 2020-08-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_auto_20200622_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'permissions': (('add_organizationusermanagement', 'Can add organization user management'), ('change_organizationusermanagement', 'Can change organization user management'), ('delete_organizationusermanagement', 'Can delete organization user management'), ('view_organizationusermanagement', 'Can view organization user management')), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
