# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import laboratory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_auto_20161212_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='cas_id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cas ID Number'),
        ),
        migrations.AlterField(
            model_name='object',
            name='molecular_formula',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[laboratory.validators.validate_molecular_formula], verbose_name='Molecular formula'),
        ),
        migrations.AlterField(
            model_name='object',
            name='security_sheet',
            field=models.FileField(blank=True, null=True, upload_to='security_sheets/', verbose_name='Security sheet'),
        ),
    ]
