# Generated by Django 2.2.13 on 2020-08-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_auto_20200806_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='molecular_formula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Molecular formula'),
        ),
    ]
