# Generated by Django 2.2.13 on 2020-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_auto_20200813_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobject',
            name='limit_quantity',
            field=models.FloatField(help_text='Use dot like 0.344 on decimal', verbose_name='Limit material quantity'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='quantity',
            field=models.FloatField(help_text='Use dot like 0.344 on decimal', verbose_name='Material quantity'),
        ),
    ]
