# Generated by Django 2.2.13 on 2020-09-20 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0012_auto_20200825_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLogChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.FloatField(default=0)),
                ('new_value', models.FloatField(default=0)),
                ('diff_value', models.FloatField(default=0)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('precursor', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Laboratory')),
                ('measurement_unit', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logmeasurementunit', to='laboratory.Catalog', verbose_name='Measurement unit')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
