# Generated by Django 2.2.13 on 2020-10-01 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_objectlogchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustancecharacteristics',
            name='nfpa',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_nfpa', to='laboratory.Catalog'),
        ),
        migrations.AddField(
            model_name='sustancecharacteristics',
            name='storage_class',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_storage_class', to='laboratory.Catalog'),
        ),
        migrations.AddField(
            model_name='sustancecharacteristics',
            name='ue_code',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_ue', to='laboratory.Catalog'),
        ),
        migrations.AlterField(
            model_name='objectlogchange',
            name='object',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Object'),
        ),
        migrations.AlterField(
            model_name='objectlogchange',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='white_organ',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_white_organ', to='laboratory.Catalog'),
        ),
    ]
