# Generated by Django 2.2.13 on 2020-10-01 21:19

from django.db import migrations


def load_sustancecharacteristic(apps, schema_editor):
    Catalog = apps.get_model('laboratory', 'Catalog')
    list_catalog = [
        ('ue_code', 'EUH 001 Explosivo en estado seco.'),
        ('ue_code', 'EUH 006 Explosivo con o sin contacto con el aire.'),
        ('ue_code', 'EUH 014 Reacciona violentamente con el agua.'),
        ('ue_code', 'EUH 018 Al usarlo pueden formarse mezclas aire-vapor explosivas o inflamables.'),
        ('ue_code', 'EUH 019 Puede formar peróxidos explosivos.'),
        ('ue_code', 'EUH 044 Riesgo de explosión al calentarlo en ambiente confinado.'),
        ('ue_code', 'EUH 029 En contacto con el agua libera gases tóxicos.'),
        ('ue_code', 'EUH 031 En contacto con ácidos libera gases tóxicos.'),
        ('ue_code', 'EUH 032 En contacto con ácidos libera gas muy tóxico.'),
        ('ue_code', 'EUH 066 La exposición repetida puede provocar sequedad o formación de grietas en la piel.'),
        ('ue_code', 'EUH 070 Tóxico en contacto con los ojos.'),
        ('ue_code', 'EUH 071 Corrosivo para las vías respiratorias.'),
        ('ue_code', 'EUH 059 Peligroso para la capa de ozono.'),
        ('ue_code', 'EUH 201 Contiene plomo. No utilizar en objetos que los niños puedan masticar o chupar.'),
        ('ue_code', 'EUH 201A ¡Atención! Contiene plomo.'),
        ('ue_code', 'EUH 202 Cianoacrilato. Peligro. Se adhiere a la piel y a los ojos en segundos. Mantener fuera del alcance de los niños.'),
        ('ue_code', 'EUH 203 Contiene cromo (VI). Puede producir una reacción alérgica.'),
        ('ue_code', 'EUH 204 Contiene isocianatos. Puede producir una reacción alérgica.'),
        ('ue_code', 'EUH 205 Contiene constituyentes epoxídicos. Puede producir una reacción alérgica.'),
        ('ue_code', 'EUH 206 ¡Atención! No utilizar junto con otros productos. Puede desprender gases peligrosos (cloro).'),
        ('ue_code', 'EUH 207 ¡Atención! Contiene cadmio. Durante su utilización se desprenden vapores peligrosos. Ver la información facilitada por el fabricante. Seguir las instrucciones de seguridad.'),
        ('ue_code', 'EUH 208 Contiene <nombre de la sustancia sensibilizante>. Puede producir una reacción alérgica.'),
        ('ue_code', 'EUH 209 Puede inflamarse fácilmente al usarlo.'),
        ('ue_code', 'EUH 209A Puede inflamarse al usarlo.'),
        ('ue_code', 'EUH 210 Puede solicitarse la ficha de datos de seguridad.'),
        ('ue_code', 'EUH 401 A fin de evitar riesgos para las personas y el medio ambiente, siga las instrucciones de uso.'),
        ('nfpa', 'Líquido inflamable clase IA'),
        ('nfpa', 'Líquido inflamable clase IB'),
        ('nfpa', 'Líquido inflamable clase IC'),
        ('nfpa', 'Líquido inflamable clase II'),
        ('nfpa', 'Líquido inflamable clase IIIA'),
        ('nfpa', 'Líquido inflamable clase IIIB'),
        ('nfpa', 'Oxidante clase 1'),
        ('nfpa', 'Oxidante clase 2'),
        ('nfpa', 'Oxidante clase 3'),
        ('nfpa', 'Oxidante clase 4'),
        ('nfpa', 'Peróxido orgánico clase I'),
        ('nfpa', 'Peróxido orgánico clase IIA'),
        ('nfpa', 'Peróxido orgánico clase IIB'),
        ('nfpa', 'Peróxido orgánico clase III'),
        ('nfpa', 'Peróxido orgánico clase IV'),
        ('nfpa', 'Peróxido orgánico clase V'),
        ('nfpa', 'Material inestable (reactivo) clase 1'),
        ('nfpa', 'Material inestable (reactivo) clase 2'),
        ('nfpa', 'Material inestable (reactivo) clase 3'),
        ('nfpa', 'Material inestable (reactivo) clase 4'),
        ('nfpa', 'Material reactivo con el agua'),
        ('storage_class', '1 Sustancias explosivas (2ª Acta alemana sobre explosivos: grupos de almacenamiento 1.1 - 1.4)'),
        ('storage_class', '2 A Gases comprimidos, licuados o disueltos a presión'),
        ('storage_class', '2 B Gases envasados a presión (aerosoles)'),
        ('storage_class', '3 A Líquidos inflamables (punto de inflamación por debajo de los 55 °C)'),
        ('storage_class', '3 B Líquidos combustibles (Ordenanza sobre líquidos inflamables, clase de peligro A III)'),
        ('storage_class', '4.1 A Sólidos inflamables (2ª Acta alemana sobre explosivos: grupos de almacenamiento I-III)'),
        ('storage_class', '4.1 B Sólidos inflamables (Método A 10 de la CE)'),
        ('storage_class', '4.2 Sustancias inflamables de combustión espontánea'),
        ('storage_class', '4.3 Sustancias que en contacto con el agua desprenden gases inflamables'),
        ('storage_class', '5.1 A Agentes oxidantes (TRGS 515 grupo 1)'),
        ('storage_class', '5.1 B Agentes oxidantes (TRGS 515 grupos 2+3)'),
        ('storage_class', '5.1 C Agentes oxidantes (TRGS 511 grupos A-C)'),
        ('storage_class', '5.2 Peróxidos orgánicos'),
        ('storage_class', '6.1 A Compuestos tóxicos inflamables'),
        ('storage_class', '6.1 B Compuestos tóxicos no inflamables'),
        ('storage_class', '6.2 Sustancias infecciosas'),
        ('storage_class', '7 Material radiactivo'),
        ('storage_class', '8 A Compuestos corrosivos inflamables'),
        ('storage_class', '8 B Compuestos corrosivos no inflamables'),
        ('storage_class', '10 Líquidos inflamables si no pertenecen a las clases de almacenamiento LGK 3A o 3B'),
        ('storage_class', '11 Sólidos inflamables'),
        ('storage_class', '12 Líquidos no inflamables en envases no inflamables'),
        ('storage_class', '13 Sólidos no inflamables en envases no inflamables')
    ]
    new_instances = []
    for key, description in list_catalog:
        new_instances.append(Catalog(key=key, description=description))

    Catalog.objects.bulk_create(new_instances)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_auto_20201001_1518'),
    ]

    operations = [
        migrations.RunPython(load_sustancecharacteristic),
    ]
