# Generated by Django 2.2.13 on 2020-10-05 18:41

from django.db import migrations, models
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0016_sustancecharacteristics_seveso_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='nfpa',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_nfpa', to='laboratory.Catalog', verbose_name='NFPA codes'),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='seveso_list',
            field=models.BooleanField(default=False, verbose_name='Is Seveso list III?'),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='storage_class',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_storage_class', to='laboratory.Catalog', verbose_name='Storage class'),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='ue_code',
            field=laboratory.catalog.GTManyToManyField(blank=True, related_name='gt_ue', to='laboratory.Catalog', verbose_name='UE codes'),
        ),
    ]
