# Generated by Django 2.2.13 on 2020-11-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0017_auto_20201005_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_position',
            field=models.CharField(default='Princiapl technician', max_length=100, verbose_name='Job Position'),
            preserve_default=False,
        ),
    ]
