# Generated by Django 2.2.13 on 2021-02-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0019_blockedlistnotification'),
    ]

    def keep_one_profile(apps, scheme_editor):
        user = apps.get_model('auth', 'user')
        users = user.objects.all()
        for u in users:
            while(u.profile_set.count() > 1):
                u.profile_set.first().delete()

    operations = [
        migrations.RunPython(keep_one_profile)
    ]
