# Generated by Django 2.2.13 on 2021-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0022_profilepermission_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='coordinator',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
