# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0023_auto_20170504_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
