# Generated by Django 2.2.13 on 2021-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0023_auto_20210318_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='coordinator',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
