# Generated by Django 2.2.13 on 2021-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0024_auto_20210318_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('legal_identity', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
