# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 16:44
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0025_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='pressure',
            field=models.CharField(default='1 atm', max_length=100, verbose_name='Pressure'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='temperature',
            field=models.CharField(default='25 degC', max_length=100, verbose_name='Temperature'),
        ),
    ]
