# Generated by Django 2.2.13 on 2021-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0025_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unit'),
        ),
    ]
