# Generated by Django 2.2.13 on 2021-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0026_laboratory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlogchange',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
