# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 22:56
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0026_auto_20170508_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(default='Test solution', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
