# Generated by Django 2.2.13 on 2021-03-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0027_objectlogchange_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlogchange',
            name='bill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectlogchange',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Provider'),
        ),
    ]
