# Generated by Django 2.2.13 on 2021-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0028_auto_20210324_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlogchange',
            name='type_action',
            field=models.IntegerField(default=0),
        ),
    ]
