# Generated by Django 2.2.13 on 2021-04-03 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0029_objectlogchange_type_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlogchange',
            name='provider',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Provider'),
        ),
        migrations.CreateModel(
            name='TranferObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantify', models.FloatField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('laboratory_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_received', to='laboratory.Laboratory', verbose_name='Laboratory Received')),
                ('laboratory_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_send', to='laboratory.Laboratory', verbose_name='Laboratory Send')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.ShelfObject', verbose_name='Object')),
            ],
        ),
    ]
