# Generated by Django 2.2.13 on 2021-04-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0030_auto_20210403_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranferobject',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
