# Generated by Django 2.2.13 on 2021-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0031_tranferobject_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranferobject',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted')], default=0),
        ),
    ]
