# Generated by Django 2.2.13 on 2021-04-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0032_tranferobject_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranferobject',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
