# Generated by Django 2.2.13 on 2021-04-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0033_auto_20210405_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.Laboratory'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='legal_identity',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='legal identity'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='phone'),
        ),
    ]
