# Generated by Django 2.2.13 on 2021-04-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0034_auto_20210407_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectlogchange',
            name='type_action',
        ),
        migrations.AddField(
            model_name='objectlogchange',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objectlogchange',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Provider'),
        ),
    ]
