# Generated by Django 2.2.13 on 2021-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0035_auto_20210408_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlogchange',
            name='type_action',
            field=models.IntegerField(default=0),
        ),
    ]
