# Generated by Django 2.2.13 on 2021-04-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0036_objectlogchange_type_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecursorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Laboratory', verbose_name='Laboratory')),
            ],
        ),
    ]
