# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0036_delete_feedbackentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='object',
            name='plaque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plaque'),
        ),
        migrations.AddField(
            model_name='object',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie'),
        ),
    ]
