# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
try:
    import mptt.fields
    TreeForeignKey = mptt.fields.TreeForeignKey
except:
    TreeForeignKey = models.ForeignKey



class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0037_auto_20180630_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principaltechnician',
            options={'ordering': ['name'], 'permissions': (('view_principaltechnician', 'Can see available PrincipalTechnician'),), 'verbose_name': 'Principal Technician', 'verbose_name_plural': 'Principal Technicians'},
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='laboratorists',
            field=models.ManyToManyField(blank=True, related_name='laboratorists', to=settings.AUTH_USER_MODEL, verbose_name='Laboratorists'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='organization',
            field=TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.OrganizationStructure', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='laboratory.LaboratoryRoom', verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='object',
            name='features',
            field=models.ManyToManyField(to='laboratory.ObjectFeatures', verbose_name='Object features'),
        ),
        migrations.AlterField(
            model_name='organizationstructure',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='organizationstructure',
            name='parent',
            field=TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='laboratory.OrganizationStructure', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='principaltechnician',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.Laboratory', verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='principaltechnician',
            name='organization',
            field=TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.OrganizationStructure', verbose_name='Organization')

        ),
        migrations.AlterField(
            model_name='shelf',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Furniture', verbose_name='Furniture'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(default='nd', max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Object', verbose_name='Equipment or reactive or sustance'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Shelf', verbose_name='Shelf'),
        ),
    ]
