# Generated by Django 2.2.13 on 2021-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0038_auto_20210409_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='precursorreport',
            name='consecutive',
            field=models.IntegerField(default=1),
        ),
    ]
