# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0038_auto_20180630_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='container_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.Shelf', verbose_name='Container shelf'),
        ),
    ]
