# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0039_auto_20180630_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfeatures',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]

