# Generated by Django 2.2.20 on 2021-05-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0039_precursorreport_consecutive'),
    ]

    operations = []

