# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-18 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0041_auto_20190423_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstructure',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationstructure',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationstructure',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
