# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0018_auto_20190423_1611'),
        ('laboratory', '0041_auto_20190423_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='h_code',
            field=models.ManyToManyField(blank=True, to='sga.DangerIndication', verbose_name='Danger Indication'),
        ),
        migrations.AlterField(
            model_name='object',
            name='imdg_code',
            field=models.CharField(blank=True, choices=[('1', 'Explosives'), ('2', 'Gases'), ('3', 'Flammable liquids'), ('4', 'Flammable solids'), ('5', 'Oxidizing substances and organic peroxides'), ('6', 'Toxic and infectious substances'), ('7', 'Radioactive material'), ('8', 'Corrosive substances'), ('9', 'Miscellaneous dangerous substances and articles')], help_text='* Eliminado en la próxima versión', max_length=1, null=True, verbose_name='IMDG code'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='measurement_unit',
            field=models.CharField(choices=[('0', 'Meters'), ('1', 'Milimeters'), ('2', 'Centimeters'), ('3', 'Liters'), ('4', 'Mililiters'), ('5', 'Unit'), ('6', 'Gram'), ('7', 'Kilogram'), ('8', 'Miligram'), ('9', 'Cubic Meter')], max_length=2, verbose_name='Measurement unit'),
        ),
    ]
