# Generated by Django 2.2.20 on 2021-05-27 15:10

from django.db import migrations


def update_template(apps, schema_editor):
    model = apps.get_model('async_notifications', 'EmailTemplate')
    template = model.objects.filter(code='Shelf object in limit').first()
    if template is not None:
        temp = "<p>Hola</p><p>&nbsp;</p><p>Usted ha recibido este correo porque tiene un cambio en un laboratorio en el sistema Organilab.</p>" \
               "<p>&nbsp;</p><p>Este mensaje es para notificarle que uno o m&aacute;s objetos en su laboratorio est&aacute;n en las cuotas m&iacute;nimas.</p>" \
               "<h4>Detalle de productos</h4>" \
               "<p>{% for obj in shelf_object %}</p><p><strong>Estante:</strong> {{ obj.shelf }} <strong>Objeto:</strong> {{ obj.object }} <strong>Cantidad de material:</strong> {{ obj.quantity }} <strong>Cantidad l&iacute;mite de material:</strong> {{ obj.limit_quantity }} <strong>Unidad de medida:</strong> {{ obj.measurement_unit }}</p>" \
               "<p><a href='{{ blockurl }}{{ obj.pk }}'>{{ blockurl }}{{ obj.pk }}</a></p><p>{% endfor %}</p><p>&nbsp;</p><p>&nbsp;</p>" \
               "<p>&nbsp;</p><p>&nbsp;</p>" \
               "<p>Por favor recargue este producto o contacte a la persona que pueda hacerlo.</p>" \
               "<p><br />Gracias,<br /><br />Organilab: Reporte de objetos</p><p>&nbsp;</p>" \
               "<p>&nbsp;</p>"
        template.message = temp
        template.save()

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0041_change_email_template'),
    ]

    operations = [
        migrations.RunPython(update_template),
    ]
