# Generated by Django 3.2 on 2022-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0044_change_email_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='bioaccumulable',
            field=models.BooleanField(null=True),
        ),
    ]
