# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0044_auto_20200303_1251'),
        ('laboratory', '0042_auto_20200118_0034'),
    ]

    operations = [
    ]
