# Generated by Django 3.2 on 2022-10-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0045_alter_sustancecharacteristics_bioaccumulable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
