# Generated by Django 4.1.2 on 2022-10-10 17:43

from django.db import migrations, models

def gen_position(apps, schema_editor):
    OrganizationStructure = apps.get_model('laboratory', 'OrganizationStructure')
    for obj in OrganizationStructure.objects.all():
        obj.position = obj.tree_id * 100000 + obj.lft
        obj.save(update_fields=['position'])

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0046_delete_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'ordering': ['position'], 'permissions': (('add_organizationusermanagement', 'Can add organization user management'), ('change_organizationusermanagement', 'Can change organization user management'), ('delete_organizationusermanagement', 'Can delete organization user management'), ('view_organizationusermanagement', 'Can view organization user management')), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(gen_position, reverse_code=migrations.RunPython.noop),
    ]
