# Generated by Django 4.1.2 on 2022-10-10 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0047_alter_organizationstructure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizationstructure',
            managers=[
                ('os_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='level',
        ),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='organizationstructure',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizationstructure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='laboratory.organizationstructure', verbose_name='parent'),
        ),
    ]
