# Generated by Django 4.1.2 on 2022-10-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0048_alter_organizationstructure_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizationstructure',
            managers=[
            ],
        ),
    ]
