# Generated by Django 4.1.2 on 2022-10-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0048_alter_organizationstructure_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizationstructure',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Phone'),
        ),
    ]
