# Generated by Django 4.0.8 on 2022-10-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('derb', '0001_initial'),
        ('laboratory', '0049_alter_organizationstructure_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='labroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratoryroom', verbose_name='Labroom'),
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('custom_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='derb.customform', verbose_name='Template')),
            ],
        ),
        migrations.AddIndex(
            model_name='inform',
            index=models.Index(fields=['content_type', 'object_id'], name='laboratory__content_cdb4bc_idx'),
        ),
    ]
