# Generated by Django 4.0.8 on 2022-10-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0050_remove_profilepermission_laboratories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='labroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratoryroom', verbose_name='Labroom'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure', verbose_name='Organization'),
        ),
    ]
