# Generated by Django 4.0.8 on 2022-10-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0050_alter_furniture_labroom_inform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inform',
            name='status',
            field=models.CharField(choices=[('Eraser', 'Eraser'), ('In Review', 'In Review'), ('Finalized', 'Finalized')], default='Eraser', max_length=6),
        ),
    ]
