# Generated by Django 4.0.8 on 2022-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0051_inform_schema_inform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='status',
            field=models.CharField(choices=[('Eraser', 'Eraser'), ('In Review', 'In Review'), ('Finalized', 'Finalized')], default='Eraser', max_length=20),
        ),
    ]
