# Generated by Django 4.0.8 on 2022-10-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0051_alter_furniture_labroom_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """BEGIN;
SELECT setval(pg_get_serial_sequence('"laboratory_clinventory"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_clinventory";
SELECT setval(pg_get_serial_sequence('"laboratory_catalog"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_catalog";
SELECT setval(pg_get_serial_sequence('"laboratory_objectfeatures"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_objectfeatures";
SELECT setval(pg_get_serial_sequence('"laboratory_object_features"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_object_features";
SELECT setval(pg_get_serial_sequence('"laboratory_object_laboratory"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_object_laboratory";
SELECT setval(pg_get_serial_sequence('"laboratory_object"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_object";
SELECT setval(pg_get_serial_sequence('"laboratory_sustancecharacteristics_white_organ"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_sustancecharacteristics_white_organ";
SELECT setval(pg_get_serial_sequence('"laboratory_sustancecharacteristics_h_code"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_sustancecharacteristics_h_code";
SELECT setval(pg_get_serial_sequence('"laboratory_sustancecharacteristics_ue_code"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_sustancecharacteristics_ue_code";
SELECT setval(pg_get_serial_sequence('"laboratory_sustancecharacteristics_nfpa"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_sustancecharacteristics_nfpa";
SELECT setval(pg_get_serial_sequence('"laboratory_sustancecharacteristics_storage_class"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_sustancecharacteristics_storage_class";
SELECT setval(pg_get_serial_sequence('"laboratory_sustancecharacteristics"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_sustancecharacteristics";
SELECT setval(pg_get_serial_sequence('"laboratory_shelfobject"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_shelfobject";
SELECT setval(pg_get_serial_sequence('"laboratory_laboratoryroom"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_laboratoryroom";
SELECT setval(pg_get_serial_sequence('"laboratory_shelf"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_shelf";
SELECT setval(pg_get_serial_sequence('"laboratory_furniture"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_furniture";
SELECT setval(pg_get_serial_sequence('"laboratory_organizationstructure"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_organizationstructure";
SELECT setval(pg_get_serial_sequence('"laboratory_organizationusermanagement_users"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_organizationusermanagement_users";
SELECT setval(pg_get_serial_sequence('"laboratory_organizationusermanagement"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_organizationusermanagement";
SELECT setval(pg_get_serial_sequence('"laboratory_laboratory_rooms"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_laboratory_rooms";
SELECT setval(pg_get_serial_sequence('"laboratory_laboratory"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_laboratory";
SELECT setval(pg_get_serial_sequence('"laboratory_provider"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_provider";
SELECT setval(pg_get_serial_sequence('"laboratory_objectlogchange"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_objectlogchange";
SELECT setval(pg_get_serial_sequence('"laboratory_blockedlistnotification"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_blockedlistnotification";
SELECT setval(pg_get_serial_sequence('"laboratory_tranferobject"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_tranferobject";
SELECT setval(pg_get_serial_sequence('"laboratory_precursorreport"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "laboratory_precursorreport";
COMMIT; """
        )
    ]
