# Generated by Django 4.0.8 on 2022-10-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0004_rol_color'),
        ('laboratory', '0052_update_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstructure',
            name='rol',
            field=models.ManyToManyField(blank=True, to='auth_and_perms.rol'),
        ),
    ]
