# Generated by Django 4.0.8 on 2022-11-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0053_commentinform'),
        ('laboratory', '0053_organizationstructure_rol'),
    ]

    operations = [
    ]
