# Generated by Django 4.0.8 on 2022-11-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0054_merge_20221101_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinform',
            name='inform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.inform', verbose_name='Inform'),
        ),
    ]
