# Generated by Django 4.0.8 on 2022-11-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0056_remove_organizationusermanagement_group'),
    ]

    operations = [
    ]
