# Generated by Django 4.0.8 on 2022-11-08 00:36

from django.db import migrations, models

def getTree(node, level=0):
    node.level=level
    node.save()
    if node.children.exists():
        for child in node.children.all():
            getTree(child, level=level+1)

def add_level(apps, schema_editor):
    OrganizationStructure = apps.get_model('laboratory', 'OrganizationStructure')
    parents=OrganizationStructure.objects.filter(parent=None)
    for node in parents:
        getTree(node, level=0)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0057_create_organizationmanagement_form_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstructure',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunPython(add_level, reverse_code=migrations.RunPython.noop)
    ]
