# Generated by Django 4.0.8 on 2022-11-11 18:12

from django.db import migrations

def remove_comments(apps, schema_editor):
    Comment = apps.get_model('laboratory', 'CommentInform')
    comments=Comment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0059_organizationstructurerelations_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_comments),
        migrations.RemoveField(
            model_name='commentinform',
            name='inform',
        ),
    ]
