# Generated by Django 4.0.8 on 2022-11-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0061_commentinform_inform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationusermanagement',
            name='group',
        ),
    ]
