# Generated by Django 4.0.8 on 2022-12-15 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0062_remove_organizationusermanagement_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('file', models.FileField(upload_to='msds', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='MSDS File')),
                ('short_description', models.CharField(max_length=300, verbose_name='short description')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory')),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
                'ordering': ('pk',),
            },
        ),
    ]
