# Generated by Django 4.0.8 on 2022-12-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0063_laborglogentry'),
        ('laboratory', '0064_protocol_creation_date_protocol_last_update_and_more'),
    ]

    operations = [
    ]
