# Generated by Django 4.0.8 on 2022-12-17 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0065_merge_20221217_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(upload_to='protocols', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Protocol PDF File'),
        ),
    ]
