# Generated by Django 4.0.8 on 2023-01-16 20:55

from django.db import migrations


def add_user_orgs(apps, schema_editor):

    user_org = apps.get_model('laboratory', 'UserOrganization')
    user_org.objects.all().delete()
    org_user_management= apps.get_model('laboratory', 'OrganizationUserManagement')
    for org in org_user_management.objects.all():
        for user in org.users.all():
            user_org.objects.get_or_create(
                organization=org.organization,
                user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0069_userorganization'),
    ]

    operations = [
        migrations.RunPython(add_user_orgs)
    ]

