# Generated by Django 4.0.8 on 2023-01-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0070_auto_20230116_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustancecharacteristics',
            name='img_representation',
            field=models.ImageField(blank=True, null=True, upload_to='sustances/', verbose_name='Sustance representation'),
        ),
    ]
