# Generated by Django 4.0.8 on 2023-01-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0072_shelf_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobject',
            name='marked_as_discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tranferobject',
            name='mark_as_discard',
            field=models.BooleanField(default=False),
        ),
    ]
