# Generated by Django 4.0.8 on 2023-02-02 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('derb', '0002_customform_created_by_customform_creation_date_and_more'),
        ('laboratory', '0074_furniture_color_furniture_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('start_application_date', models.DateField()),
                ('close_application_date', models.DateField()),
                ('period_on_days', models.IntegerField(default=365)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inform_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derb.customform', verbose_name='Inform template')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformsPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('start_application_date', models.DateField()),
                ('close_application_date', models.DateField()),
                ('inform_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derb.customform', verbose_name='Inform template')),
                ('informs', models.ManyToManyField(blank=True, to='laboratory.inform')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure', verbose_name='Organization')),
                ('scheduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.informscheduler')),
            ],
        ),
    ]
