# Generated by Django 4.0.8 on 2023-02-02 17:43

from django.db import migrations
import zoneinfo


def register_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='30',
        hour='4',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
        timezone=zoneinfo.ZoneInfo('America/Costa_Rica')
    )

    PeriodicTask.objects.create(
        crontab=schedule,
        name='Check new inform period',
        task='laboratory.tasks.create_informs_based_on_period',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('laboratory', '0075_informscheduler_informsperiod'),
    ]

    operations = [
        migrations.RunPython(register_task, reverse_code=migrations.RunPython.noop),
    ]
