# Generated by Django 4.0.8 on 2023-02-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0076_register_task_period_inform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informsperiod',
            options={'ordering': ['-start_application_date']},
        ),
    ]
