# Generated by Django 4.0.8 on 2023-02-14 22:16

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0076_register_task_period_inform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informsperiod',
            options={'ordering': ['-start_application_date']},
        ),
        migrations.AddField(
            model_name='shelf',
            name='discard',
            field=models.BooleanField(default=True, verbose_name='Discard'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='measurement_unit',
            field=laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurementshelfunit', to='laboratory.catalog', verbose_name='Measurement unit'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='quantity',
            field=models.FloatField(default=0, help_text='Use dot like 0.344 on decimal', verbose_name='Quantity'),
        ),
    ]
