# Generated by Django 4.0.8 on 2023-02-15 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0008_alter_usertotpdevice_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('laboratory', '0076_register_task_period_inform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informsperiod',
            options={'ordering': ['-start_application_date']},
        ),
        migrations.CreateModel(
            name='RegisterUserQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('activate_user', models.BooleanField(default=True, verbose_name='Activate user')),
                ('url', models.TextField(verbose_name='Url')),
                ('register_user_qr', models.FileField(upload_to='register_user_qr/', verbose_name='Register user QR')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_creator', to='laboratory.organizationstructure')),
                ('organization_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_register', to='laboratory.organizationstructure')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth_and_perms.rol', verbose_name='Role')),
            ],
        ),
    ]
