# Generated by Django 4.0.8 on 2023-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0076_register_task_period_inform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informsperiod',
            options={'ordering': ['-start_application_date']},
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='shelf_object_qr',
            field=models.FileField(null=True, upload_to='shelf_object_qr/', verbose_name='Shelf Object QR'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='shelf_object_url',
            field=models.TextField(null=True, verbose_name='Shelf Object Url'),
        ),
    ]
