# Generated by Django 4.0.8 on 2023-02-14 22:41

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0078_remove_shelf_discard_remove_shelf_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='discard',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shelf',
            name='discard',
            field=models.BooleanField(default=True, verbose_name='Discard'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='measurement_unit',
            field=laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurementshelfunit', to='laboratory.catalog', verbose_name='Measurement unit'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='quantity',
            field=models.FloatField(default=0, help_text='Use dot like 0.344 on decimal', verbose_name='Quantity'),
        ),
    ]
