# Generated by Django 4.0.8 on 2023-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0080_shelf_course_name_shelf_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='laboratory_name',
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='course_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Course name'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='laboratory_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Laboratory name'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='discard',
            field=models.BooleanField(default=False, verbose_name='Discard'),
        ),
    ]
