# Generated by Django 4.0.8 on 2023-02-22 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0081_remove_shelf_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobject',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='discard',
            field=models.BooleanField(default=False, verbose_name='Disposal'),
        ),
    ]
