# Generated by Django 4.0.8 on 2023-02-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0077_alter_informsperiod_options_and_more'),
        ('laboratory', '0077_alter_informsperiod_options_registeruserqr'),
        ('laboratory', '0082_shelfobject_creator_alter_shelf_discard'),
    ]

    operations = [
    ]
