# Generated by Django 4.0.8 on 2023-03-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0083_merge_20230227_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'permissions': [('can_manage_disposal', 'Can manage disposal')]},
        ),
    ]
