# Generated by Django 4.0.8 on 2023-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0083_merge_20230227_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruserqr',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
