# Generated by Django 4.0.8 on 2023-03-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0084_alter_shelf_options'),
        ('laboratory', '0084_registeruserqr_code'),
    ]

    operations = [
    ]
