# Generated by Django 4.0.8 on 2023-03-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0085_merge_20230302_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruserqr',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
    ]
