# Generated by Django 4.0.8 on 2023-03-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0086_alter_registeruserqr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'permissions': [('can_manage_disposal', 'Can manage disposal'), ('can_add_disposal', 'Can add disposal'), ('can_view_disposal', 'Can view disposal')]},
        ),
    ]
