# Generated by Django 4.0.8 on 2023-03-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0087_alter_shelf_description'),
        ('laboratory', '0087_alter_shelf_options'),
    ]

    operations = [
    ]
