# Generated by Django 4.0.8 on 2023-03-09 22:19

from django.db import migrations
from django_celery_beat.models import CrontabSchedule, PeriodicTask

def createShedule(apps, schema_editor):
    schedule, _ = CrontabSchedule.objects.get_or_create(minute='23',hour='5')
    PeriodicTask.objects.create(crontab=schedule,name='Remove Phantoms Shelfs',task='laboratory.tasks.remove_shelf_not_furniture')

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0088_merge_20230303_2031'),
    ]

    operations = [
        migrations.RunPython(createShedule)
    ]
