# Generated by Django 4.0.8 on 2023-03-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0077_alter_informsperiod_options'),
        ('laboratory', '0088_merge_20230303_2031'),
    ]

    operations = [
    ]
