# Generated by Django 4.0.8 on 2023-03-11 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0088_merge_20230303_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobject',
            name='in_where_laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory'),
        ),
    ]
