# Generated by Django 4.0.8 on 2023-03-11 04:52

from django.db import migrations

def create_laboratory_shelfobject_task(apps, schema_editor):
    ShelfObject = apps.get_model('laboratory', 'ShelfObject')
    for shelfobject in ShelfObject.objects.all():
        laboratory = shelfobject.shelf.furniture.labroom.laboratory_set.all().first()
        shelfobject.in_where_laboratory=laboratory
        shelfobject.save()

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0089_shelfobject_in_where_laboratory'),
    ]

    operations = [
        migrations.RunPython(create_laboratory_shelfobject_task, reverse_code=migrations.RunPython.noop),
    ]
