# Generated by Django 4.0.8 on 2023-03-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0089_merge_20230309_1718'),
        ('laboratory', '0090_insertlaboratoryinshelfobject'),
    ]

    operations = [
    ]
