# Generated by Django 4.0.8 on 2023-03-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0091_merge_20230313_1137'),
        ('laboratory', '0091_merge_20230314_1639'),
    ]

    operations = [
    ]
