# Generated by Django 4.0.8 on 2023-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0091_merge_20230321_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='type_in_organization',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Laboratory Manager'), (3, 'Laboratory User')], default=3),
        ),
    ]
