# Generated by Django 4.0.8 on 2023-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0092_merge_20230315_1717'),
        ('laboratory', '0092_merge_20230316_0921'),
    ]

    operations = [
    ]
