# Generated by Django 4.0.8 on 2023-04-04 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('laboratory', '0093_mv_userorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstructure',
            name='users',
            field=models.ManyToManyField(blank=True, through='laboratory.UserOrganization', to=settings.AUTH_USER_MODEL),
        ),
    ]
