# Generated by Django 4.0.8 on 2023-04-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0094_organizationstructure_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'ordering': ['position'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.DeleteModel(
            name='OrganizationUserManagement',
        ),
    ]
