# Generated by Django 4.0.8 on 2023-04-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0092_taskreport'),
        ('laboratory', '0095_alter_organizationstructure_options_and_more'),
    ]

    operations = [
    ]
