# Generated by Django 4.0.8 on 2023-04-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0096_merge_20230406_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryroom',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lab_old', to='laboratory.laboratoryroom', verbose_name='Rooms'),
        ),
    ]
