# Generated by Django 4.0.8 on 2023-04-08 01:27

from django.db import migrations


def mv_rooms(apps, schema_editor):
    Laboratory = apps.get_model('laboratory', 'Laboratory')

    for lab in Laboratory.objects.all():
        labrooms = lab.rooms.all()
        for labroom in labrooms:
            if labroom.laboratory is None:
                labroom.laboratory=lab
                labroom.save()
            else:
                print(labroom.pk, "\t",str(labroom), "\t", str(lab), "\t", labroom.laboratory)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0097_laboratoryroom_laboratory_alter_laboratory_rooms'),
    ]

    operations = [
        migrations.RunPython(mv_rooms, reverse_code=migrations.RunPython.noop),
    ]
