# Generated by Django 4.1.8 on 2023-04-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0098_mv_labroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='TaskReport',
        ),
    ]
