# Generated by Django 4.0.8 on 2023-04-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0098_mv_labroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='rooms',
        ),
    ]
