# Generated by Django 4.1.7 on 2023-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0099_remove_laboratory_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='table_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
