# Generated by Django 4.0.8 on 2023-04-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0100_alter_taskreport_table_content'),
        ('laboratory', '0100_taskreport_language'),
    ]

    operations = [
    ]
