# Generated by Django 4.1.9 on 2023-05-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0101_shelf_available_objects_when_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='available_objects_when_limit',
            field=models.ManyToManyField(related_name='limit_objects', to='laboratory.object', verbose_name='Only objects allowed in this shelf'),
        ),
    ]
