# Generated by Django 4.1.9 on 2023-05-12 03:55

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0102_alter_shelf_available_objects_when_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfObjectLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_limit', models.FloatField(default=0, help_text='Use dot like 0.344 on decimal', verbose_name='Limit material quantity')),
                ('maximum_limit', models.FloatField(default=0, help_text='Use dot like 0.344 on decimal', verbose_name='Limit material quantity')),
            ],
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='batch',
            field=models.CharField(default='0', max_length=250, verbose_name='Production batch'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='status',
            field=laboratory.catalog.GTForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.catalog', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='limit_quantity',
            field=models.FloatField(default=0, help_text='Use dot like 0.344 on decimal', verbose_name='Limit material quantity'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='limits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.shelfobjectlimits'),
        ),
    ]
