# Generated by Django 4.1.9 on 2023-05-12 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0103_shelfobjectlimits_shelfobject_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobjectlimits',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Expiration date'),
        ),
        migrations.CreateModel(
            name='ShelfObjectObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('action_taken', models.CharField(default='Object Change', max_length=50, verbose_name='Action Taken')),
                ('description', models.TextField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
