# Generated by Django 4.1.8 on 2023-05-15 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0105_alter_shelf_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfObjectContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.object', verbose_name='Container')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shelf_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.shelfobject', verbose_name='Shelf Object')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
