# Generated by Django 4.1.9 on 2023-05-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0106_shelfobjectcontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobjectlimits',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration date'),
        ),
    ]
