# Generated by Django 4.1.8 on 2023-05-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0106_shelfobjectcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobjectobservation',
            name='shelf_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.shelfobject'),
        ),
    ]
