# Generated by Django 4.1.8 on 2023-05-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0107_shelfobjectobservation_shelf_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobjectobservation',
            name='shelf_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.shelfobject'),
        ),
    ]
