# Generated by Django 4.0.8 on 2023-05-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0107_alter_shelfobjectlimits_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobjectobservation',
            name='shelf_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.shelfobject'),
            preserve_default=False,
        ),
    ]
