# Generated by Django 4.1.8 on 2023-05-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0107_alter_shelfobjectlimits_expiration_date'),
        ('laboratory', '0108_alter_shelfobjectobservation_shelf_object'),
    ]

    operations = [
    ]
