# Generated by Django 4.0.8 on 2023-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0109_merge_20230520_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='infinity_quantity',
            field=models.BooleanField(default=False, verbose_name='Infinite amount'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='quantity',
            field=models.FloatField(default=0, help_text='Use dot like 0.344 on decimal', verbose_name='Quantity'),
        ),
    ]
