# Generated by Django 4.0.8 on 2023-05-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0111_alter_shelfobject_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='infinity_quantity',
            field=models.BooleanField(default=True, verbose_name='Infinite amount'),
        ),
    ]
