# Generated by Django 4.0.8 on 2023-05-26 16:37

from django.db import migrations


def update_shelf_limits(apps, schema_editor):
    Shelf = apps.get_model('laboratory', 'Shelf')
    Shelf.objects.filter(quantity__lt=0.1, infinity_quantity=False).update(infinity_quantity=True)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0112_alter_shelf_infinity_quantity'),
    ]

    operations = [
        migrations.RunPython(update_shelf_limits, reverse_code=migrations.RunPython.noop),
    ]
