# Generated by Django 4.1.7 on 2023-06-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0113_fixed_limited_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="laboratory.shelfobject",
            ),
        ),
    ]
