# Generated by Django 4.1.7 on 2023-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0114_shelfobject_container"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShelfObjectContainer",
        ),
    ]
