# Generated by Django 4.1.7 on 2023-06-08 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0114_alter_shelf_quantity"),
        ("laboratory", "0115_delete_shelfobjectcontainer"),
    ]

    operations = []
