# Generated by Django 4.1.7 on 2023-06-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0116_merge_20230608_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelfobject",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containershelfobject",
                to="laboratory.shelfobject",
                verbose_name="Container",
            ),
        ),
    ]
