# Generated by Django 4.1.9 on 2023-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0118_shelfobject_quantity_base_unit_baseunitvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseunitvalues',
            name='si_value',
            field=models.FloatField(default=1),
        ),
    ]
