# Generated by Django 4.1.9 on 2023-06-21 16:13

from django.db import migrations
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0119_alter_baseunitvalues_si_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseunitvalues',
            name='measurement_unit',
            field=laboratory.catalog.GTOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseunit', to='laboratory.catalog', verbose_name='Base unit'),
        ),
    ]
