# Generated by Django 4.1.9 on 2023-06-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0120_alter_baseunitvalues_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobject',
            name='quantity_base_unit',
            field=models.FloatField(default=0, help_text='Quantity in its respective base unit', verbose_name='Quantity Base Unit'),
        ),
    ]
