# Generated by Django 4.0.8 on 2023-07-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0122_create_base_unit_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentinform',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='laboratoryroom',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='shelfobject',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='shelfobjectobservation',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='tranferobject',
            old_name='creator',
            new_name='created_by',
        ),
    ]
