# Generated by Django 4.0.8 on 2023-07-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0123_rename_creator_commentinform_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlogchange',
            name='organization_where_action_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.organizationstructure'),
        ),
    ]
