# Generated by Django 4.0.8 on 2023-07-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0124_objectlogchange_organization_where_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstructure',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
