# Generated by Django 4.1.8 on 2023-07-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0125_organizationstructure_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobject',
            name='quantity',
            field=models.FloatField(help_text='Use dot like 0.344 on decimal', verbose_name='Quantity'),
        ),
    ]
