# Generated by Django 4.0.8 on 2023-08-08 20:55

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0126_alter_shelfobject_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('capacity_measurement_unit', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.catalog', verbose_name='Capacity measurement unit')),
                ('object', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.object')),
            ],
        ),
    ]
