# Generated by Django 4.0.8 on 2023-08-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0126_alter_shelfobject_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(default='nd', max_length=150, verbose_name='Name'),
        ),
    ]
