# Generated by Django 4.1.10 on 2023-08-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0127_alter_shelf_name'),
        ('laboratory', '0127_materialcapacity'),
    ]

    operations = [
    ]
