# Generated by Django 4.1.11 on 2023-10-12 22:14

from django.db import migrations, models
import laboratory.models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0129_alter_object_options_alter_shelfobject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='security_sheet',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models.upload_security_sheets, verbose_name='Security sheet'),
        ),
    ]
