# Generated by Django 4.1.11 on 2023-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0129_alter_object_options_alter_shelfobject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_container',
            field=models.BooleanField(default=False, verbose_name='Is Container'),
        ),
    ]
