# Generated by Django 4.1.11 on 2023-10-13 19:37

import django.core.validators
from django.db import migrations, models
import laboratory.models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0130_alter_sustancecharacteristics_security_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(upload_to=laboratory.models.upload_protocol_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Protocol PDF File'),
        ),
        migrations.AlterField(
            model_name='registeruserqr',
            name='register_user_qr',
            field=models.FileField(upload_to=laboratory.models.upload_register_user_qr, verbose_name='Register user QR'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='shelf_object_qr',
            field=models.FileField(null=True, upload_to=laboratory.models.upload_shelf_object_qr, verbose_name='Shelf Object QR'),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='img_representation',
            field=models.ImageField(blank=True, null=True, upload_to=laboratory.models.upload_substance_img_representation, verbose_name='Sustance representation'),
        ),
    ]
