# Generated by Django 4.1.11 on 2023-10-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0131_alter_protocol_file_and_more'),
        ('laboratory', '0131_set_is_container'),
    ]

    operations = [
    ]
