# Generated by Django 4.1.11 on 2023-10-17 17:18

import django.core.validators
from django.db import migrations, models
import laboratory.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0131_set_is_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='is_container',
            field=models.BooleanField(default=False, verbose_name='Is Container?'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(upload_to=laboratory.models_utils.upload_files, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Protocol PDF File'),
        ),
        migrations.AlterField(
            model_name='registeruserqr',
            name='register_user_qr',
            field=models.FileField(upload_to=laboratory.models_utils.upload_files, verbose_name='Register user QR'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='shelf_object_qr',
            field=models.FileField(null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Shelf Object QR'),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='img_representation',
            field=models.ImageField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Sustance representation'),
        ),
        migrations.AlterField(
            model_name='sustancecharacteristics',
            name='security_sheet',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Security sheet'),
        ),
    ]
