# Generated by Django 4.1.13 on 2024-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0132_alter_object_is_container_alter_protocol_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfobject',
            name='course_name',
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
    ]
