# Generated by Django 4.1.13 on 2024-02-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0133_remove_shelfobject_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inform',
            options={'permissions': [('can_manage_inform_status', 'Can manage inform status')]},
        ),
    ]
