# Generated by Django 4.1.13 on 2024-03-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0135_equipmenttype_shelfobjecttraining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='organization',
        ),
    ]
