# Generated by Django 4.1.13 on 2024-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0135_equipmenttype_shelfobjecttraining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobjectmaintenance',
            name='maintenance_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
