# Generated by Django 4.1.13 on 2024-03-13 17:27

from django.db import migrations

def create_provider_laboratory(apps, schema_editor):
    Provider = apps.get_model('laboratory', 'Provider')
    Provider.objects.create(name="No se dispone de proveedor", phone_number="61569029",
                            email="contacto@organilab.org")

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0136_remove_equipmentcharacteristics_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(create_provider_laboratory)
    ]
