# Generated by Django 4.1.10 on 2024-03-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0136_create_provider_default'),
    ]

    operations = [
    ]
