# Generated by Django 4.1.10 on 2024-03-16 01:16

from django.db import migrations
from django.db.models import Q

def register_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
#    OrganizationStructure = apps.get_model('laboratory', 'OrganizationStructure')
    Rol = apps.get_model('auth_and_perms', 'Rol')
# ProfilePermission.objects.get_or_create(profile=profile, content_type=ct, object_id=profile.pk)
    perms=Permission.objects.filter(
        Q(codename__icontains='equipmenttype')|
        Q(codename__icontains='shelfobjecttraining')|
        Q(codename__icontains='shelfobjectmaintenance')|
        Q(codename__icontains='shelfobjectlog')|
        Q(codename__icontains='shelfobjectguarantee')|
        Q(codename__icontains='shelfobjectequipmentcharacteristics')|
        Q(codename__icontains='shelfobjectcalibrate')|
        Q(codename__icontains='equipmentcharacteristics')|
        Q(codename__icontains='can_manage_inform_status')|
        Q(codename__icontains='can_view_contract')|
        Q(codename__icontains='view_logentry')
                              )
    g, ok=Group.objects.get_or_create(name='RegisterOrganization')
    g.permissions.add(*perms)

    rols=Rol.objects.filter(name__icontains='Administración de Organización')
    for rol in rols:
        rol.permissions.add(*perms)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0136_create_provider_default'),
    ]

    operations = [
        migrations.RunPython(register_permissions,
                             reverse_code=migrations.RunPython.noop)
    ]
