# Generated by Django 4.1.13 on 2024-03-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0136_alter_shelfobjectmaintenance_maintenance_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfobject',
            options={'ordering': ['pk', 'object__name'], 'permissions': [('can_view_contract', 'Can view contract')], 'verbose_name': 'Shelf object', 'verbose_name_plural': 'Shelf objects'},
        ),
        migrations.AlterField(
            model_name='shelfobjectcalibrate',
            name='calibrate_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name of Calibrator'),
        ),
    ]
