# Generated by Django 4.1.13 on 2024-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0137_alter_shelfobject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobjecttraining',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place'),
        ),
    ]
