# Generated by Django 4.1.13 on 2024-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0137_add_equipment_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobjectequipmentcharacteristics',
            name='available_to_use',
            field=models.BooleanField(default=False, verbose_name='Is available to use?'),
        ),
        migrations.AlterField(
            model_name='shelfobjectequipmentcharacteristics',
            name='delivery_equipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='shelfobjectequipmentcharacteristics',
            name='equipment_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shelfobjectequipmentcharacteristics',
            name='have_guarantee',
            field=models.BooleanField(default=False, verbose_name='Has guarantee?'),
        ),
        migrations.AlterField(
            model_name='shelfobjectequipmentcharacteristics',
            name='purchase_equipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
    ]
