# Generated by Django 4.1.13 on 2024-04-25 23:42

from django.db import migrations, models
import laboratory.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0138_alter_shelfobjectequipmentcharacteristics_available_to_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobjectequipmentcharacteristics',
            name='contract_of_maintenance',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Contract of maintenance'),
        ),
    ]
