# Generated by Django 4.1.13 on 2024-04-15 17:55

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0138_alter_shelfobjectequipmentcharacteristics_available_to_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecursorReportValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('previous_balance', models.CharField(blank=True, max_length=200)),
                ('new_income', models.FloatField(default=0.0)),
                ('bills', models.CharField(blank=True, max_length=200)),
                ('providers', models.CharField(blank=True, max_length=200)),
                ('stock', models.FloatField(default=0.0)),
                ('month_expense', models.FloatField(default=0.0)),
                ('final_balance', models.FloatField(default=0.0)),
                ('reason_to_spend', models.TextField(blank=True)),
                ('measurement_unit', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.catalog', verbose_name='measurement unit')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.object')),
                ('precursor_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.precursorreport')),
            ],
        ),
        migrations.AddField(
            model_name='precursorreport',
            name='report_values',
            field=models.ManyToManyField(through='laboratory.PrecursorReportValues', to='laboratory.object'),
        ),
    ]
