# Generated by Django 4.1.13 on 2024-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0012_alter_profile_options'),
        ('laboratory', '0138_shelfobjecttraining_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='equipmentcharacteristics',
            name='organization',
        ),
        migrations.AlterField(
            model_name='shelfobjecttraining',
            name='intern_people_receive_training',
            field=models.ManyToManyField(to='auth_and_perms.profile', verbose_name='Internal participants in training'),
        ),
    ]
