# Generated by Django 4.1.13 on 2024-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0139_precursorreportvalues_precursorreport_report_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='previous_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
