# Generated by Django 4.1.13 on 2024-05-07 23:00

from django.db import migrations, models
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0140_alter_precursorreportvalues_previous_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='bills',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bills'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='final_balance',
            field=models.FloatField(default=0.0, verbose_name='Final balance'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='measurement_unit',
            field=laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.catalog', verbose_name='Measurement unit'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='month_expense',
            field=models.FloatField(default=0.0, verbose_name='Month expense'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='new_income',
            field=models.FloatField(default=0.0, verbose_name='New income'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.object', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='precursor_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.precursorreport', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='previous_balance',
            field=models.FloatField(default=0.0, verbose_name='Previous balance'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='providers',
            field=models.CharField(blank=True, max_length=200, verbose_name='Providers'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='reason_to_spend',
            field=models.TextField(blank=True, verbose_name='Reason to spend'),
        ),
        migrations.AlterField(
            model_name='precursorreportvalues',
            name='stock',
            field=models.FloatField(default=0.0, verbose_name='Stock'),
        ),
    ]
