# Generated by Django 5.1 on 2025-03-18 20:21

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0143_auto_20240917_0305"),
    ]
    operations = [
        UnaccentExtension()
    ]
