# Generated by Django 5.1 on 2025-04-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0145_alter_baseunitvalues_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['pk']},
        ),
    ]
