# Generated by Django 5.1 on 2025-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0146_alter_catalog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='area',
            field=models.FloatField(default=0.0, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sustancecharacteristics',
            name='concentration',
            field=models.FloatField(default=0.0, verbose_name='Concentration'),
        ),
    ]
