# Generated by Django 5.1 on 2025-04-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0147_laboratory_area_laboratory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobject',
            name='physical_status',
            field=models.CharField(blank=True, choices=[('no_reactive', ''), ('liquid', 'Liquid'), ('solid powder', 'Solid powder'), ('solid granular or crystalline', 'Solid granular or crystalline'), ('Gaseous', 'Gaseous')], max_length=100, null=True, verbose_name='Physical Status'),
        ),
    ]
