# Generated by Django 5.1 on 2025-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0148_shelfobject_physical_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustancecharacteristics',
            name='concentration',
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='concentration',
            field=models.FloatField(default=0.0, verbose_name='Concentration'),
        ),
    ]
