# Generated by Django 5.1 on 2025-05-07 15:41

import laboratory.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0150_laboratory_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='nearby_sites',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Study centers, hospitals, transportation terminals, gas stations, or others that might be affected in the event of an emergency.'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='water_resources_affected',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Rivers, streams, springs and aquifers that are affected in an emergency'),
        ),
    ]
