# Generated by Django 5.1 on 2025-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0151_laboratory_nearby_sites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precursorreport',
            name='month_belong',
            field=models.IntegerField(default=0),
        ),
    ]
