# Generated by Django 5.1 on 2025-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0152_precursorreport_month_belong'),
        ('sga', '0071_pictogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobject',
            name='pictograms',
            field=models.ManyToManyField(blank=True, related_name='sga_pictograms', to='sga.pictogram', verbose_name='Pictograms'),
        ),
    ]
