# Generated by Django 5.1 on 2025-05-28 22:43

from django.db import migrations

def create_new_catalog(apps, schema_editor):
    Catalog = apps.get_model('laboratory', 'Catalog')

    Catalog.objects.create(key="distance_unit", description="Metros cuadrados")
    Catalog.objects.create(key="distance_unit", description="Kilometros cuadrados")
class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0153_shelfobject_pictograms'),
    ]

    operations = [
        migrations.RunPython(create_new_catalog,
                             reverse_code=migrations.RunPython.noop)
    ]

