# Generated by Django 5.1 on 2025-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0154_add_distance_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='has_threshold',
            field=models.BooleanField(default=False, verbose_name='Has threshold?'),
        ),
        migrations.AddField(
            model_name='object',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Is Dangerous?'),
        ),
        migrations.AddField(
            model_name='object',
            name='threshold',
            field=models.FloatField(default=0.0, verbose_name='Threshold'),
        ),
    ]
