# Generated by Django 5.1 on 2025-06-24 22:13

from django.db import migrations

def update_has_threshold(apps, schema_editor):
    Object = apps.get_model('laboratory', 'Object')

    Object.objects.filter(type=0).update(has_threshold=True)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0155_object_has_threshold_object_is_dangerous_and_more'),
    ]

    operations = [
        migrations.RunPython(update_has_threshold,
                             reverse_code=migrations.RunPython.noop)
    ]
