# Generated by Django 5.2.6 on 2025-09-17 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0156_update_has_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationstructure",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                through="laboratory.UserOrganization",
                through_fields=("organization", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
