# Generated by Django 5.2.6 on 2025-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0157_alter_organizationstructure_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_pure',
            field=models.BooleanField(default=False, verbose_name='Is pure?'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
