# Generated by Django 5.2.6 on 2025-09-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0158_object_is_pure_shelfobject_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelfobject',
            old_name='expiration_date',
            new_name='reactive_expiration_date',
        ),
    ]
