# Generated by Django 5.2.6 on 2025-10-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0159_rename_expiration_date_shelfobject_reactive_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.object', verbose_name='Equipment or reactive or substance'),
        ),
        migrations.AlterField(
            model_name='shelfobjectlimits',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration date?'),
        ),
    ]
