# Generated by Django 5.2.6 on 2025-10-30 18:04

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0160_alter_shelfobject_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectMaximumLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory')),
                ('measurement_unit', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.catalog', verbose_name='Measurement unit')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.object')),
            ],
        ),
    ]
