# Generated by Django 5.2.6 on 2025-11-03 21:45

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0161_objectmaximumlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactiveLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_limit', models.FloatField(default=0.0, verbose_name='Maximum Limit')),
                ('minimum_limit', models.FloatField(default=0.0, verbose_name='Minimum Limit')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_reactive_limits', to='laboratory.laboratory', verbose_name='Laboratory')),
                ('measurement_unit', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurementunit_reactive_limits', to='laboratory.catalog', verbose_name='Measurement unit')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_reactive_limits', to='laboratory.object', verbose_name='Object')),
            ],
        ),
    ]
