# Generated by Django 5.2.6 on 2025-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0162_reactivelimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelfobject",
            name="physical_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_reactive", ""),
                    ("liquid", "Liquid"),
                    ("solid powder", "Solid powder"),
                    ("solid granular or crystalline", "Solid granular or crystalline"),
                    ("Gaseous", "Gaseous"),
                    ("Tablets", "Tablets"),
                    ("Lentils", "Lentils"),
                    ("Granza", "Granza"),
                ],
                max_length=100,
                null=True,
                verbose_name="Physical Status",
            ),
        ),
    ]
