# Generated by Django 5.2.8 on 2025-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0163_alter_shelfobject_physical_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='has_threshold',
            field=models.BooleanField(default=False, help_text='It belongs to the regulations of decree 44741', verbose_name='Has threshold?'),
        ),
        migrations.AlterField(
            model_name='object',
            name='is_dangerous',
            field=models.BooleanField(default=False, help_text='It belongs to the regulations of decree 44741', verbose_name='Is Dangerous?'),
        ),
        migrations.AlterField(
            model_name='object',
            name='is_pure',
            field=models.BooleanField(default=False, help_text='It belongs to the regulations of decree 44741', verbose_name='Is pure?'),
        ),
        migrations.AlterField(
            model_name='object',
            name='threshold',
            field=models.FloatField(default=0.0, help_text='It belongs to the regulations of decree 44741', verbose_name='Threshold'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='physical_status',
            field=models.CharField(blank=True, choices=[('no_reactive', ''), ('liquid', 'Liquid'), ('solid powder', 'Solid powder'), ('solid granular or crystalline', 'Solid granular or crystalline'), ('Gaseous', 'Gaseous'), ('Tablets', 'Tablets'), ('Lentils', 'Lentils'), ('Granza', 'Granza'), ('card', 'Card'), ('solid', 'Solid'), ('colloidal', 'Colloidal'), ('viscuos liquid', 'Viscuos Liquid'), ('kit', 'Kit')], max_length=100, null=True, verbose_name='Physical Status'),
        ),
    ]
