# Generated by Django 5.2.8 on 2026-01-06 21:40

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations, models

def create_new_catalog(apps, schema_editor):
    Catalog = apps.get_model('laboratory', 'Catalog')

    for description in ["Universidad Nacional","Fundauna", "Otro"]:
       Catalog.objects.create(key="type_budget", description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0164_alter_object_has_threshold_alter_object_is_dangerous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobject',
            name='container_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Container Entry Date'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='container_open_date',
            field=models.DateField(blank=True, null=True, verbose_name='Container Open Date'),
        ),
        migrations.AddField(
            model_name='shelfobject',
            name='type_budget',
            field=laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_budget', to='laboratory.catalog', verbose_name='Type Budget'),
        ),
        migrations.RunPython(create_new_catalog, reverse_code=migrations.RunPython.noop),
    ]
