# Generated by Django 5.2.8 on 2026-01-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0164_alter_object_has_threshold_alter_object_is_dangerous_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='faculty_dispatch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Faculty or dispatch'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='workplace',
            field=models.ManyToManyField(blank=True, related_name='workplace', to='laboratory.organizationstructure', verbose_name='Workplace'),
        ),
        migrations.CreateModel(
            name='LaboratoryProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_proccess', to='laboratory.laboratory', verbose_name='Laboratory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
