# Generated by Django 5.2.8 on 2026-01-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0165_laboratory_faculty_dispatch_laboratory_workplace_and_more'),
        ('laboratory', '0165_shelfobject_container_entry_date_and_more'),
    ]

    operations = [
    ]
