# Generated by Django 5.2.8 on 2026-02-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0166_merge_20260114_1219"),
    ]

    operations = [
        migrations.AddField(
            model_name="sustancecharacteristics",
            name="density",
            field=models.FloatField(
                default=0,
                help_text="t belongs to the regulations of decree 44741, only use dot like 0.344 on decimal",
                verbose_name="Density",
            ),
        ),
    ]
