# Generated by Django 5.2.8 on 2026-02-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0166_merge_20260114_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'ordering': ['position'], 'permissions': [('can_manage_org_permissions', 'Can manage organization permission structure')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
