# Generated by Django 5.2.8 on 2026-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0166_merge_20260114_1219"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="without_limit",
            field=models.BooleanField(default=False, verbose_name="Without limit"),
        ),
    ]
