# Generated by Django 5.2.8 on 2026-02-04 16:56

from django.db import migrations


def forwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    OrganizationStructure = apps.get_model("laboratory", "OrganizationStructure")

    group, _ = Group.objects.get_or_create(name="RegisterOrganization")

    ct, _ = ContentType.objects.get_or_create(
        app_label="laboratory",
        model=OrganizationStructure._meta.model_name,  # "organizationstructure"
    )

    perm, _ = Permission.objects.get_or_create(
        content_type=ct,
        codename="can_manage_org_permissions",
        defaults={"name": "Can manage organization permission structure"},
    )

    if not group.permissions.filter(pk=perm.pk).exists():
        group.permissions.add(perm)


def backwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    group_name = "RegisterOrganization"
    perm_codename = "can_manage_org_permissions"

    try:
        group = Group.objects.get(name=group_name)
    except Group.DoesNotExist:
        return

    try:
        ct = ContentType.objects.get(
            app_label="laboratory", model="organizationstructure"
        )
        perm = Permission.objects.get(content_type=ct, codename=perm_codename)
    except (ContentType.DoesNotExist, Permission.DoesNotExist):
        return

    group.permissions.remove(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0167_alter_organizationstructure_options"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
