# Generated by Django 5.2.8 on 2026-02-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0167_sustancecharacteristics_density"),
        ("laboratory", "0168_add_can_manage_org_permissions_to_registerorganization"),
    ]

    operations = []
