# Generated by Django 5.2.8 on 2026-02-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0168_add_can_manage_org_permissions_to_registerorganization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationstructure",
            options={
                "ordering": ["position"],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AddField(
            model_name="shelfobject",
            name="was_donated",
            field=models.BooleanField(default=False, verbose_name="Was donated?"),
        ),
    ]
