# Generated by Django 5.2.8 on 2026-02-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0169_alter_organizationstructure_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationstructure",
            options={
                "ordering": ["position"],
                "permissions": [
                    (
                        "can_manage_org_permissions",
                        "Can manage organization permission structure",
                    )
                ],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
    ]
