# Generated by Django 5.2.8 on 2026-02-09 14:37

from django.db import migrations

def create_expiration_template(apps, schema_editor):
    model = apps.get_model('async_notifications', 'EmailTemplate')

    template = model.objects.filter(code='Expiring reactives').first()

    if template is None:
        temp = "<p>Hola</p>" \
               "<p>&nbsp;</p>" \
               "<p>Usted ha recibido este correo porque tiene reactivos pr&oacute;ximos a vencer en el sistema Organilab.</p>" \
               "<p>&nbsp;</p>" \
               "<p>Este mensaje es para notificarle que uno o m&aacute;s reactivos en el laboratorio <strong>{{ laboratory.name }}</strong> vencer&aacute;n ma&ntilde;ana.</p>" \
               "<h4>Reactivos pr&oacute;ximos a vencer</h4>" \
               "{% for obj in shelf_object %}" \
               "<p>" \
               "<strong>Estante:</strong> {{ obj.shelf }} " \
               "<strong>Reactivo:</strong> {{ obj.object }} " \
               "<strong>Fecha de vencimiento:</strong> {{ obj.reactive_expiration_date }} " \
               "<strong>Cantidad disponible:</strong> {{ obj.quantity }} {{ obj.measurement_unit }}" \
               "</p>" \
               "<p><a href='{{ blockurl }}{{ obj.object.pk }}/'>{{ blockurl }}{{ obj.object.pk }}/</a></p>" \
               "{% endfor %}" \
               "<p>&nbsp;</p>" \
               "<p>&nbsp;</p>" \
               "<p>Por favor tome las medidas necesarias con estos reactivos antes de su vencimiento.</p>" \
               "<p><br />Gracias,<br /><br />Organilab: Notificaci&oacute;n de reactivos por vencer</p>" \
               "<p>&nbsp;</p>" \
               "<p>&nbsp;</p>"

        model.objects.create(
            code='Expiring reactives',
            subject='Expiring reactives - {{ laboratory.name }}',
            message=temp
        )

class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0170_alter_organizationstructure_options"),
    ]

    operations = [
        migrations.RunPython(create_expiration_template,
                             reverse_code=migrations.RunPython.noop),

    ]
