# Generated by Django 5.2.8 on 2026-02-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0169_merge_20260206_1140"),
        ("laboratory", "0171_auto_20260209_0837"),
    ]

    operations = []
