# Generated by Django 5.2.8 on 2026-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0172_merge_20260209_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="legal_identity",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Legal Identity"
            ),
        ),
    ]
