# Generated by Django 5.2.11 on 2026-02-11 23:05

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations


def create_shelfobject_flashpoint(apps, schema_editor):
    Catalog = apps.get_model("laboratory", "Catalog")
    flashpoints = [
        "Gas Inflamable Cat12",
        "Sobre Punto Ebullicion",
        "Normal",
        "Elevada",
    ]
    for flashpoint in flashpoints:
        Catalog.objects.get_or_create(
            key="process_condition",
            description=flashpoint,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0173_alter_provider_legal_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="flashpoint",
            field=laboratory.catalog.GTForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="flashpoint",
                to="laboratory.catalog",
                verbose_name="Flashpoint",
            ),
        ),
        migrations.RunPython(
            create_shelfobject_flashpoint, reverse_code=migrations.RunPython.noop
        ),
    ]
