# Generated by Django 5.2.11 on 2026-02-12 17:50

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0174_shelfobject_flashpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelfobject",
            name="flashpoint",
            field=laboratory.catalog.GTForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="process_condition_shelfobject",
                to="laboratory.catalog",
                verbose_name="Process Condition",
            ),
        ),
    ]
