# Generated by Django 5.2.11 on 2026-02-18 20:35

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0175_alter_shelfobject_flashpoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shelfobject",
            old_name="flashpoint",
            new_name="process_condition",
        ),
        migrations.AddField(
            model_name="objectmaximumlimit",
            name="process_condition",
            field=laboratory.catalog.GTForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="process_condition_object_maximum",
                to="laboratory.catalog",
                verbose_name="Process Condition",
            ),
        ),
    ]
