# Generated by Django 5.2.11 on 2026-02-18 22:57

from django.db import migrations


def create_unit_tons(apps, schema_editor):
    Catalog = apps.get_model("laboratory", "Catalog")
    Catalog.objects.get_or_create(
        key="units",
        description="Toneladas",
    )


def remove_process_condition(apps, schema_editor):
    Catalog = apps.get_model("laboratory", "Catalog")
    cat = Catalog.objects.filter(
        key="process_condition",
        description__in=[
            "Gas Inflamable Cat12",
            "Sobre Punto Ebullicion",
            "Normal",
            "Elevada",
        ],
    )
    ShelfObject = apps.get_model("laboratory", "ShelfObject")
    ShelfObject.objects.filter(process_condition__in=cat).update(process_condition=None)
    cat.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0176_rename_flashpoint_shelfobject_process_condition_and_more"),
    ]

    operations = [
        migrations.RunPython(create_unit_tons, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            remove_process_condition, reverse_code=migrations.RunPython.noop
        ),
    ]
