# Generated by Django 5.2.11 on 2026-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0178_temporaluploadreactive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Code"
            ),
        ),
    ]
