# Generated by Django 5.2.11 on 2026-03-12 01:24

import django.db.models.deletion
import laboratory.models_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0179_alter_object_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='informscheduler',
            name='close_application_date',
            field=models.DateField(verbose_name='Close application date'),
        ),
        migrations.AlterField(
            model_name='informscheduler',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='informscheduler',
            name='period_on_days',
            field=models.IntegerField(default=365, verbose_name='Period on days'),
        ),
        migrations.AlterField(
            model_name='informscheduler',
            name='start_application_date',
            field=models.DateField(verbose_name='Start application date'),
        ),
        migrations.CreateModel(
            name='SDSTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('merck', 'Merck/Sigma-Aldrich'), ('pubchem', 'PubChem'), ('fisher', 'Fisher/Thermo'), ('panreac', 'Panreac'), ('carlo_erba', 'Carlo Erba'), ('jt_baker', 'JT Baker'), ('honeywell', 'Honeywell/Fluka'), ('unknown', 'Unknown'), ('manual', 'Manual upload')], default='unknown', max_length=50, verbose_name='SDS source')),
                ('revision_date', models.DateField(blank=True, null=True, verbose_name='SDS revision date')),
                ('download_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Download URL')),
                ('security_sheet', models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Security sheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sustance_characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds_traceability', to='laboratory.sustancecharacteristics')),
            ],
            options={
                'verbose_name': 'SDS traceability',
                'verbose_name_plural': 'SDS traceability records',
                'ordering': ['-creation_date'],
            },
        ),
    ]
