# Generated by Django 5.2.11 on 2026-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0181_register_update_sds_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informscheduler",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
