# Generated by Django 5.2.11 on 2026-03-31 17:57

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0182_alter_informscheduler_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="informscheduler",
            name="laboratories",
            field=models.ManyToManyField(
                blank=True, to="laboratory.laboratory", verbose_name="Laboratories"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="geolocation",
            field=location_field.models.plain.PlainLocationField(
                default="9.895804362670006,-84.1552734375",
                max_length=63,
                verbose_name="Geolocation",
            ),
        ),
    ]
