# Generated by Django 5.2.11 on 2026-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0183_informscheduler_laboratories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="is_box",
            field=models.BooleanField(default=False, verbose_name="Is box?"),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="description",
            field=models.CharField(max_length=500, verbose_name="Description"),
        ),
    ]
