# Generated by Django 5.2.11 on 2026-04-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0184_shelfobject_is_box_alter_catalog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="quantity_units",
            field=models.FloatField(
                default=0,
                help_text="Number of units per box",
                verbose_name="Quantity Units per box",
            ),
        ),
    ]
