# Generated by Django 5.2.11 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0185_shelfobject_quantity_units"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE laboratory_shelfobject
                ALTER COLUMN quantity_units TYPE jsonb
                USING CASE
                    WHEN quantity_units = 0 THEN '[]'::jsonb
                    ELSE json_build_array(quantity_units::integer)::jsonb
                END;
            """,
            reverse_sql="""
                ALTER TABLE laboratory_shelfobject
                ALTER COLUMN quantity_units TYPE double precision
                USING COALESCE((quantity_units->0)::text::double precision, 0);
            """,
        ),
        migrations.AlterField(
            model_name="shelfobject",
            name="quantity_units",
            field=models.JSONField(
                default=list,
                help_text="List of unit quantities indexed by box position",
                verbose_name="Units per box",
            ),
        ),
    ]
