# Generated by Django 5.2.11 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0186_shelfobject_quantity_units_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="quantity_box",
            field=models.IntegerField(
                default=1,
                help_text="Number of box",
                verbose_name="Quantity Box",
            ),
        ),
    ]