# Generated by Django 5.2.11 on 2026-04-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0187_shelfobject_quantity_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelfobject",
            name="quantity_box",
            field=models.IntegerField(default=1, verbose_name="Quantity Box"),
        ),
        migrations.AlterField(
            model_name="shelfobject",
            name="quantity_units",
            field=models.JSONField(
                default=list,
                help_text="List of integer unit quantities indexed by box position",
                verbose_name="Units per box",
            ),
        ),
    ]
