# Generated by Django 5.2.11 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0188_alter_shelfobject_quantity_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="units_per_box",
            field=models.IntegerField(
                default=0,
                help_text="Original number of units per box at creation time",
                verbose_name="Units per box (reference)",
            ),
        ),
        migrations.RemoveField(
            model_name="shelfobject",
            name="quantity_box",
        ),
    ]