# Generated by Django 5.2.11 on 2026-04-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0190_alter_shelfobject_quantity_units_to_dicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectlogchange",
            name="is_box",
            field=models.BooleanField(default=False),
        ),
    ]
