# Generated by Django 5.2.11 on 2026-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0191_objectlogchange_is_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="tranferobject",
            name="is_box",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tranferobject",
            name="quantity_box",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tranferobject",
            name="quantity_units",
            field=models.JSONField(default=list),
        ),
    ]
