# Generated by Django 5.2.11 on 2026-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0192_tranferobject_is_box_tranferobject_quantity_box_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectlogchange",
            name="note",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
