# Generated by Django 5.2.11 on 2026-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0193_alter_objectlogchange_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectlogchange",
            name="subject",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
