# Generated by Django 5.2.11 on 2026-04-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0194_alter_objectlogchange_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sdstraceability",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is verified"),
        ),
        migrations.AddField(
            model_name="sdstraceability",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sds_verified_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified by",
            ),
        ),
        migrations.AddField(
            model_name="sdstraceability",
            name="verified_date",
            field=models.DateField(blank=True, null=True, verbose_name="Verified date"),
        ),
    ]
