# Generated by Django 5.2.11 on 2026-05-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0195_sdstraceability_is_verified_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                SELECT setval(
                    pg_get_serial_sequence('laboratory_sdstraceability', 'id'),
                    COALESCE((SELECT MAX(id) FROM laboratory_sdstraceability), 1)
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
