# Generated by Django 5.2.11 on 2026-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0196_auto_20260512_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="threshold",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="It belongs to the regulations of decree 44741",
                null=True,
                verbose_name="Threshold",
            ),
        ),
    ]
