# Generated by Django 5.2.11 on 2026-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0197_alter_object_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationstructure",
            name="enable_child_organizations",
            field=models.BooleanField(default=False),
        ),
    ]
