# Generated by Django 5.2.11 on 2026-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0198_organizationstructure_enable_child_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelfobject",
            name="shelfobject_code",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Unit code"
            ),
        ),
    ]
