# Generated by Django 5.2.11 on 2026-06-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0199_shelfobject_shelfobject_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shelfobject",
            options={
                "ordering": ["pk", "object__name"],
                "permissions": [
                    ("can_view_contract", "Can view contract"),
                    ("can_view_process_condition", "Can view process condition"),
                ],
                "verbose_name": "Shelf object",
                "verbose_name_plural": "Shelf objects",
            },
        ),
    ]
