# Generated by Django 5.2.11 on 2026-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0199_shelfobject_shelfobject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfobject',
            options={'ordering': ['pk', 'object__name'], 'permissions': [('can_view_contract', 'Can view contract'), ('can_view_process_condition', 'Can view process condition'), ('can_manage_reorder', 'Can manage reactive consumption reorder')], 'verbose_name': 'Shelf object', 'verbose_name_plural': 'Shelf objects'},
        ),
    ]
