# Generated by Django 5.2.11 on 2026-06-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0200_add_can_manage_reorder_permission"),
        ("laboratory", "0200_alter_shelfobject_options"),
    ]

    operations = []
