# Generated by Django 5.2.11 on 2026-06-23 20:24

import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0200_add_can_manage_reorder_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrOrgRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('org', 'Organization'), ('lab', 'Laboratory')], max_length=3, verbose_name='Entity type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=25, verbose_name='Phone')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('geolocation', location_field.models.plain.PlainLocationField(blank=True, default='9.895804362670006,-84.1552734375', max_length=63, null=True, verbose_name='Geolocation')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('coordinator', models.CharField(blank=True, max_length=255, verbose_name='Coordinator')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('area', models.FloatField(default=0.0, verbose_name='Area')),
                ('faculty_dispatch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Faculty or dispatch')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('level', models.SmallIntegerField(default=0, verbose_name='Level')),
                ('enable_child_organizations', models.BooleanField(default=False, verbose_name='Enable child organizations')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review notes')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='laboratory.organizationstructure', verbose_name='Parent organization')),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_org_requests', to='laboratory.organizationstructure', verbose_name='Parent organization (for org)')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_org_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Lab or organization request',
                'verbose_name_plural': 'Lab or organization requests',
                'ordering': ['-requested_at'],
                'permissions': [('can_approve_labororgrequest', 'Can approve lab or organization request')],
            },
        ),
    ]
