# Generated by Django 5.2.11 on 2026-06-23 23:21

import django.db.models.deletion
import laboratory.models_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0201_add_labororgrequest_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labororgrequest',
            name='enable_child_organizations',
        ),
        migrations.RemoveField(
            model_name='labororgrequest',
            name='level',
        ),
        migrations.RemoveField(
            model_name='labororgrequest',
            name='position',
        ),
        migrations.AddField(
            model_name='labororgrequest',
            name='nearby_sites',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Nearby sites'),
        ),
        migrations.AddField(
            model_name='labororgrequest',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_lab_requests', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='labororgrequest',
            name='water_resources_affected',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Water resources affected'),
        ),
        migrations.AddField(
            model_name='labororgrequest',
            name='workplace',
            field=models.ManyToManyField(blank=True, related_name='lab_requests_workplace', to='laboratory.organizationstructure', verbose_name='Workplace'),
        ),
    ]
