# Generated by Django 5.2.11 on 2026-06-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0201_merge_20260623_1001"),
        ("laboratory", "0205_fix_labororgrequest_email_subject_template"),
    ]

    operations = []
