# Generated by Django 5.2.11 on 2026-07-31 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0209_migrate_sustancecharacteristics_to_sga"),
        ("sga", "0089_substancecharacteristics_img_representation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdstraceability",
            name="sga_substance_characteristics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sds_traceability",
                to="sga.substancecharacteristics",
            ),
        ),
        migrations.AlterField(
            model_name="sdstraceability",
            name="sustance_characteristics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sds_traceability",
                to="laboratory.sustancecharacteristics",
            ),
        ),
    ]
