# Generated by Django 5.2.11 on 2026-07-31 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0211_migrate_sdstraceability_to_sga"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sdstraceability",
            name="sustance_characteristics",
        ),
    ]
