# Generated by Django 5.2.11 on 2026-08-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0215_move_sdstraceability_to_sga'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfObjectCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Counter')),
            ],
            options={
                'verbose_name': 'Shelf object code counter',
                'verbose_name_plural': 'Shelf object code counters',
            },
        ),
        migrations.AddField(
            model_name='laboratory',
            name='code',
            field=models.CharField(blank=True, help_text='Three-letter code used in substance codes', max_length=3, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='code',
            field=models.CharField(blank=True, help_text='Three-letter code used in substance codes', max_length=3, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='shelfobject',
            name='shelfobject_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit code'),
        ),
    ]
