# Generated by Django 5.2.11 on 2026-08-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0216_shelfobjectcodecounter_laboratory_code_and_more'),
        ('sga', '0094_substancelaboratory_alter_substance_laboratories'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfobjectcodecounter',
            name='substance_laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_counters', to='sga.substancelaboratory', verbose_name='Substance laboratory'),
        ),
        migrations.AlterUniqueTogether(
            name='shelfobjectcodecounter',
            unique_together={('substance_laboratory', 'year', 'month')},
        ),
    ]
