# Generated by Django 5.2.11 on 2026-08-29 21:20

import djgentelella.fields.maps
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0219_move_email_templates_to_djgentelella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='geolocation',
            field=djgentelella.fields.maps.GTPointField(default='9.895804362670006,-84.1552734375', verbose_name='Geolocation', zoom=15),
        ),
        migrations.AlterField(
            model_name='labororgrequest',
            name='geolocation',
            field=djgentelella.fields.maps.GTPointField(blank=True, default='9.895804362670006,-84.1552734375', null=True, verbose_name='Geolocation', zoom=15),
        ),
    ]
