# Generated by Django 5.2.11 on 2026-08-30 01:54

from django.db import migrations


def copy_to_historyrelation(apps, schema_editor):
    """LabOrgLogEntry -> djgentelella.HistoryRelation, 1:1.

    Mismo esquema (FK a LogEntry + GenericFK); el campo data queda NULL.
    """
    LabOrgLogEntry = apps.get_model('laboratory', 'LabOrgLogEntry')
    HistoryRelation = apps.get_model('djgentelella', 'HistoryRelation')
    batch = []
    for row in LabOrgLogEntry.objects.all().iterator(chunk_size=2000):
        batch.append(
            HistoryRelation(
                log_entry_id=row.log_entry_id,
                content_type_id=row.content_type_id,
                object_id=row.object_id,
            )
        )
        if len(batch) >= 2000:
            HistoryRelation.objects.bulk_create(batch)
            batch = []
    if batch:
        HistoryRelation.objects.bulk_create(batch)


def restore_from_historyrelation(apps, schema_editor):
    """Reverso: las filas con GenericFK completo vuelven al modelo viejo."""
    LabOrgLogEntry = apps.get_model('laboratory', 'LabOrgLogEntry')
    HistoryRelation = apps.get_model('djgentelella', 'HistoryRelation')
    rows = HistoryRelation.objects.filter(
        content_type__isnull=False, object_id__isnull=False
    )
    LabOrgLogEntry.objects.bulk_create(
        LabOrgLogEntry(
            log_entry_id=row.log_entry_id,
            content_type_id=row.content_type_id,
            object_id=row.object_id,
        )
        for row in rows.iterator(chunk_size=2000)
    )
    rows.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0220_alter_laboratory_geolocation_and_more'),
        ('djgentelella', '0019_historyrelation'),
    ]

    operations = [
        migrations.RunPython(
            copy_to_historyrelation, restore_from_historyrelation
        ),
        migrations.DeleteModel(
            name='LabOrgLogEntry',
        ),
    ]
