# Generated by Django 5.2.11 on 2026-08-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0221_delete_laborglogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
