# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255, verbose_name='Advertisement Description')),
                ('published_date', models.DateField(auto_now=True, verbose_name='Published Date')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=15, verbose_name='Phone')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_size', models.CharField(choices=[('mm', 'Milimeters'), ('cm', 'Centimeters'), ('inch', 'inch')], default='mm', max_length=5, verbose_name='Unit Size')),
                ('widthSize', models.FloatField(verbose_name='Width Size')),
                ('longSize', models.FloatField(verbose_name='Long Size')),
                ('name', models.TextField(default='', max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', max_length=255, verbose_name='Description')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Paper Type',
                'verbose_name_plural': 'Paper Types',
            },
        ),
        migrations.CreateModel(
            name='PrintObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('location', models.TextField(default='', max_length=255, verbose_name='Location')),
                ('geolocation', location_field.models.plain.PlainLocationField(max_length=63)),
                ('name', models.TextField(default='', max_length=255, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='print_logos/', verbose_name='Logo')),
                ('qualification', models.SmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Good'), (4, 'Very Good'), (5, 'Excelent')], verbose_name='Qualification')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='Creation Date')),
                ('state', models.TextField(default='', max_length=255, verbose_name='State')),
                ('description', models.TextField(default='', max_length=255, verbose_name='Description')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='printOrderManager.Advertisement')),
                ('contacts', models.ManyToManyField(to='printOrderManager.Contact', verbose_name='Contacts')),
                ('paperType', models.ManyToManyField(to='printOrderManager.PaperType', verbose_name='Paper Types')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsible User')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Print',
                'verbose_name_plural': 'Printers',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('closeTime', models.TimeField(verbose_name='Close Time')),
                ('startDay', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=25, verbose_name='Start Day')),
                ('closeDay', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='fri', max_length=25, verbose_name='Close Day')),
                ('description', models.TextField(default='Normal Schedule', max_length=255, verbose_name='Schedule Description')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AddField(
            model_name='printobject',
            name='schedules',
            field=models.ManyToManyField(to='printOrderManager.Schedule', verbose_name='Schedules'),
        ),
    ]
