# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 17:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0002_auto_20180927_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printobject',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+55577777777'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
    ]
