# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 18:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0003_auto_20180927_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printobject',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='print_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])], verbose_name='Logo'),
        ),
    ]
