# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0007_auto_20181012_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printobject',
            options={'ordering': ('pk',), 'permissions': (('changeInformation_printObject', 'Can edit the print information'), ('changeContacts_printObject', 'Can edit the print contacts'), ('changePaper_printObject', 'Can edit the print paper types'), ('changeSchedules_printObject', 'Can edit the print schedules'), ('changeAdvertisements_printObject', 'Can edit the print advertisements')), 'verbose_name': 'Print', 'verbose_name_plural': 'Printers'},
        ),
    ]
