# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printOrderManager', '0008_auto_20181012_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLabelPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Preparing'), (2, 'Done'), (3, 'Rejected'), (4, 'Delivered')], default=0)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printOrderManager.PrintObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
