# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0009_requestlabelprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.TextField(default='Enabled', max_length=255, verbose_name='State'),
        ),
    ]
