# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0010_contact_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertype',
            name='available',
            field=models.TextField(default='Available', max_length=255, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='papertype',
            name='grams',
            field=models.FloatField(default=0.0, verbose_name='Grams'),
            preserve_default=False,
        ),
    ]
