# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0011_auto_20181031_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.TextField(default='Normal Schedule', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Schedule Description'),
        ),
    ]
