# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0012_auto_20181101_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Schedule Description'),
        ),
    ]
