# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0014_auto_20181102_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='closeDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Friday', max_length=50, verbose_name='Close Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=50, verbose_name='Start Day'),
        ),
    ]
