# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printOrderManager', '0015_auto_20181102_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printobject',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='createdBy',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='state',
            field=models.TextField(default='Enabled', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='typeOfAdvertisement',
            field=models.TextField(default='Default', max_length=255, verbose_name='Type of advertisement'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='usersNotified',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users Notified'),
        ),
        migrations.AddField(
            model_name='printobject',
            name='advertisements',
            field=models.ManyToManyField(to='printOrderManager.Advertisement', verbose_name='Advertisements'),
        ),
    ]
