# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0016_auto_20181102_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.TextField(default='Advertisement', max_length=255, verbose_name='Title'),
        ),
    ]
