# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printOrderManager', '0017_advertisement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
