# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printOrderManager', '0018_auto_20181102_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='typeOfAdvertisement',
            field=models.TextField(default='Information', max_length=255, verbose_name='Type of advertisement'),
        ),
    ]
