# Generated by Django 2.0.3 on 2018-08-19 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.TextField(max_length=15)),
                ('address', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Information of Builders',
                'permissions': (('view_builderinformation', 'Can see available Builder Information'),),
                'verbose_name': 'Builder Information',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Components',
                'permissions': (('view_component', 'Can see available Component'),),
                'verbose_name': 'Component',
            },
        ),
        migrations.CreateModel(
            name='DangerIndication',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Indication of Danger',
                'permissions': (('view_dangerindication', 'Can see available indication of danger'),),
                'verbose_name': 'Danger Indication',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField(choices=[(0, 'default')])),
                ('builderInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.BuilderInformation')),
            ],
            options={
                'verbose_name_plural': 'Labels',
                'permissions': (('view_label', 'Can see available labels'),),
                'verbose_name': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Pictograms',
                'permissions': (('view_pictogram', 'Can see available pictograms'),),
                'verbose_name': 'Pictogram',
            },
        ),
        migrations.CreateModel(
            name='Sustance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercial_name', models.CharField(max_length=250)),
                ('cas_number', models.CharField(max_length=150)),
                ('components', models.ManyToManyField(to='sga.Component')),
                ('danger_indications', models.ManyToManyField(to='sga.DangerIndication')),
            ],
            options={
                'verbose_name_plural': 'Sustances',
                'permissions': (('view_sustance', 'Can see available Sustance'),),
                'verbose_name': 'Sustance',
            },
        ),
        migrations.CreateModel(
            name='WarningClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.SmallIntegerField(choices=[(0, 'Physic warning'), (1, 'Healty warning'), (2, 'Environment warning')])),
            ],
            options={
                'verbose_name_plural': 'Warning Classes',
                'permissions': (('view_warningclass', 'Can see available Warning Classes'),),
                'verbose_name': 'Warning Class',
            },
        ),
        migrations.CreateModel(
            name='WarningWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weigth', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Warning Words',
                'permissions': (('view_warningword', 'Can see available Warning Words'),),
                'verbose_name': 'Warning Word',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='sustance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.Sustance'),
        ),
        migrations.AddField(
            model_name='dangerindication',
            name='pictograms',
            field=models.ManyToManyField(to='sga.Pictogram'),
        ),
        migrations.AddField(
            model_name='dangerindication',
            name='warning_class',
            field=models.ManyToManyField(to='sga.WarningClass'),
        ),
        migrations.AddField(
            model_name='dangerindication',
            name='warning_words',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.WarningWord'),
        ),
    ]
