# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0014_sustance_agrochemical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustance',
            name='agrochemical',
            field=models.BooleanField(default=False, verbose_name='Agrochemical'),
        ),
    ]
