# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0024_laboratory_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureObservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureRequiredObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Material quantity')),
                ('measurement_unit', models.CharField(choices=[('0', 'Meters'), ('1', 'Milimeters'), ('2', 'Centimeters'), ('3', 'Liters'), ('4', 'Mililiters'), ('5', 'Unit')], max_length=2, verbose_name='Measurement unit')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Procedure')),
            ],
        ),
        migrations.AddField(
            model_name='procedurerequiredobject',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ProcedureStep'),
        ),
        migrations.AddField(
            model_name='procedureobservations',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ProcedureStep'),
        ),
    ]
