# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:50
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ('pk',), 'permissions': (('view_procedure', 'Can see available Procedure'),)},
        ),
        migrations.AlterModelOptions(
            name='procedureobservations',
            options={'ordering': ('pk',), 'permissions': (('view_procedureobservations', 'Can see available ProcedureObservations'),)},
        ),
        migrations.AlterModelOptions(
            name='procedurerequiredobject',
            options={'ordering': ('pk',), 'permissions': (('view_procedurerequiredobject', 'Can see available ProcedureRequiredObject'),)},
        ),
        migrations.AlterModelOptions(
            name='procedurestep',
            options={'ordering': ('pk',), 'permissions': (('view_procedurestep', 'Can see available ProcedureStep'),)},
        ),
    ]
