# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20170508_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ('pk',), 'permissions': (('view_procedure', 'Can see available Procedure'),), 'verbose_name': 'Procedure', 'verbose_name_plural': 'Procedures'},
        ),
        migrations.AlterModelOptions(
            name='procedureobservations',
            options={'ordering': ('pk',), 'permissions': (('view_procedureobservations', 'Can see available ProcedureObservations'),), 'verbose_name': 'Procedure Observation', 'verbose_name_plural': 'Procedure Observations'},
        ),
        migrations.AlterModelOptions(
            name='procedurerequiredobject',
            options={'ordering': ('pk',), 'permissions': (('view_procedurerequiredobject', 'Can see available ProcedureRequiredObject'),), 'verbose_name': 'Procedure Required Object', 'verbose_name_plural': 'Procedure Required Objects'},
        ),
        migrations.AlterModelOptions(
            name='procedurestep',
            options={'ordering': ('pk',), 'permissions': (('view_procedurestep', 'Can see available ProcedureStep'),), 'verbose_name': 'Procedure step', 'verbose_name_plural': 'Procedure steps'},
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Procedure', verbose_name='Procedure'),
        ),
    ]
