# Generated by Django 2.2.12 on 2020-05-26 01:16

from django.db import migrations
import django.db.models.deletion
import laboratory.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20200302_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ('pk',), 'verbose_name': 'Procedure', 'verbose_name_plural': 'Procedures'},
        ),
        migrations.AlterModelOptions(
            name='procedureobservations',
            options={'ordering': ('pk',), 'verbose_name': 'Procedure Observation', 'verbose_name_plural': 'Procedure Observations'},
        ),
        migrations.AlterModelOptions(
            name='procedurerequiredobject',
            options={'ordering': ('pk',), 'verbose_name': 'Procedure Required Object', 'verbose_name_plural': 'Procedure Required Objects'},
        ),
        migrations.AlterModelOptions(
            name='procedurestep',
            options={'ordering': ('pk',), 'verbose_name': 'Procedure step', 'verbose_name_plural': 'Procedure steps'},
        ),
        migrations.AlterField(
            model_name='procedurerequiredobject',
            name='measurement_unit',
            field=laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.Catalog', verbose_name='Measurement unit'),
        ),
    ]
