# Generated by Django 3.2 on 2022-09-14 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sga', '0020_merge_20220913_2302'),
        ('academic', '0007_componentsga_substancesga_sustancecharacteristicssga'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.substance')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
            },
        ),
    ]
