# Generated by Django 4.1.2 on 2022-10-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_substanceobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancesga',
            name='synonymous',
            field=models.TextField(verbose_name='Synonymous'),
        ),
    ]
