# Generated by Django 4.0.8 on 2022-10-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_substancesga_synonymous'),
    ]

    operations = [
        migrations.RunSQL("""
BEGIN;
SELECT setval(pg_get_serial_sequence('"academic_procedure"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_procedure";
SELECT setval(pg_get_serial_sequence('"academic_procedurestep"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_procedurestep";
SELECT setval(pg_get_serial_sequence('"academic_procedurerequiredobject"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_procedurerequiredobject";
SELECT setval(pg_get_serial_sequence('"academic_procedureobservations"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_procedureobservations";
SELECT setval(pg_get_serial_sequence('"academic_componentsga"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_componentsga";
SELECT setval(pg_get_serial_sequence('"academic_substancesga_components"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_substancesga_components";
SELECT setval(pg_get_serial_sequence('"academic_substancesga"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_substancesga";
SELECT setval(pg_get_serial_sequence('"academic_sustancecharacteristicssga_white_organ"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_sustancecharacteristicssga_white_organ";
SELECT setval(pg_get_serial_sequence('"academic_sustancecharacteristicssga_h_code"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_sustancecharacteristicssga_h_code";
SELECT setval(pg_get_serial_sequence('"academic_sustancecharacteristicssga_ue_code"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_sustancecharacteristicssga_ue_code";
SELECT setval(pg_get_serial_sequence('"academic_sustancecharacteristicssga_nfpa"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_sustancecharacteristicssga_nfpa";
SELECT setval(pg_get_serial_sequence('"academic_sustancecharacteristicssga_storage_class"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_sustancecharacteristicssga_storage_class";
SELECT setval(pg_get_serial_sequence('"academic_sustancecharacteristicssga"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_sustancecharacteristicssga";
SELECT setval(pg_get_serial_sequence('"academic_substanceobservation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "academic_substanceobservation";
COMMIT; """)
    ]
