# Generated by Django 4.1.9 on 2023-05-18 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0104_shelfobjectlimits_expiration_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0011_procedure_content_type_procedure_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Eraser', 'Eraser'), ('In Review', 'In Review'), ('Finalized', 'Finalized')], default='Eraser', max_length=20)),
                ('schema', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.procedure', verbose_name='Template')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
            ],
        ),
        migrations.AddIndex(
            model_name='myprocedure',
            index=models.Index(fields=['content_type', 'object_id'], name='academic_my_content_f2b0ec_idx'),
        ),
    ]
