# Generated by Django 4.0.8 on 2023-06-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_myprocedure_commentprocedurestep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substanceobservation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='substanceobservation',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='substancesga',
            name='components',
        ),
        migrations.RemoveField(
            model_name='substancesga',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='h_code',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='iarc',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='imdg',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='nfpa',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='precursor_type',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='storage_class',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='ue_code',
        ),
        migrations.RemoveField(
            model_name='sustancecharacteristicssga',
            name='white_organ',
        ),
        migrations.DeleteModel(
            name='ComponentSGA',
        ),
        migrations.DeleteModel(
            name='SubstanceObservation',
        ),
        migrations.DeleteModel(
            name='SubstanceSGA',
        ),
        migrations.DeleteModel(
            name='SustanceCharacteristicsSGA',
        ),
    ]
