# Generated by Django 4.1.9 on 2023-05-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_commentprocedurestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentprocedurestep',
            name='my_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.myprocedure', verbose_name='My procedure'),
        ),
    ]
