# Generated by Django 4.0.8 on 2023-06-20 22:22
from django.db import migrations

def set_procedure_content_type(apps, schema_editor):
    Procedure = apps.get_model('academic','Procedure')
    Laboratory = apps.get_model('laboratory','Laboratory')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    org_contenttype = ContentType.objects.filter(app_label='laboratory',
                                                 model='organizationstructure').first()
    lab_contenttype = ContentType.objects.filter(app_label='laboratory',
                                                 model='laboratory').first()

    procedures = Procedure.objects.filter(content_type=lab_contenttype)
    for procedure in procedures:
        lab = Laboratory.objects.filter(pk=procedure.object_id).first()
        if lab:
            procedure.content_type = org_contenttype
            procedure.object_id = lab.organization.id
            procedure.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_substanceobservation_creator_and_more'),
    ]

    operations = [
        migrations.RunPython(set_procedure_content_type,
                             reverse_code=migrations.RunPython.noop),

    ]
