# Generated by Django 5.2.11 on 2026-03-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic",
            "0016_alter_commentprocedurestep_id_alter_myprocedure_id_and_more",
        ),
        ("derb", "0003_alter_customform_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurestep",
            name="form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="derb.customform",
            ),
        ),
    ]
