# Generated by Django 5.2.11 on 2026-08-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_procedurestep_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
