
def create_catalog(Catalog):
    list_catalog = [
        ('IARC', 'Grupo 1: Carcinógeno para el ser humano'),
        ('IARC', 'Grupo 2A: Probablemente carcinógeno para el ser humano'),
        ('IARC', 'Grupo 2B: : Posiblemente carcinógeno para el ser humano'),
        ('IARC', 'Grupo 3: No clasificable en cuanto a su carcinogenicidad para seres humanos'),
        ('white_organ', 'Aparato digestivo'),
        ('white_organ', 'Aparato reproductor masculino'),
        ('white_organ', 'Articulaciones'),
        ('white_organ', 'Bazo'),
        ('white_organ', 'Bronquios'),
        ('white_organ', 'Cardiovascular (corazón y vasos sanguíneos)'),
        ('white_organ', 'Células germinales masculinas'),
        ('white_organ', 'Células sanguíneas'),
        ('white_organ', 'Cerebro'),
        ('white_organ', 'Corazón'),
        ('white_organ', 'Córnea'),
        ('white_organ', 'Daño al feto'),
        ('white_organ', 'Dientes'),
        ('white_organ', 'Estómago'),
        ('white_organ', 'Garganta'),
        ('white_organ', 'Glándula Timo'),
        ('white_organ', 'Glándulas suprarrenales'),
        ('white_organ', 'Glándulas y hormonas'),
        ('white_organ', 'Hígado'),
        ('white_organ', 'Huesos'),
        ('white_organ', 'Inhibidor de colinesterasa'),
        ('white_organ', 'Intestinos'),
        ('white_organ', 'Médula ósea '),
        ('white_organ', 'Membranas mucosas'),
        ('white_organ', 'Músculo'),
        ('white_organ', 'Nariz'),
        ('white_organ', 'Nervio craneal'),
        ('white_organ', 'No se tienen datos'),
        ('white_organ', 'Ojos'),
        ('white_organ', 'Órganos auditivos'),
        ('white_organ', 'Páncreas'),
        ('white_organ', 'Piel'),
        ('white_organ', 'Pulmón'),
        ('white_organ', 'Riñón'),
        ('white_organ', 'Sangre'),
        ('white_organ', 'Sangre (metahemoglobina)'),
        ('white_organ', 'Se sospecha que es tóxico para la reproducción'),
        ('white_organ', 'Sensibilizante de la piel'),
        ('white_organ', 'Sistema cardiovascular'),
        ('white_organ', 'Sistema gastrointestinal'),
        ('white_organ', 'Sistema inmune'),
        ('white_organ', 'sistema nervioso'),
        ('white_organ', 'Sistema nervioso central'),
        ('white_organ', 'Sistema nervioso periférico'),
        ('white_organ', 'Sistema reproductivo'),
        ('white_organ', 'sistema reproductor masculino'),
        ('white_organ', 'Sistema respiratorio'),
        ('white_organ', 'Sistema urinario'),
        ('white_organ', 'Tiroides'),
        ('white_organ', 'Tracto gastrointestinal'),
        ('white_organ', 'Uñas'),
        ('white_organ', 'Vejiga'),
        ('white_organ', 'Vías respiratorias superiores'),
        ('white_organ', 'Otro'),
        ('units', 'Metros'),
        ('units', 'Milímetros'),
        ('units', 'Centímetros'),
        ('units', 'Litros'),
        ('units', 'Mililitros'),
        ('units', 'Unidades'),
        ('units', 'Gramos'),
        ('units', 'Kilogramos'),
        ('units', 'Miligramos'),
        ('units', 'Metro cúbico'),
        ('units', 'Atmósfera'),
        ('units', 'Pascales'),
        ('units', 'PSI'),
        ('container_type', 'Espacio'),
        ('container_type', 'Gaveta'),
        ('furniture_type', 'Cajón'),
        ('furniture_type', 'Estante'),
        ('IDMG', 'Explosivo'),
        ('IDMG', 'Gases'),
        ('IDMG', 'Líquidos inflamables'),
        ('IDMG', 'Solidos inflamables'),
        ('IDMG', 'Sustancias oxidantes y peróxidos orgánicos'),
        ('IDMG', 'Sustancias tóxicas e infecciosas'),
        ('IDMG', 'Material radioactivo'),
        ('IDMG', 'Sustancias corrosivas'),
        ('IDMG', 'Sustancias y artículos peligrosos diversos'),

    ]
    for key, description in list_catalog:
        list_catalog.append(Catalog(key=key, description=description))

    Catalog.objects.bulk_create(list_catalog)