# Generated by Django 5.1 on 2025-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derb', '0002_customform_created_by_customform_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='name',
            field=models.CharField(),
        ),
    ]
