# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 07:16
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('related_file', models.FileField(blank=True, upload_to='media/feedback_entries/', verbose_name='Related file')),
            ],
            options={
                'verbose_name_plural': 'Feedback entries',
                'permissions': (('view_feedbackentry', 'Can see available feed back entry'),),
                'verbose_name': 'Feedback entry',
            },
        ),
    ]
