# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 00:35
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='laboratory_id',
            field=models.IntegerField(default=0, null=True, verbose_name='Laboratory id'),
        ),
        migrations.AlterField(
            model_name='feedbackentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
