# Generated by Django 2.2.12 on 2020-06-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200525_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='First Name')),
                ('business_email', models.EmailField(max_length=70, verbose_name='Business Email Address')),
                ('company_name', models.CharField(max_length=120, verbose_name='Company Name')),
                ('country', models.CharField(max_length=120, verbose_name='Country Name')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
            },
        ),
    ]
