# Generated by Django 4.0.8 on 2022-12-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_demorequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoRequest',
        ),
        migrations.DeleteModel(
            name='FeedbackEntry',
        ),
    ]
