# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0046_auto_20200320_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('priority', models.SmallIntegerField(verbose_name='Priority')),
                ('num_workers', models.SmallIntegerField(verbose_name='Number of workers')),
                ('zone_type', models.SmallIntegerField(choices=[(1, 'Zona Residencial, Zona Comercial y de Servicios o Zona Mixta'), (2, 'Zona Industrial'), (3, 'Otras Zonas')], default=1, verbose_name='Zone type')),
                ('laboratories', models.ManyToManyField(to='laboratory.Laboratory', verbose_name='Laboratories')),
            ],
            options={
                'verbose_name': 'Risk zone',
                'verbose_name_plural': 'Risk zones',
                'ordering': ('zone_type', 'pk'),
            },
        ),
    ]
