# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import risk_management.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityConstrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('<', '<'), ('<=', '<='), ('=', '='), ('>', '>'), ('>=', '>='), ('!', '!'), ('<>', '<x>'), ('=<>=', '=<x>='), ('<>=', '<x>='), ('=<>', '=<x>')], max_length=5, verbose_name='Opertation')),
                ('left_value', models.IntegerField(help_text='left_value opertation X ej.  left_value > 100', verbose_name='Comparative value')),
                ('right_value', models.IntegerField(blank=True, help_text='Use only if =<x>=, <x>, <x>= or =<x>  ', null=True)),
                ('priority', models.IntegerField(default=1, help_text='Value result if operation is True', verbose_name='Set priority if true')),
            ],
            bases=(models.Model, risk_management.models_utils.PriorityCalculator),
        ),
        migrations.CreateModel(
            name='ZoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('priority_validator', models.ManyToManyField(to='risk_management.PriorityConstrain', verbose_name='Priority calculate operators')),
            ],
        ),
        migrations.AlterField(
            model_name='riskzone',
            name='num_workers',
            field=models.SmallIntegerField(verbose_name='Number of workers (aprox)'),
        ),
        migrations.AlterField(
            model_name='riskzone',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.ZoneType'),
        ),
    ]
