# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0046_auto_20200320_1838'),
        ('risk_management', '0002_auto_20200320_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.CharField(help_text='Descipción corta de evento, max 500 caracteres', max_length=500, verbose_name='Descipción corta')),
                ('incident_date', models.DateField(verbose_name='Fecha del incidente')),
                ('causes', models.TextField(verbose_name='Causas del accidente')),
                ('infraestructure_impact', models.TextField(help_text='Indicando las consecuencias a corto, mediano y largo plazo.', verbose_name='Impacto a la infraestructura')),
                ('people_impact', models.TextField(help_text='Indicando las consecuencias a corto, mediano y largo plazo.', verbose_name='Impacto a las personas (empleados, visitantes y comunidad afectada)')),
                ('environment_impact', models.TextField(help_text='Indicando las consecuencias a corto, mediano y largo plazo.', verbose_name='Impacto ambiental')),
                ('result_of_plans', models.TextField(verbose_name='Resultado de la implementación del Plan de Prevención, Preparación y Respuesta ante Accidentes Químicos.')),
                ('mitigation_actions', models.TextField(verbose_name='Medidas adoptadas para corregir la situación y para atenuar sus efectos.')),
                ('recomendations', models.TextField(help_text='Recomendaciones que describan en detalle las medidas que se vayan a llevar a cabo para reducir el riesgo de que accidentes similares vuelvan a producirse.', verbose_name='Recomendaciones')),
                ('notification_copy', models.FileField(blank=True, null=True, upload_to='notifications/', verbose_name='En caso de intoxicación adjuntar copia de la notificación realizada al Centro Nacional de Control de Intoxicaciones (CNCI)')),
                ('laboratories', models.ManyToManyField(to='laboratory.Laboratory', verbose_name='Laboratories')),
            ],
        ),
        migrations.AlterModelOptions(
            name='riskzone',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Risk zone', 'verbose_name_plural': 'Risk zones'},
        ),
        migrations.AlterField(
            model_name='priorityconstrain',
            name='operation',
            field=models.CharField(choices=[('<', '<'), ('<=', '<='), ('=', '='), ('>', '>'), ('>=', '>='), ('!', '!'), ('<>', '<X>'), ('=<>=', '=<X>='), ('<>=', '<X>='), ('=<>', '=<X>'), ('<<', '<X<'), ('=<<=', '=<X<='), ('<<=', '<X<='), ('=<<', '=<X<')], max_length=5, verbose_name='Opertation'),
        ),
    ]
