# Generated by Django 4.0.8 on 2022-10-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0003_auto_20200321_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzone',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.zonetype', verbose_name='Zone Type'),
        ),
    ]
