# Generated by Django 4.0.8 on 2022-10-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0004_alter_riskzone_zone_type'),
    ]

    operations = [
        migrations.RunSQL("""BEGIN;
SELECT setval(pg_get_serial_sequence('"risk_management_priorityconstrain"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_priorityconstrain";
SELECT setval(pg_get_serial_sequence('"risk_management_zonetype_priority_validator"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_zonetype_priority_validator";
SELECT setval(pg_get_serial_sequence('"risk_management_zonetype"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_zonetype";
SELECT setval(pg_get_serial_sequence('"risk_management_riskzone_laboratories"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_riskzone_laboratories";
SELECT setval(pg_get_serial_sequence('"risk_management_riskzone"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_riskzone";
SELECT setval(pg_get_serial_sequence('"risk_management_incidentreport_laboratories"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_incidentreport_laboratories";
SELECT setval(pg_get_serial_sequence('"risk_management_incidentreport"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "risk_management_incidentreport";
COMMIT;""")
    ]
