# Generated by Django 4.0.8 on 2022-12-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_incidentreport_created_by_incidentreport_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonetype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='zonetype',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='zonetype',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='zonetype',
            name='organization',
        ),
    ]
