# Generated by Django 4.0.8 on 2023-01-20 22:19

from django.db import migrations

def add_priority(apps, schema_editor):

    priority = apps.get_model('risk_management', 'PriorityConstrain')
    priorities = [{'operation':'<', 'left_value':100, 'priority':1},
                  {'operation': '<', 'left_value': 0, 'priority': 5},
                  {'operation': '<', 'left_value': 0, 'priority': 4},
                  {'operation': '=<<=', 'left_value': 100, 'right_value': 30, 'priority': 2},
                  {'operation': '>', 'left_value': 30,'priority': 3},
    ]
    for p in priorities:
        obj, created = priority.objects.get_or_create(**p)

class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0007_remove_zonetype_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(add_priority)
    ]
