# Generated by Django 5.1 on 2025-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "risk_management",
            "0011_remove_buildings_long_remove_buildings_width_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="buildings",
            field=models.ManyToManyField(
                blank=True,
                related_name="incident_buildings",
                to="risk_management.buildings",
                verbose_name="Buildings",
            ),
        ),
    ]
