# Generated by Django 5.1 on 2025-04-22 18:02

import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0012_incidentreport_buildings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildings',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='regent',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='buildings',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_management.buildings', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='geolocation',
            field=location_field.models.plain.PlainLocationField(default='9.895804362670006,-84.1552734375', max_length=63, verbose_name='Geolocation'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='structure_manager', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
    ]
