# Generated by Django 5.1 on 2025-04-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0014_incidentreport_buildings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='building',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='risk_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.riskzone', verbose_name='Risk Zone'),
        ),
    ]
