# Generated by Django 5.1 on 2025-04-25 15:53

import laboratory.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0015_remove_incidentreport_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='emergency_plan',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Emergency Plan'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='has_nearby_sites',
            field=models.FileField(blank=True, null=True, upload_to=laboratory.models_utils.upload_files, verbose_name='Are there establishments with a large concentration of people that could be exposed to the risk of an accident?'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='has_water_resources',
            field=models.BooleanField(default=False, verbose_name='Presence of rivers, streams, springs and aquifers'),
        ),
    ]
