# Generated by Django 5.1 on 2025-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0147_laboratory_area_laboratory_description_and_more'),
        ('risk_management', '0016_buildings_emergency_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regent',
            name='laboratories',
            field=models.ManyToManyField(related_name='regent_laboratories', to='laboratory.laboratory'),
        ),
    ]
