# Generated by Django 5.1 on 2025-04-30 22:58

import django.db.models.deletion
import laboratory.catalog
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0148_shelfobject_physical_status'),
        ('risk_management', '0017_regent_laboratories'),
    ]

    operations = [
        migrations.AddField(
            model_name='regent',
            name='type_regent',
            field=laboratory.catalog.GTForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.catalog', verbose_name='Type Regent'),
        ),
    ]
