# Generated by Django 5.1 on 2025-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0018_regent_type_regent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regent',
            name='type_regent',
            field=models.CharField(choices=[('chemical', 'Chemical'), ('chemical_engineer', 'Chemical Engineer'), ('veterinarian', 'Veterinarian')], default='chemical', max_length=100, verbose_name='Type Regent'),
        ),
    ]
