# Generated by Django 6.0.2 on 2026-02-13 22:49


from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0020_establishmentlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishmentlogs",
            name="date",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="establishmentlogs",
            name="environmental",
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name="establishmentlogs",
            name="health",
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name="establishmentlogs",
            name="physical",
            field=models.FloatField(default=False),
        ),
    ]
