# Generated by Django 6.0.2 on 2026-02-16 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0021_establishmentlogs_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishmentlogs",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
