# Generated by Django 5.2.11 on 2026-03-18 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0022_alter_establishmentlogs_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildings",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible",
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="regents",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="regents",
                to="risk_management.regent",
                verbose_name="Regents Associated",
            ),
        ),
    ]
