# Generated by Django 5.2.11 on 2026-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0022_alter_establishmentlogs_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishmentlogs",
            name="xls_content",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
