# Generated by Django 5.2.11 on 2026-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0023_alter_buildings_manager_alter_buildings_regents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildings",
            name="regents",
            field=models.ManyToManyField(
                blank=True,
                related_name="regents",
                to="risk_management.regent",
                verbose_name="Regents Associated",
            ),
        ),
    ]
