# Generated by Django 5.2.11 on 2026-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0024_alter_buildings_regents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskzone",
            name="priority",
            field=models.SmallIntegerField(default=0, verbose_name="Priority"),
        ),
    ]
