# Generated by Django 5.2.11 on 2026-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0023_establishmentlogs_xls_content"),
        ("risk_management", "0025_alter_riskzone_priority"),
    ]

    operations = []
