# Generated by Django 5.2.11 on 2026-03-20 17:34

from django.db import migrations


from django.db import migrations


def move_riskzones_to_root(apps, schema_editor):
    OrganizationStructure = apps.get_model("laboratory", "OrganizationStructure")
    RiskZone = apps.get_model("risk_management", "RiskZone")
    Buildings = apps.get_model("risk_management", "Buildings")

    root_org = OrganizationStructure.objects.filter(parent__isnull=True).first()
    if root_org:
        RiskZone.objects.exclude(organization=root_org).update(organization=root_org)
        Buildings.objects.exclude(organization=root_org).update(organization=root_org)


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0026_merge_20260319_1639"),
    ]

    operations = [
        migrations.RunPython(move_riskzones_to_root, migrations.RunPython.noop),
    ]
