# Generated by Django 5.2.11 on 2026-03-20

from django.db import migrations
from django.db.models import Count


def clean_names(apps, schema_editor):
    RiskZone = apps.get_model("risk_management", "RiskZone")
    Buildings = apps.get_model("risk_management", "Buildings")

    for model in [RiskZone, Buildings]:
        for obj in model.objects.all():
            cleaned = obj.name.replace("\xa0", " ").strip()
            if cleaned != obj.name:
                obj.name = cleaned
                obj.save(update_fields=["name"])


def merge_duplicate_riskzones(apps, schema_editor):
    RiskZone = apps.get_model("risk_management", "RiskZone")
    IncidentReport = apps.get_model("risk_management", "IncidentReport")
    EstablishmentLogs = apps.get_model("risk_management", "EstablishmentLogs")
    ContentType = apps.get_model("contenttypes", "ContentType")

    rz_ct = ContentType.objects.get_for_model(RiskZone)

    duplicates = (
        RiskZone.objects.values("name")
        .annotate(c=Count("pk"))
        .filter(c__gt=1)
    )

    for group in duplicates:
        zones = RiskZone.objects.filter(name=group["name"]).order_by("pk")
        survivor = zones.first()
        to_delete = zones.exclude(pk=survivor.pk)

        max_workers = survivor.num_workers
        max_priority = survivor.priority

        for dupe in to_delete:
            survivor.laboratories.add(*dupe.laboratories.all())
            survivor.buildings.add(*dupe.buildings.all())
            IncidentReport.objects.filter(risk_zone=dupe).update(risk_zone=survivor)
            EstablishmentLogs.objects.filter(
                content_type=rz_ct, object_id=dupe.pk
            ).update(object_id=survivor.pk)
            if dupe.num_workers > max_workers:
                max_workers = dupe.num_workers
            if dupe.priority > max_priority:
                max_priority = dupe.priority

        survivor.num_workers = max_workers
        survivor.priority = max_priority
        survivor.save(update_fields=["num_workers", "priority"])
        to_delete.delete()


def merge_duplicate_buildings(apps, schema_editor):
    Buildings = apps.get_model("risk_management", "Buildings")

    duplicates = (
        Buildings.objects.values("name")
        .annotate(c=Count("pk"))
        .filter(c__gt=1)
    )

    for group in duplicates:
        buildings = Buildings.objects.filter(name=group["name"]).order_by("pk")
        survivor = buildings.first()
        to_delete = buildings.exclude(pk=survivor.pk)

        for dupe in to_delete:
            survivor.laboratories.add(*dupe.laboratories.all())
            survivor.regents.add(*dupe.regents.all())
            survivor.nearby_buildings.add(
                *dupe.nearby_buildings.exclude(pk=survivor.pk)
            )
            for rz in dupe.riskzone_set.all():
                rz.buildings.add(survivor)
            for incident in dupe.incident_buildings.all():
                incident.buildings.add(survivor)
            for structure in dupe.structura_buildings.all():
                structure.buildings.add(survivor)
            for b in dupe.near_buildings_as.exclude(pk=survivor.pk):
                b.nearby_buildings.add(survivor)

        to_delete.delete()


def assign_labs_to_riskzones(apps, schema_editor):
    RiskZone = apps.get_model("risk_management", "RiskZone")
    Laboratory = apps.get_model("laboratory", "Laboratory")

    for rz in RiskZone.objects.all():
        labs = Laboratory.objects.filter(
            buildings__in=rz.buildings.all()
        ).distinct()
        new_labs = labs.exclude(pk__in=rz.laboratories.all())
        if new_labs.exists():
            rz.laboratories.add(*new_labs)


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0027_move_riskzones_to_root_org"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(clean_names, migrations.RunPython.noop),
        migrations.RunPython(merge_duplicate_riskzones, migrations.RunPython.noop),
        migrations.RunPython(merge_duplicate_buildings, migrations.RunPython.noop),
        migrations.RunPython(assign_labs_to_riskzones, migrations.RunPython.noop),
    ]
