# Generated by Django 5.2.11 on 2026-03-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0026_merge_20260319_1159"),
        ("risk_management", "0028_merge_duplicate_riskzones_and_buildings"),
    ]

    operations = []
