# Generated by Django 5.2.11 on 2026-03-24 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0182_alter_informscheduler_active"),
        ("risk_management", "0028_auto_20260320_1140"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "workday",
                    models.CharField(
                        choices=[
                            ("day shift", "Day shift"),
                            ("mixed shift", "Mixed shift"),
                            ("night shift", "Night shift"),
                        ],
                        max_length=20,
                        verbose_name="Workday",
                    ),
                ),
                (
                    "num_workers",
                    models.SmallIntegerField(verbose_name="Number of workers (aprox)"),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.organizationstructure",
                    ),
                ),
                (
                    "risk_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_management.riskzone",
                        verbose_name="Risk Zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
