# Generated by Django 5.2.11 on 2026-03-20 15:50

from django.db import migrations


def move_buildgins_to_root(apps, schema_editor):
    OrganizationStructure = apps.get_model("laboratory", "OrganizationStructure")
    Buildings = apps.get_model("risk_management", "Buildings")

    root_org = OrganizationStructure.objects.filter(parent__isnull=True).first()
    if root_org:
        Buildings.objects.exclude(organization=root_org).update(organization=root_org)


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0029_merge_20260320_0841"),
    ]

    operations = [
        migrations.RunPython(move_buildgins_to_root, migrations.RunPython.noop),
    ]
