# Generated by Django 5.2.11 on 2026-04-08 17:15

from django.db import migrations


def create_new_catalog(apps, schema_editor):
    Catalog = apps.get_model("laboratory", "Catalog")
    Catalog.objects.get_or_create(key="distance_unit", description="Metros cúbicos")


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0029_workday"),
    ]

    operations = [
        migrations.RunPython(create_new_catalog, reverse_code=migrations.RunPython.noop)
    ]
