# Generated by Django 5.2.11 on 2026-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0030_auto_20260408_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="area",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Area/Volume"
            ),
        ),
    ]
