# Generated by Django 5.2.11 on 2026-06-27 05:42

import django.db.models.deletion
import laboratory.catalog
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0207_alter_shelfobject_options'),
        ('risk_management', '0031_alter_structure_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPERAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField(verbose_name='Assessment date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('obsolete', 'Obsolete')], default='draft', max_length=20, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Next update due date')),
                ('source', models.CharField(choices=[('periodic', 'Periodic'), ('on_demand', 'On demand'), ('zone_request', 'Risk zone request')], default='on_demand', max_length=20, verbose_name='Source')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iper_assessments', to='laboratory.laboratory', verbose_name='Laboratory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='risk_management.iperassessment', verbose_name='Previous version')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iper_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsible')),
            ],
            options={
                'verbose_name': 'IPER assessment',
                'verbose_name_plural': 'IPER assessments',
                'ordering': ('-assessment_date', '-version', '-pk'),
                'permissions': [('view_all_iper', 'Can view all IPER assessments in the organization'), ('request_iper', 'Can request laboratories to fill the IPER'), ('view_iper_dashboard', 'Can view the IPER risk dashboard'), ('manage_iper_catalog', 'Can manage IPER catalog and risk matrix (root org)')],
            },
        ),
        migrations.CreateModel(
            name='IPERConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('period_months', models.PositiveIntegerField(default=12, verbose_name='Update period (months)')),
                ('reminder_days_before', models.PositiveIntegerField(default=30, verbose_name='Remind days before due date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iper_configs', to='laboratory.laboratory', verbose_name='Laboratory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
            ],
            options={
                'verbose_name': 'IPER configuration',
                'verbose_name_plural': 'IPER configurations',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='IPERHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Hazard description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Hazard location')),
                ('risk_priority', models.SmallIntegerField(default=0, editable=False, verbose_name='Risk priority')),
                ('controls', models.TextField(blank=True, verbose_name='Implemented controls')),
                ('recommended_controls', models.TextField(blank=True, verbose_name='Recommended controls')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='risk_management.iperassessment', verbose_name='Assessment')),
                ('category', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_hazard_category', to='laboratory.catalog', verbose_name='Hazard classification')),
                ('consequence', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_hazard_consequence', to='laboratory.catalog', verbose_name='Consequence')),
                ('probability', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_hazard_probability', to='laboratory.catalog', verbose_name='Probability')),
                ('related_shelfobjects', models.ManyToManyField(blank=True, related_name='iper_hazards', to='laboratory.shelfobject', verbose_name='Related inventory items')),
                ('risk_level', laboratory.catalog.GTForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_hazard_risk_level', to='laboratory.catalog', verbose_name='Risk level')),
            ],
            options={
                'verbose_name': 'IPER hazard',
                'verbose_name_plural': 'IPER hazards',
                'ordering': ('-risk_priority', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='IPERObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Observation')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='risk_management.iperassessment', verbose_name='Assessment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iper_observations', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'IPER observation',
                'verbose_name_plural': 'IPER observations',
                'ordering': ('-creation_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='IPERRiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_matrix_consequence', to='laboratory.catalog', verbose_name='Consequence')),
                ('probability', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_matrix_probability', to='laboratory.catalog', verbose_name='Probability')),
                ('risk_level', laboratory.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iper_matrix_risk_level', to='laboratory.catalog', verbose_name='Risk level')),
            ],
            options={
                'verbose_name': 'IPER risk matrix',
                'verbose_name_plural': 'IPER risk matrix',
                'ordering': ['pk'],
                'unique_together': {('probability', 'consequence')},
            },
        ),
    ]
