# Generated by Django 5.2.11 on 2026-06-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0033_seed_iper"),
    ]

    operations = [
        migrations.AddField(
            model_name="iperassessment",
            name="is_anonymous",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, the laboratory name is hidden in public listings.",
                verbose_name="Anonymous",
            ),
        ),
    ]
