# Generated by Django 5.2.11 on 2026-07-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_management", "0034_iperassessment_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iperconfig",
            name="period_months",
            field=models.PositiveIntegerField(
                default=6, verbose_name="Update period (months)"
            ),
        ),
    ]
