# Generated by Django 5.2.11 on 2026-08-29 21:20

import djgentelella.fields.maps
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0036_alter_buildings_manager_alter_structure_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='geolocation',
            field=djgentelella.fields.maps.GTPointField(default='9.895804362670006,-84.1552734375', zoom=15),
        ),
        migrations.AlterField(
            model_name='structure',
            name='geolocation',
            field=djgentelella.fields.maps.GTPointField(default='9.895804362670006,-84.1552734375', verbose_name='Geolocation', zoom=15),
        ),
    ]
