#!/bin/bash

NAME="beat_organilab"                                  # Name of the application
DJANGODIR=/organilab            # Django project directory
DJANGO_SETTINGS_MODULE=organilab.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=organilab.wsgi                     # WSGI module name

exec  celery beat -A organilab --schedule /organilab/beat.db --loglevel=INFO
