#!/bin/bash
 
NAME="organilabCelery" # Name of the application 
DJANGODIR=/organilab # Django project directory 
NUM_WORKERS=2 # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=organilab.settings # which settings file should Django use 
DJANGO_WSGI_MODULE=organilab.wsgi  # WSGI module name 

cd $DJANGODIR 

exec celery worker -A organilab -l info  -c $NUM_WORKERS --pidfile="/run/worker_`date  +"%Y%m%d%H%M%S"`.pid"

