# Generated by Django 4.0.8 on 2022-10-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import connection

def update_profilepermission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ProfilePermission = apps.get_model("auth_and_perms", "ProfilePermission")
    oldPP = {}
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, laboratories_id, profile_id FROM laboratory_profilepermission")
        for row in cursor.fetchall():
            pp=ProfilePermission(
                content_type= ContentType.objects.get(app_label='laboratory', model="laboratory"),
                object_id = row[1],
                profile_id = row[2]
            )
            pp.save()
            oldPP[row[0]] = pp.pk

    with connection.cursor() as cursor:
        cursor.execute("SELECT id, rol_id, profilepermission_id FROM laboratory_profilepermission_rol")
        for row in cursor.fetchall():
            cursor.execute("INSERT INTO auth_and_perms_profilepermission_rol (id, rol_id, profilepermission_id) VALUES (%s, %s, %s);",
                           [row[0], row[1], oldPP[row[2]] ]
                           )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('laboratory', '0049_alter_organizationstructure_managers_and_more')
    ]

    operations = [

        migrations.RunSQL(
            "ALTER TABLE laboratory_profile RENAME TO auth_and_perms_profile;",
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('phone_number', models.CharField(default='', max_length=25, verbose_name='Phone')),
                        ('id_card', models.CharField(max_length=100, verbose_name='ID Card')),
                        ('job_position', models.CharField(max_length=100, verbose_name='Job Position')),
                        ('laboratories',
                         models.ManyToManyField(blank=True, to='laboratory.laboratory', verbose_name='Laboratories')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                      to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),

        migrations.RunSQL(
            "ALTER TABLE laboratory_rol RENAME TO auth_and_perms_rol;",
            state_operations=[
                migrations.CreateModel(
                    name='Rol',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=100)),
                        ('permissions',
                         models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
                    ],
                    options={
                        'verbose_name': 'Rol',
                        'verbose_name_plural': 'Rols',
                    },
                ),
            ],
        ),

        migrations.RunSQL("ALTER TABLE laboratory_profile_laboratories RENAME TO auth_and_perms_profile_laboratories;"),
        migrations.RunSQL("ALTER TABLE laboratory_rol_permissions RENAME TO auth_and_perms_rol_permissions;"),

        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_and_perms.profile', verbose_name='Profile')),
                ('rol', models.ManyToManyField(blank=True, to='auth_and_perms.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Profile Rol',
                'verbose_name_plural': 'Profile Rols',
            },
        ),
        migrations.AddIndex(
            model_name='profilepermission',
            index=models.Index(fields=['content_type', 'object_id'], name='auth_and_pe_content_743b00_idx'),
        ),
        migrations.RunPython(update_profilepermission)
    ]
