# Generated by Django 4.0.8 on 2022-10-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS constance_config;"),
        migrations.RunSQL("DROP TABLE IF EXISTS guardian_groupobjectpermission;"),
        migrations.RunSQL("DROP TABLE IF EXISTS guardian_userobjectpermission;"),

        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_printobject_advertisements\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_printobject_contacts\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_printobject_paperType\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_printobject_schedules\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_advertisement_usersNotified\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_advertisement\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_contact\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_papertype\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_schedule\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_requestlabelprint\";"),
        migrations.RunSQL("DROP TABLE IF EXISTS public.\"printOrderManager_printobject\";"),

        migrations.RunSQL("DROP TABLE IF EXISTS zinnia_entry_authors;"),
        migrations.RunSQL("DROP TABLE IF EXISTS zinnia_entry_categories;"),
        migrations.RunSQL("DROP TABLE IF EXISTS zinnia_entry_related;"),
        migrations.RunSQL("DROP TABLE IF EXISTS zinnia_entry_sites;"),
        migrations.RunSQL("DROP TABLE IF EXISTS zinnia_category;"),
        migrations.RunSQL("DROP TABLE IF EXISTS zinnia_entry;"),
        migrations.RunSQL("DROP TABLE IF EXISTS chunked_upload_chunkedupload;")
    ]
