# Generated by Django 4.0.8 on 2022-10-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0002_clean_old_tables'),
    ]

    operations = [

        migrations.RunSQL("""
BEGIN;
SELECT setval(pg_get_serial_sequence('"auth_and_perms_profile_laboratories"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_and_perms_profile_laboratories";
SELECT setval(pg_get_serial_sequence('"auth_and_perms_profile"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_and_perms_profile";
SELECT setval(pg_get_serial_sequence('"auth_and_perms_rol_permissions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_and_perms_rol_permissions";
SELECT setval(pg_get_serial_sequence('"auth_and_perms_rol"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_and_perms_rol";
SELECT setval(pg_get_serial_sequence('"auth_and_perms_profilepermission_rol"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_and_perms_profilepermission_rol";
SELECT setval(pg_get_serial_sequence('"auth_and_perms_profilepermission"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_and_perms_profilepermission";
COMMIT;
        """)
    ]
