# Generated by Django 4.0.8 on 2022-10-21 03:29

import auth_and_perms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0003_update_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='color',
            field=models.CharField(default=auth_and_perms.models.get_random_color, max_length=20),
        ),
    ]
