# Generated by Django 4.0.8 on 2023-01-21 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_and_perms', '0007_alter_authenticatedatarequest_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotpdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
