# Generated by Django 4.0.8 on 2023-03-23 01:28

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0008_alter_usertotpdevice_user'),
    ]

    operations = [


    ]
