# Generated by Django 4.0.8 on 2023-07-08 16:30

from django.db import migrations

PERMS = ['academic.add_componentsga', 'academic.change_componentsga',
         'academic.delete_componentsga', 'academic.view_componentsga',
         'academic.add_substanceobservation', 'academic.change_substanceobservation',
         'academic.delete_substanceobservation', 'academic.view_substanceobservation',
         'academic.add_substancesga', 'academic.change_substancesga',
         'academic.delete_substancesga', 'academic.view_substancesga',
         'academic.add_sustancecharacteristicssga',
         'academic.change_sustancecharacteristicssga',
         'academic.delete_sustancecharacteristicssga',
         'academic.view_sustancecharacteristicssga', 'auth.add_author',
         'auth.change_author', 'auth.delete_author', 'authentication.add_demorequest',
         'authentication.change_demorequest', 'authentication.delete_demorequest',
         'authentication.view_demorequest', 'authentication.add_feedbackentry',
         'authentication.change_feedbackentry', 'authentication.delete_feedbackentry',
         'authentication.view_feedbackentry', 'chunked_upload.add_chunkedupload',
         'chunked_upload.change_chunkedupload', 'chunked_upload.delete_chunkedupload',
         'chunked_upload.view_chunkedupload', 'constance.change_config',
         'database.add_constance', 'database.change_constance',
         'database.delete_constance', 'database.view_constance',
         'django_comments.add_comment', 'django_comments.can_moderate',
         'django_comments.change_comment', 'django_comments.delete_comment',
         'django_comments.add_commentflag', 'django_comments.change_commentflag',
         'django_comments.delete_commentflag', 'guardian.add_groupobjectpermission',
         'guardian.change_groupobjectpermission',
         'guardian.delete_groupobjectpermission', 'guardian.add_userobjectpermission',
         'guardian.change_userobjectpermission', 'guardian.delete_userobjectpermission',
         'laboratory.add_feedbackentry', 'laboratory.change_feedbackentry',
         'laboratory.delete_feedbackentry', 'laboratory.view_feedbackentry',
         'laboratory.view_shelf', 'laboratory.add_organizationusermanagement',
         'laboratory.change_organizationusermanagement',
         'laboratory.delete_organizationusermanagement',
         'laboratory.view_organizationusermanagement',
         'laboratory.add_organizationusermanagement',
         'laboratory.change_organizationusermanagement',
         'laboratory.delete_organizationusermanagement',
         'laboratory.view_organizationusermanagement',
         'laboratory.add_principaltechnician', 'laboratory.change_principaltechnician',
         'laboratory.delete_principaltechnician', 'laboratory.view_principaltechnician',
         'laboratory.add_profilepermission', 'laboratory.change_profilepermission',
         'laboratory.delete_profilepermission', 'laboratory.view_profilepermission',
         'laboratory.add_rol', 'laboratory.change_rol', 'laboratory.delete_rol',
         'laboratory.view_rol', 'laboratory.view_shelfobjects',
         'laboratory.add_solution', 'laboratory.change_solution',
         'laboratory.delete_solution', 'laboratory.view_solution',
         'laboratory.view_Solution', 'printOrderManager.add_advertisement',
         'printOrderManager.change_advertisement',
         'printOrderManager.delete_advertisement', 'printOrderManager.add_contact',
         'printOrderManager.change_contact', 'printOrderManager.delete_contact',
         'printOrderManager.add_papertype', 'printOrderManager.change_papertype',
         'printOrderManager.delete_papertype', 'printOrderManager.add_printobject',
         'printOrderManager.changeAdvertisements_printObject',
         'printOrderManager.changeContacts_printObject',
         'printOrderManager.changeInformation_printObject',
         'printOrderManager.changePaper_printObject',
         'printOrderManager.change_printobject',
         'printOrderManager.changeSchedules_printObject',
         'printOrderManager.delete_printobject', 'printOrderManager.view_printobject',
         'printOrderManager.add_requestlabelprint',
         'printOrderManager.change_requestlabelprint',
         'printOrderManager.delete_requestlabelprint', 'printOrderManager.add_schedule',
         'printOrderManager.change_schedule', 'printOrderManager.delete_schedule',
         'sga.add_personaltemplatesga', 'sga.change_personaltemplatesga',
         'sga.delete_personaltemplatesga', 'sga.view_personaltemplatesga',
         'sga.add_donation', 'sga.change_donation', 'sga.delete_donation',
         'sga.view_donation', 'sga.add_pictogram', 'sga.change_pictogram',
         'sga.delete_pictogram', 'sga.view_pictogram', 'sga.add_prudence_advice',
         'sga.change_prudence_advice', 'sga.delete_prudence_advice', 'sga.add_sustance',
         'sga.change_sustance', 'sga.delete_sustance', 'sga.view_sustance',
         'sga.view_label', 'sga.add_warningcategory', 'sga.change_warningcategory',
         'sga.delete_warningcategory', 'sga.view_warningclass', 'tagging.add_tag',
         'tagging.change_tag', 'tagging.delete_tag', 'tagging.view_tag',
         'tagging.add_taggeditem', 'tagging.change_taggeditem',
         'tagging.delete_taggeditem', 'tagging.view_taggeditem', 'zinnia.add_category',
         'zinnia.change_category', 'zinnia.delete_category', 'zinnia.add_entry',
         'zinnia.can_change_author', 'zinnia.can_change_status', 'zinnia.can_view_all',
         'zinnia.change_entry', 'zinnia.delete_entry']


def remove_unused_perms(apps, schema_editor):
    for perm in PERMS:
        Permission = apps.get_model('auth', 'Permission')
        app_label, codename = perm.split('.')
        Permission.objects.filter(content_type__app_label=app_label,
                                  codename=codename).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0114_shelfobject_container"),
        ('auth_and_perms', '0009_rolbyorganizatio'), ]

    operations = [migrations.RunPython(remove_unused_perms,
                                       reverse_code=migrations.RunPython.noop)]
