# Generated by Django 4.1.10 on 2023-12-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0011_profile_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_external_user_in_org', 'Can add external user to organization'),)},
        ),
    ]
