# Generated by Django 4.1.13 on 2024-04-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_external_user_in_org', 'Can add external user to organization'), ('can_manage_users', 'Can manage users'))},
        ),
    ]
