# Generated by Django 4.1.13 on 2024-05-14 19:35

from django.db import migrations

def create_user_default(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create(username="soporte@organilab.org", email="soporte@organilab.org",
                        first_name="Usuario preservador de integridad")

def delete_user_default(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username="soporte@organilab.org").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0013_alter_profile_options'),
    ]

    operations = [
        migrations.RunPython(create_user_default,
                             reverse_code=delete_user_default)
    ]
