# Generated by Django 4.1.10 on 2024-05-11 23:42

from django.db import migrations

def register_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
#    OrganizationStructure = apps.get_model('laboratory', 'OrganizationStructure')
    Rol = apps.get_model('auth_and_perms', 'Rol')
# ProfilePermission.objects.get_or_create(profile=profile, content_type=ct, object_id=profile.pk)
    perms=Permission.objects.filter(codename__icontains='change_impostorlog')
    g, ok=Group.objects.get_or_create(name='RegisterOrganization')
    g.permissions.add(*perms)

    rols=Rol.objects.filter(name__icontains='Administración de Organización')
    for rol in rols:
        rol.permissions.add(*perms)

class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0015_impostorlog_active'),
    ]

    operations = [
        migrations.RunPython(register_permissions,
                             reverse_code=migrations.RunPython.noop)
    ]
