# Generated by Django 5.1 on 2025-03-27 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0016_addpermissiontoadmingroup"),
        ("laboratory", "0145_alter_baseunitvalues_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.TextField(blank=True, null=True, verbose_name="Location"),
        ),
    ]
