# Generated by Django 4.1.10 on 2024-05-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0014_create_user_default'),
        ('auth_and_perms', '0016_addpermissiontoadmingroup'),
    ]

    operations = [
    ]
