# Generated by Django 5.1 on 2025-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0017_profile_location_regent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Address"
            ),
        ),
    ]
