# Generated by Django 4.1.13 on 2024-05-21 16:13

from django.db import migrations
import zoneinfo

def register_tasks(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule6, _ = CrontabSchedule.objects.get_or_create(minute='0', hour='6',
                                                         day_of_week='*',
                                                         day_of_month='*',
                                                         month_of_year='*',
                                                         timezone=zoneinfo.ZoneInfo(
                                                             'America/Costa_Rica')
                                                         )
    PeriodicTask.objects.create(crontab=schedule6,
                                name='Update Delete Users List',
                                task='auth_and_perms.tasks.update_delete_users_list')

    schedule7, _ = CrontabSchedule.objects.get_or_create(minute='0', hour='7',
                                                         day_of_week='*',
                                                         day_of_month='*',
                                                         month_of_year='*',
                                                         timezone=zoneinfo.ZoneInfo(
                                                             'America/Costa_Rica')
                                                         )
    PeriodicTask.objects.create(crontab=schedule7,
                                name='Send Warning Notification Delete User',
                                task='auth_and_perms.tasks.send_notification_warning_delete_user')


def delete_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    PeriodicTask.objects.filter(name__in=[
        "Update Delete Users List", "Send Warning Notification Delete User"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0018_deleteuserlist'),
    ]

    operations = [
        migrations.RunPython(register_tasks, reverse_code=delete_periodic_tasks),
    ]
