# Generated by Django 4.1.13 on 2024-05-21 16:13

from django.db import migrations
import zoneinfo

def register_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = CrontabSchedule.objects.get_or_create(minute='0', hour='24',
                                                        day_of_week='*',
                                                        day_of_month='*',
                                                        month_of_year='*',
                                                        timezone=zoneinfo.ZoneInfo('America/Costa_Rica')
                                                        )
    PeriodicTask.objects.create(crontab=schedule,
                                name='Update Delete Users List',
                                task='auth_and_perms.tasks.update_delete_users_list')


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0018_deleteuserlist'),
    ]

    operations = [
        migrations.RunPython(register_task, reverse_code=migrations.RunPython.noop),
    ]
