# Generated by Django 5.2.8 on 2026-01-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0018_remove_profile_location_profile_address'),
        ('laboratory', '0165_laboratory_faculty_dispatch_laboratory_workplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workplace',
            field=models.ManyToManyField(blank=True, related_name='profile_workplace', to='laboratory.organizationstructure', verbose_name='Workplace'),
        ),
    ]
