# Generated by Django 4.1.10 on 2024-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0019_register_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteuserlist',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
