# Generated by Django 5.2.8 on 2026-01-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0020_rol_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
