# Generated by Django 5.2.8 on 2026-02-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0021_alter_rol_description_alter_rol_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    (
                        "can_add_external_user_in_org",
                        "Can add external user to organization",
                    ),
                    ("una_can_access", "UNA puede acceder"),
                ]
            },
        ),
    ]
