# Generated by Django 5.2.8 on 2026-02-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0023_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="identification",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identification"
            ),
        ),
    ]
