# Generated by Django 5.2.8 on 2026-02-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0023_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_card",
            field=models.CharField(max_length=100, verbose_name="Identification"),
        ),
    ]
