# Generated by Django 5.2.11 on 2026-03-12 22:21

from django.db import migrations


def register_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")
    perms = Permission.objects.filter(codename__icontains="can_manage_permissions")
    g, ok = Group.objects.get_or_create(name="Manage Roles Permissions")
    profile, ok = Group.objects.get_or_create(name="Profile")
    g.permissions.add(*perms)
    update_profile_perms = Permission.objects.filter(
        name="Can change user", codename="change_user"
    )
    if update_profile_perms:
        for user in User.objects.all():
            user.groups.add(profile)


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0024_alter_profile_id_card"),
    ]

    operations = [
        migrations.RunPython(
            register_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
