# Generated by Django 5.2.11 on 2026-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0026_remove_unused_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_tutorials",
            field=models.BooleanField(
                default=True,
                help_text="Enable automatic tutorial display on page visits",
                verbose_name="Show tutorials",
            ),
        ),
    ]
