# Generated by Django 5.2.11 on 2026-05-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0027_profile_show_tutorials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_card",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Identification"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="job_position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Job Position"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=25, null=True, verbose_name="Phone"
            ),
        ),
    ]
