# Generated by Django 5.2.11 on 2026-06-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_and_perms",
            "0028_alter_profile_id_card_alter_profile_job_position_and_more",
        ),
        ("laboratory", "0198_organizationstructure_enable_child_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepermission",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_permissions",
                to="laboratory.organizationstructure",
                verbose_name="Organization",
            ),
        ),
    ]
