# Generated by Django 5.2.11 on 2026-06-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0029_profilepermission_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_add_external_user_in_org', 'Can add external user to organization'), ('institution_can_access', 'Institution can access'), ('change_own_profile', 'Can change own user/profile data')]},
        ),
    ]
