# Generated by Django 5.2.11 on 2026-09-08 02:01

import organilab.model_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0034_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=organilab.model_defaults.get_language_choices, default=organilab.model_defaults.get_default_language, max_length=4, verbose_name='Language'),
        ),
    ]
