# Generated by Django 5.2.11 on 2026-09-16 19:16

import auth_and_perms.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0035_alter_profile_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_add_external_user_in_org', 'Can add external user to organization'), ('institution_can_access', 'Institution can access'), ('change_own_profile', 'Can change own user/profile data'), ('can_manage_users', 'Can delete and merge users of the whole platform')]},
        ),
        migrations.CreateModel(
            name='UserDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Manual'), (2, 'Inactive user')], default=1, verbose_name='Reason')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('expiration_date', models.DateTimeField(default=auth_and_perms.models.get_user_deletion_expiration, verbose_name='Expiration date')),
                ('warnings_sent', models.JSONField(blank=True, default=list, help_text='Days before expiration for which a warning was already sent', verbose_name='Warnings sent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User deletion request',
                'verbose_name_plural': 'User deletion requests',
                'ordering': ('expiration_date',),
            },
        ),
    ]
