# Generated by Django 4.0.8 on 2022-12-23 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('related_file', models.FileField(blank=True, null=True, upload_to='media/feedback_entries/', verbose_name='Related file')),
                ('laboratory_id', models.IntegerField(default=0, null=True, verbose_name='Laboratory id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback entry',
                'verbose_name_plural': 'Feedback entries',
            },
        ),
    ]
