# Generated by Django 4.0.8 on 2023-03-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('presentation', '0002_feedbackentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_url', models.TextField(null=True, verbose_name='QR Url')),
                ('qr_image', models.TextField(null=True, verbose_name='Image QR on SVG')),
                ('b64_image', models.TextField(null=True, verbose_name='Base64 Image QR')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
