# Generated by Django 4.0.8 on 2023-03-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0088_merge_20230303_2031'),
        ('presentation', '0003_qrmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrmodel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure'),
        ),
    ]
