# Generated by Django 4.0.8 on 2023-04-21 19:51

from django.db import migrations
from django.urls import reverse


def load_notificacion(apps, schema_editor):
    model = apps.get_model("djgentelella", "MenuItem")
    model.objects.create(
            parent = None,
            title = 'top_navigation',
            url_name ='djgentelella.notification.widgets.NotificationMenu',
            category = 'main',
            is_reversed = False,
            reversed_kwargs = None,
            reversed_args = reverse('notifications'),
            is_widget = True,
            icon = 'fa fa-envelope',
            only_icon = False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_qrmodel_organization'),
    ]

    operations = [
        migrations.RunPython(load_notificacion, reverse_code=migrations.RunPython.noop),
    ]
