# Generated by Django 5.2.11 on 2026-03-20 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_and_perms", "0027_profile_show_tutorials"),
        ("presentation", "0006_alter_donation_id_alter_feedbackentry_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "url_name",
                    models.CharField(
                        help_text="Django URL name where this tutorial applies. Comma-separated for multiple pages.",
                        max_length=500,
                        verbose_name="URL name(s)",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("PERMISOS", "Permissions"),
                            ("LABORATORIOS", "Laboratories"),
                            ("SUSTANCIAS", "Substances"),
                            ("PROCEDIMIENTOS", "Procedures"),
                            ("RESERVACIONES", "Reservations"),
                            ("TAREAS", "Scheduled Tasks"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="Chapter",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "auto_start",
                    models.BooleanField(
                        default=False,
                        help_text="Start automatically on first visit (if user has tutorials enabled)",
                        verbose_name="Auto start",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "target_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles that should see this tutorial. Empty = all users.",
                        to="auth_and_perms.rol",
                        verbose_name="Target roles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutorials",
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="TutorialProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(default=0, verbose_name="Current step"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="User temporarily dismissed this tutorial",
                        verbose_name="Dismissed",
                    ),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="presentation.tutorial",
                        verbose_name="Tutorial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial progress",
                "verbose_name_plural": "Tutorial progress",
                "unique_together": {("user", "tutorial")},
            },
        ),
        migrations.CreateModel(
            name="TutorialStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                ("step_key", models.SlugField(max_length=100, verbose_name="Step key")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "content",
                    models.TextField(help_text="Supports HTML", verbose_name="Content"),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("HIGHLIGHT", "Highlight element"),
                            ("MODAL", "Modal dialog"),
                            ("POPOVER", "Popover tooltip"),
                        ],
                        default="MODAL",
                        max_length=10,
                        verbose_name="Step type",
                    ),
                ),
                (
                    "css_selector",
                    models.CharField(
                        blank=True,
                        help_text="CSS selector of the target element to highlight",
                        max_length=500,
                        verbose_name="CSS selector",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("left", "Left"),
                            ("right", "Right"),
                        ],
                        default="bottom",
                        max_length=10,
                        verbose_name="Position",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate after this step (for cross-page tutorials)",
                        max_length=500,
                        verbose_name="Action URL",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tutorial_images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="presentation.tutorial",
                        verbose_name="Tutorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial step",
                "verbose_name_plural": "Tutorial steps",
                "ordering": ["order"],
                "unique_together": {("tutorial", "order"), ("tutorial", "step_key")},
            },
        ),
    ]
