# Generated by Django 5.2.11 on 2026-09-17 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0223_normalize_dataconfig'),
        ('presentation', '0010_fix_salas_muebles_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=150, verbose_name='Key')),
                ('raw_value', models.TextField(blank=True, default='', verbose_name='Value')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
            ],
            options={
                'verbose_name': 'System parameter',
                'verbose_name_plural': 'System parameters',
                'ordering': ['key'],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
