# Generated by Django 5.2.11 on 2026-09-17 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0223_normalize_dataconfig'),
        ('presentation', '0011_systemparameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=150, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('override_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Subject')),
                ('override_message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
            ],
            options={
                'verbose_name': 'Notification setting',
                'verbose_name_plural': 'Notification settings',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
