# Generated by Django 5.2.11 on 2026-09-17 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0035_alter_profile_language'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('laboratory', '0223_normalize_dataconfig'),
        ('presentation', '0012_notificationsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('process', models.CharField(max_length=150, verbose_name='Process')),
                ('threshold', models.JSONField(blank=True, default=dict, verbose_name='Threshold')),
                ('level', models.CharField(choices=[('info', 'Informative'), ('medium', 'Medium'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Level')),
                ('notification_code', models.SlugField(blank=True, default='', max_length=150, verbose_name='Email')),
                ('notify_responsible', models.BooleanField(default=True, verbose_name='Notify the responsible')),
                ('create_task', models.BooleanField(default=True, verbose_name='Create pending task')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notify_roles', models.ManyToManyField(blank=True, to='auth_and_perms.rol', verbose_name='Notify roles')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
                ('trigger', models.ForeignKey(limit_choices_to={'key': 'alert_trigger'}, on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='laboratory.catalog', verbose_name='Trigger')),
            ],
            options={
                'verbose_name': 'Alert rule',
                'verbose_name_plural': 'Alert rules',
                'ordering': ['process', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('level', models.CharField(choices=[('info', 'Informative'), ('medium', 'Medium'), ('critical', 'Critical')], max_length=20, verbose_name='Level')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Link')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='Recipients')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.organizationstructure')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='presentation.alertrule', verbose_name='Alert rule')),
            ],
            options={
                'verbose_name': 'Alert event',
                'verbose_name_plural': 'Alert events',
                'ordering': ['-creation_date'],
            },
        ),
    ]
