# Generated by Django 2.2.12 on 2020-05-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0001_squashed_0012_auto_20200320_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msdsobject',
            options={'ordering': ('pk',), 'verbose_name': 'MSDS Object', 'verbose_name_plural': 'MSDS Object'},
        ),
    ]
