# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0002_auto_20180630_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msdsobject',
            options={'ordering': ('pk',), 'permissions': (('view_msdsobject', 'Can see available MSDSObject'),), 'verbose_name': 'MSDS Object', 'verbose_name_plural': 'MSDS Object'},
        ),
        migrations.AlterField(
            model_name='msdsobject',
            name='file',
            field=models.FilePathField(verbose_name='MSDS File'),
        ),
        migrations.AlterField(
            model_name='msdsobject',
            name='product',
            field=models.CharField(max_length=300, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='msdsobject',
            name='provider',
            field=models.CharField(max_length=300, verbose_name='Provider'),
        ),
    ]
