# Generated by Django 4.1.2 on 2022-10-10 17:43

from django.db import migrations, models


def gen_position(apps, schema_editor):
    OrganilabNode = apps.get_model('msds', 'OrganilabNode')
    for obj in OrganilabNode.objects.all():
        obj.position = obj.tree_id * 100000 + obj.lft
        obj.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0003_auto_20200610_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organilabnode',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='organilabnode',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(gen_position, reverse_code=migrations.RunPython.noop),
    ]
