# Generated by Django 4.1.2 on 2022-10-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0004_alter_organilabnode_options_organilabnode_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organilabnode',
            name='level',
        ),
        migrations.RemoveField(
            model_name='organilabnode',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='organilabnode',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='organilabnode',
            name='tree_id',
        ),
    ]
