# Generated by Django 4.1.2 on 2022-10-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0005_remove_organilabnode_level_remove_organilabnode_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organilabnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='msds.organilabnode', verbose_name='parent'),
        ),
    ]
