# Generated by Django 4.0.8 on 2022-12-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0066_alter_protocol_file'),
        ('msds', '0006_alter_organilabnode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='msdsobject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.organizationstructure'),
        ),
    ]
