# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0007_organilabnode_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organilabnode',
            name='color',
        ),
        migrations.RemoveField(
            model_name='organilabnode',
            name='font',
        ),
        migrations.RemoveField(
            model_name='organilabnode',
            name='shape',
        ),
        migrations.AddField(
            model_name='organilabnode',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='organilabnode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nodes/'),
        ),
    ]
