# Generated by Django 4.1.11 on 2023-10-13 19:37

import django.core.validators
from django.db import migrations, models
import msds.models


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0008_msdsobject_created_by_msdsobject_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msdsobject',
            name='file',
            field=models.FileField(upload_to=msds.models.upload_msds, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='MSDS File'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='file',
            field=models.FileField(upload_to=msds.models.upload_regulation_document, verbose_name='Regulation File'),
        ),
    ]
