# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0008_auto_20180709_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organilabnode',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organilabnode',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organilabnode',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
