# Generated by Django 5.1 on 2025-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msds", "0009_alter_msdsobject_file_alter_regulationdocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msdsobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="organilabnode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="regulationdocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
