# Generated by Django 5.2.11 on 2026-03-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0010_alter_msdsobject_id_alter_organilabnode_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MSDSObject',
        ),
    ]
