# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msds', '0010_regulationdocument'),
        ('msds', '0010_auto_20200118_0034'),
    ]

    operations = [
    ]
